New post: Smaller is better: Q8-Chat, an efficient generative AI experience on Xeon
huggingface/blog pull request #1084
Opened 2023-05-08 12:29 UTC by juliensimon

2023-05-08 12:33 UTC, juliensimon commented
Flying to the US in a couple of hours. Please fix anything that's needed and don't wait for me :)

2023-05-08 13:33 UTC, mfuntowicz approved these changes
LGTM!

2023-05-08 15:30 UTC, jeffboudier approved these changes
Great post!

2023-05-08 15:47 UTC, echarlaix approved these changes
Looks great @juliensimon !

2023-05-08 15:49 UTC, juliensimon commented
@Michellehbn I'm boarding in 15 minutes, which doesn't leave much me room for post-merge fixes if any are needed. Would me mind taking care of it when you have a moment? Tomorrow morning would work too if you're too busy. Many thanks.

2023-05-08 17:35 UTC, ofirzaf requested changes
I wasn't sure how to make some of the changes myself or only you can make changes. Let me know how to proceed. Thanks!

2023-05-08 17:35 UTC, ofirzaf commented on generative-ai-models-on-intel-cpu.md
> +
Need to add a title to the figure "OPT-13B Input to layer 3.FC1", we produced this figure ourselves if it matters

2023-05-08 17:35 UTC, ofirzaf commented on generative-ai-models-on-intel-cpu.md
> +
In the end we used the example from OPT, should change Llama-7B to OPT-13B

2023-05-08 17:35 UTC, ofirzaf commented on generative-ai-models-on-intel-cpu.md
> +The table below presents a summary of their findings. The second column shows the ratio of benchmarks that have improved post-quantization. The third column contain the mean average degradation (a ne
Add a \*, (* a negativa ...) So it will be clear the * in the table refers to this comment

2023-05-08 17:35 UTC, ofirzaf commented on generative-ai-models-on-intel-cpu.md
> +The table below presents a summary of their findings. The second column shows the ratio of benchmarks that have improved post-quantization. The third column contain the mean average degradation (a ne
We think that the second column might be misunderstood, maybe it is better to talk about how many tasks preserves accuracy degradation of less than 1% or something like that, or add some clarification that it is ok that we are not improving accross all tasks because we are dealing with lossy compression, or remove it all-together.

2023-05-08 17:35 UTC, ofirzaf commented on generative-ai-models-on-intel-cpu.md
> +The obvious benefit of working with smaller models is a significant reduction in inference latency. Here’s a [video](https://drive.google.com/file/d/19PrWwJo-laXYppRzUZyR7s3M1zd_2Yfe/view?usp=share_l
We recorded a new video where it is clear where the compute cycle begins, https://drive.google.com/file/d/1h8C2I4xn1c0HdrzfMqBaYECJyqo5kcJL/view?usp=sharing

2023-05-09 07:08 UTC, Michellehbn approved these changes
Looks great!

2023-05-09 07:08 UTC, Michellehbn commented on generative-ai-models-on-intel-cpu.md
> +It only takes ~80 milliseconds to generate the first token. The mean generation time for the next tokens is an amazing ~40 milliseconds. This level of performance definitely makes it possible to to r
```suggestion
It only takes ~80 milliseconds to generate the first token. The mean generation time for the next tokens is an amazing ~40 milliseconds. This level of performance definitely makes it possible to run LLMs on CPU platforms, giving customers more IT flexibility and better cost-performance than ever before.
```

2023-05-09 07:08 UTC, Michellehbn commented on generative-ai-models-on-intel-cpu.md
> +Recently, Clement, the CEO of HuggingFace, said: “*More companies would be better served focusing on smaller, specific models that are cheaper to train and run.*” The emergence of relatively smaller
```suggestion
Clement, the CEO of HuggingFace, recently said: “*More companies would be better served focusing on smaller, specific models that are cheaper to train and run.*” The emergence of relatively smaller models like Alpaca, BloomZ and Vicuna, open a new opportunity for enterprises to lower the cost of fine-tuning and inference in production. As demonstrated above, high-quality quantization brings high-quality chat experiences to Intel CPU platforms, without the need of running mammoth LLMs and complex AI accelerators. 
```

2023-05-09 07:08 UTC, Michellehbn commented on generative-ai-models-on-intel-cpu.md
> +Together with Intel, we've hosted on Spaces a new exciting demo called [Q8-Chat](https://huggingface.co/spaces/Intel/Q8-Chat) (pronounced "Cute chat"). Q8-Chat offers you a ChatGPT-like chat experien
```suggestion
Together with Intel, we're hosting a new exciting demo in Spaces called [Q8-Chat](https://huggingface.co/spaces/Intel/Q8-Chat) (pronounced "Cute chat"). Q8-Chat offers you a ChatGPT-like chat experience, while only running on a single socket Intel Sapphire Rapids CPU with 32 cores and a batch size of 1.
```

2023-05-09 07:44 UTC, mfuntowicz commented
Thanks @Michellehbn, just included your suggestions 🤗

2023-05-11 00:29 UTC, ofirzaf commented on generative-ai-models-on-intel-cpu.md
> +We’re currently working on integrating these amazing new quantization techniques into the Hugging Face [Optimum Intel](https://huggingface.co/docs/optimum/intel/index) library. Once we’re done, you’l
Can you please add
"... into the Hugging Face [Optimum Intel](https://huggingface.co/docs/optimum/intel/index) library through [Intel Neural Compressor](https://github.com/intel/neural-compressor)."

2023-05-14 14:04 UTC, guybd commented on generative-ai-models-on-intel-cpu.md
> +It only takes ~80 milliseconds to generate the first token. The mean generation time for the next tokens is an amazing ~40 milliseconds. This level of performance definitely makes it possible to run
replace the line:
"It only takes ~80 milliseconds to generate the first token. The mean generation time for the next tokens is an amazing ~40 milliseconds."
with:
"As you can see in the example with 8bit quantization the latency per word is very low which results in fast generation."

2023-05-16 10:13 UTC, guybd commented on generative-ai-models-on-intel-cpu.md
> +Our friends at Intel have quantized several LLMs with SmoothQuant-O3: OPT [2.7B](https://huggingface.co/facebook/opt-2.7b) and [6.7B](https://huggingface.co/facebook/opt-6.7b) [[5]](https://arxiv.org
add after BloomZ:
and MPT-7B-chat [https://www.mosaicml.com/blog/mpt-7b](url)

2023-05-16 10:50 UTC, merged