re-translation dreambooth.md
huggingface/blog pull request #1097
Opened 2023-05-11 02:50 UTC by youyuanrsq

The dreambooth.md has been retranslated and a bilingual version has been added

2023-05-18 10:22 UTC, xianbaoqian commented
@zhongdongy @chenglu FYI

2023-06-05 01:54 UTC, zhongdongy requested changes
Nice work and thanks! 🤗 But please make a few changes (mentioned in multiple comments) so we can merge your contributions.

2023-06-05 01:54 UTC, zhongdongy commented on zh/dreambooth.md
> +- user: youyuanrsq
Please only put your username unser `authors` if you are one of the original writer, otherwise please only add to `translators`.

2023-06-05 01:54 UTC, zhongdongy commented on zh/dreambooth.md
> +> [Dreambooth](https://dreambooth.github.io/) is a technique to teach new concepts to [Stable Diffusion](https://huggingface.co/blog/stable_diffusion) using a specialized form of fine-tuning. Some pe
Please don't include original English source in the translated file. You may add translator notes if necessary. Please kindly remove those contents.

2023-06-05 01:54 UTC, zhongdongy commented on zh/dreambooth.md
> +我们做了许多实验来分析不同参数配置下`DreamBooth`的效果。本文展示了我们的发现和一些小技巧来帮助你在用 `DreamBooth`微调`Stable Diffusion`的时候提升（生成图片的）效果。
Please make sure a single whitespace inserted between **inline code block** and **plain text** contents.

2023-06-05 01:54 UTC, zhongdongy commented on zh/dreambooth.md
> +## TL;DR: 推荐的设置（TL;DR: Recommended Settings）
Original contents should be stripped from titles as well.

2024-08-13 14:57 UTC, closed without merging