add blog post content guidelines
huggingface/blog pull request #1101
Opened 2023-05-11 12:34 UTC by giadilli

Feel free to edit 

cc @yjernite @meg-huggingface

2023-05-11 12:38 UTC, julien-c commented on _blog.yml
> +- local: content-guidelines
```suggestion
- local: content-guidelines-update
```

maybe, to differentiate more (in search engines etc) from the actual /content-guidelines page

2023-05-11 13:15 UTC, osanseviero commented on content-guidelines-update.md
> +# Announcing our new Community Guidelines and Policy
You'll also need this + other authors

```suggestion
---
title: "Announcing our new Content Guidelines and Policy"
authors:
- user: giadap
---


# Announcing our new Community Guidelines and Policy
```

2023-05-11 13:54 UTC, pcuenca reviewed
Awesome!

2023-05-11 13:54 UTC, pcuenca commented on content-guidelines-update.md
> +# Announcing our new Community Guidelines and Policy
Also missing:

- Thumbnail path in the section mentioned by Omar: 
`thumbnail: /blog/assets/path/to/thumbnail.png`
- This snippet (typically after the title) to make it render:

```suggestion
# Announcing our new Community Guidelines and Policy

<!-- {blog_metadata} -->
<!-- {authors} -->
```

2023-05-11 13:54 UTC, pcuenca commented on content-guidelines-update.md
> +As a community-driven platform that aims to advance Open, Collaborative, and Responsible Machine Learning, we are thrilled support and maintain a welcoming space for our entire community! In support
```suggestion
As a community-driven platform that aims to advance Open, Collaborative, and Responsible Machine Learning, we are thrilled to support and maintain a welcoming space for our entire community! In support of this goal, we've updated our [Content Guidelines and Policy](https://huggingface.co/content-guidelines).
```

2023-05-11 13:54 UTC, pcuenca commented on content-guidelines-update.md
> +As we prioritize respecting users and peoples' rights throughout the use of Machine Learning systems, we take a forward-looking view to accounting for developments in the technology affect those righ
```suggestion
As we prioritize respecting users and peoples' rights throughout the use of Machine Learning systems, we take a forward-looking view to accounting for developments in how technology affects those rights. While existing regulations do protect people's agency over their work, their image, and their privacy, we see that new ways of processing information enabled by Machine Learning are posing entirely new questions with respect to how these rights should be operationalized - which is the focus of ongoing regulatory work around the world.
```

2023-05-11 13:54 UTC, pcuenca commented on content-guidelines-update.md
> +As we prioritize respecting users and peoples' rights throughout the use of Machine Learning systems, we take a forward-looking view to accounting for developments in the technology affect those righ
(or maybe I misunderstood the intent)

2023-05-11 13:56 UTC, giadilli commented on content-guidelines-update.md
> +# Announcing our new Community Guidelines and Policy
Thanks! I don't have a thumbnail tbh. Is it mandatory? Don't know what to use, it's a policy announcement.

2023-05-11 13:58 UTC, giadilli commented on content-guidelines-update.md
> +As we prioritize respecting users and peoples' rights throughout the use of Machine Learning systems, we take a forward-looking view to accounting for developments in the technology affect those righ
Good catch!

2023-05-11 13:59 UTC, pcuenca commented on content-guidelines-update.md
> +# Announcing our new Community Guidelines and Policy
I had the same question, not sure.

2023-05-11 14:49 UTC, osanseviero commented on content-guidelines-update.md
> +# Announcing our new Community Guidelines and Policy
Yes, all our posts have thumbnails. @Reeray or @gary149 might be able to helpor maybe we can reuse one from previous posts

2023-05-12 19:57 UTC, meg-huggingface commented on content-guidelines-update.md
> +Our approach is a reflection of our ongoing efforts to adapt and progress, which is made possible by the invaluable input of our users who actively collaborate and share their feedback. We are commit
Hahaha, I feel you @pcuenca ! Definitely important to reflect on implications of ownership, and how this interacts with HF goals wrt enabling/empowering/inclusion/self-responsibility/autonomy/etc.  Good eye to notice, IMO! Critical ethicsy thinking.
And to Giada's point, yes, it's been discussed! 😅

2023-05-12 20:07 UTC, meg-huggingface requested changes
This provides comments on the blog post. 
Something that should be standardized is "peoples'" vs "people's". The former is about lots of *groups of people* (subpopulations, people from different continents etc), while the latter is about people generally. I THINK we mean the latter, not the former, at least in most of the uses.

2023-05-12 20:07 UTC, meg-huggingface commented on content-guidelines-update.md
> +As we prioritize respecting users and peoples' rights throughout the use of Machine Learning systems, we take a forward-looking view to accounting for developments in how technology affects those rig
"to accounting for developments in the technology affect those rights." --> "to account for developments in the technology affecting those rights."

2023-05-12 20:07 UTC, meg-huggingface commented on content-guidelines-update.md
> +As we prioritize respecting users and peoples' rights throughout the use of Machine Learning systems, we take a forward-looking view to accounting for developments in how technology affects those rig
"While existing regulations do protect people's agency over their work" --> Is this about non-AI regulation? I think I actually kinda disagree with this either way. So maybe could be like, "While some existing regulation seeks to protect...."

2023-05-12 20:07 UTC, meg-huggingface commented on content-guidelines-update.md
> +As we prioritize respecting users and peoples' rights throughout the use of Machine Learning systems, we take a forward-looking view to accounting for developments in how technology affects those rig
I'm also wondering whether talking about regulation is a bit out of scope? The last sentence here is quite long, and I think it is because it is also trying to make points about regulation. These points are important, but maybe not a priority in this context?

2023-05-12 20:07 UTC, meg-huggingface commented on content-guidelines-update.md
> +As we prioritize respecting users and peoples' rights throughout the use of Machine Learning systems, we take a forward-looking view to accounting for developments in how technology affects those rig
Based on all this + some further edit ideas, here are two proposals for a reword on the paragraph as a whole: (Feel free to ignore, just connecting dots from my previous comments.)

Including reference to regulation/law; keeping the multiple points in place:
"As we prioritize respecting people's rights throughout the development and use of Machine Learning systems, we take a forward-looking view to account for developments in the technology and law affecting those rights. New ways of processing information enabled by Machine Learning are posing entirely new questions, both in the field of AI and in regulatory circles, about people's agency and rights with respect to their work, their image, and their privacy. Central to these discussions are how people's rights should be operationalized -- and we offer one avenue for addressing this here."

Removing law, shortening/tightening:
"As we prioritize respecting people's rights throughout the development and use of Machine Learning systems, we take a forward-looking view to account for developments in the technology affecting those rights. New ways of processing information enabled by Machine Learning are posing entirely new questions about how to protect people's agency and rights concerning their work, their image, and their privacy. "

I can offer other rewordings that further tease out some of the points, or shorten them, if helpful. Just lmk. =)

2023-05-12 20:07 UTC, meg-huggingface commented on content-guidelines-update.md
> +This consideration for people's consent and experiences on the platform extends to Community Content and people's behaviors on the Hub. To maintain a safe and welcoming environment, we do not allow a
peoples' --> people's?
"directed at our users" --> should we also include us (staff)?

2023-05-12 20:07 UTC, meg-huggingface commented on content-guidelines-update.md
> +Let's join forces to build a friendly and supportive community that encourages open AI and ML collaboration! Together, we can make great strides in fostering a welcoming environment for everyone.
"great strides forward" ? (not sure)

2023-05-12 20:19 UTC, meg-huggingface commented on _blog.yml
> +    - guidelines
```suggestion
    - guidelines
    - ethics
```

2023-05-12 20:23 UTC, meg-huggingface commented on content-guidelines-update.md
> +Moderating Machine Learning artifacts defines a new challenge. Unlike static content, the risks associated with developing and deploying artificial intelligence systems and/or models require in-depth
How about "presents" a new challenge, or, "introduces new challenges"?

2023-05-15 08:27 UTC, giadilli commented on content-guidelines-update.md
> +Furthermore, as the field of AI and machine learning continues to expand, the variety of use cases and applications grows exponentially. This makes it essential for us to stay up-to-date with the lat
"Proliferate", yes! Can you suggest all the changes so I just commit them? :)

2023-05-15 08:33 UTC, giadilli commented on content-guidelines-update.md
> +As we prioritize respecting users and peoples' rights throughout the use of Machine Learning systems, we take a forward-looking view to accounting for developments in how technology affects those rig
We mention regulations to prevent people to say we don't take it into account or, on the other hand, we should just wait for it to regulate also content moderation efforts. 

I like your first proposal for rewording, thank you!! Feel free to edit directly and change it with the version you prefer :)

2023-05-15 08:34 UTC, giadilli commented on content-guidelines-update.md
> +Let's join forces to build a friendly and supportive community that encourages open AI and ML collaboration! Together, we can make great strides in fostering a welcoming environment for everyone.
As you prefer, no strong opinion on that

2023-05-15 13:20 UTC, yjernite commented on content-guidelines-update.md
> +Furthermore, as the field of AI and machine learning continues to expand, the variety of use cases and applications grows exponentially. This makes it essential for us to stay up-to-date with the lat
updated to introduces

2023-05-15 14:40 UTC, giadilli commented
Added a thumbnail and addressed all comments! Thank you all :)

2023-06-13 19:27 UTC, meg-huggingface approved these changes

2023-06-14 19:28 UTC, merged