Add DeepFloyd If deployment blog post
huggingface/blog pull request #1320
Opened 2023-07-19 04:53 UTC by Sherlock113

Add a blog post to explain how to use BentoML to deploy Hugging Face models with DeepFloyd IF as an example. See https://github.com/huggingface/blog/issues/1280 for details.

2023-07-19 04:55 UTC, Sherlock113 commented
@sayakpaul @osanseviero PTAL. Thanks!

2023-07-31 04:07 UTC, sayakpaul commented on deploy-deepfloydif-using-bentoml.md
> +- user: larme
```suggestion
- user: Sherlockk
  guest: true
- user: larme
  guest: true
```

2023-07-31 04:08 UTC, sayakpaul commented on deploy-deepfloydif-using-bentoml.md
> +Hugging Face provides a centralized Model Hub that allows you to upload, share, and deploy your models with ease. It saves developers the time and computational resources required to train models fro
Let's maybe call it the Hub platform as it's not specific to models only. Hub platform allows for easy sharing of datasets and ML application demos too.

2023-07-31 04:11 UTC, sayakpaul commented on deploy-deepfloydif-using-bentoml.md
> +2. **Save the model**: Once you have a trained model, save it to the BentoML local Model Store, which is used for managing all your trained models locally as well as accessing them for serving.
So, the resultant image will _always_ have the model / artifact files?

2023-07-31 04:13 UTC, sayakpaul commented on deploy-deepfloydif-using-bentoml.md
> +DeepFloyd delivers a high degree of photorealism and sophisticated language understanding. Unlike Stable Diffusion, DeepFloyd IF works directly in pixel space, leveraging a modular structure that enc
I'd add a header to this section, maybe something like "Brief intro to IF".

2023-07-31 04:13 UTC, sayakpaul commented on deploy-deepfloydif-using-bentoml.md
> +
I'd also add a ToC here.

2023-07-31 04:15 UTC, sayakpaul commented on deploy-deepfloydif-using-bentoml.md
> +## Creating a DeepFloyd IF application with BentoML
Maybe discuss why deploying IF is particularly challenging?

2023-07-31 04:17 UTC, sayakpaul commented on deploy-deepfloydif-using-bentoml.md
> +- At least 2x16GB VRAM GPU or 1x40 VRAM GPU. For this project, we used a machine of type `n1-standard-16` from Google Cloud plus 64 GB of RAM and 2 NVIDIA T4 GPUs.
But it's also possible to run IF on a single T4: https://huggingface.co/blog/if. 

I'd maybe make a note about this and then warn the readers that even though the support is there, it's not really recommended for production-grade serving. 

WDYT?

2023-07-31 04:19 UTC, sayakpaul commented on deploy-deepfloydif-using-bentoml.md
> +- `import_models.py`: Defines the models for each Stage. You use this file to download all the models to your local machine so that you can package them into a single Bento.
```suggestion
- `import_models.py`: Defines the models for each stage of the [`IFPipeline`](https://huggingface.co/docs/diffusers/api/pipelines/if). You use this file to download all the models to your local machine so that you can package them into a single Bento.
```

2023-07-31 04:20 UTC, sayakpaul reviewed
I think we're already on a great start! Left a couple of minor comments.

2023-07-31 07:18 UTC, Sherlock113 commented on deploy-deepfloydif-using-bentoml.md
> +- At least 2x16GB VRAM GPU or 1x40 VRAM GPU. For this project, we used a machine of type `n1-standard-16` from Google Cloud plus 64 GB of RAM and 2 NVIDIA T4 GPUs.
I am ok to this. Perhaps add a sentence like this: `Note that while it is possible to run IF on a single T4, it is not recommended for production-grade serving`. @larme Let me know if you have any comments on it.

2023-07-31 08:41 UTC, Sherlock113 commented on deploy-deepfloydif-using-bentoml.md
> +2. **Save the model**: Once you have a trained model, save it to the BentoML local Model Store, which is used for managing all your trained models locally as well as accessing them for serving.
Yes, correct.

2023-07-31 09:11 UTC, Sherlock113 commented on deploy-deepfloydif-using-bentoml.md
> +## Creating a DeepFloyd IF application with BentoML
It is actually not just about deploying IF. BentoML works for all ML models. We use IF here just as an example to demo how BentoML works. Using the BentoML framework provides developers a unified way to deploy their AI apps in production. BentoML helps developers and in-house data science teams bridge the gap between model creation and production deployment. Perhaps I can add some explanations for it at the beginning to clarify this.

2023-07-31 09:18 UTC, sayakpaul commented on deploy-deepfloydif-using-bentoml.md
> +## Creating a DeepFloyd IF application with BentoML
I think that is clear. But we could have shown this with a `StableDiffusionPipeline` too. But I don't think it's particularly challenging to deploy. The `IFPipeline` is because of its computational requirements. Perhaps, it's worth clarifying that part and how we leverage the superpowers of BentoML to help ease that process.

Does it make more sense now?

2023-07-31 10:05 UTC, philschmid requested changes
Thank you for this amazing blog post! I left two suggestions. Since this is meant to be a guest post for the open-source integration of `diffusers` with `bentoML`, it would be good if we avoid advertising your paid solutions. Would you mind removing or reworking that section.

Let me know if you have any other questions!

2023-07-31 10:05 UTC, philschmid commented on deploy-deepfloydif-using-bentoml.md
> +If you seek a fully managed service for building and operating AI applications, consider deploying Bentos through BentoCloud. All [Hugging Face Diffuser models](https://huggingface.co/docs/diffusers/
```suggestion
```

2023-07-31 10:05 UTC, philschmid commented on deploy-deepfloydif-using-bentoml.md
> +You can then deploy the model on Kubernetes. Alternatively, push the Bento to Yatai or BentoCloud. For more information, see [Deploying Bentos](https://docs.bentoml.org/en/latest/concepts/deploy.html
```suggestion
You can then deploy the model on Kubernetes.
```

2023-07-31 12:37 UTC, Sherlock113 commented on deploy-deepfloydif-using-bentoml.md
> +## Creating a DeepFloyd IF application with BentoML
Thanks. I added some explanations about BentoML's ability to allow users manage resources for IF deployment.

2023-08-04 04:20 UTC, sayakpaul commented
@osanseviero @pcuenca could you review it once? I think it's good to go.

2023-08-04 04:20 UTC, sayakpaul commented on _blog.yml
> +  date: July 19, 2023
To be changed.

2023-08-04 04:20 UTC, sayakpaul commented on _blog.yml
> +    - guide
Maybe also add `diffusers`?

2023-08-07 10:53 UTC, Sherlock113 commented on _blog.yml
> +  date: July 19, 2023
I will update it once the release date is confirmed.

2023-08-08 21:29 UTC, osanseviero approved these changes
Cool blog post!

2023-08-08 21:29 UTC, osanseviero commented on _blog.yml
> +  date: July 19, 2023
Please also add `guest: true`

2023-08-08 21:29 UTC, osanseviero commented on deploy-deepfloydif-using-bentoml.md
> +This is where BentoML comes into the picture. BentoML is an open-source platform for machine learning model serving and deployment. It is a unified framework for building, shipping, and scaling produ
```suggestion
This is where BentoML comes into the picture. BentoML is an open-source platform for machine learning model serving and deployment. It is a unified framework for building, shipping, and scaling production-ready AI applications incorporating traditional, pre-trained, and generative models as well as Large Language Models. Here is how you use the BentoML framework from a high-level perspective:
```

2023-08-08 21:29 UTC, osanseviero commented on deploy-deepfloydif-using-bentoml.md
> +```
nit for nice formatting, also for other blocks

```suggestion
```bash
```

2023-08-09 02:00 UTC, sayakpaul commented
Hey @Sherlock113!

The additional image present in `assets` needs to go to https://huggingface.co/datasets/huggingface/documentation-images. We only keep the thumbnail images in that folder these days. So I hosted that here: https://huggingface.co/datasets/huggingface/documentation-images/tree/main/blog/deploy-deepfloydif-using-bentoml. Could you please delete that image from `assets` and update the link wherever necessary?

2023-08-09 02:54 UTC, Sherlock113 commented
> Hey @Sherlock113!
> 
> The additional image present in `assets` needs to go to https://huggingface.co/datasets/huggingface/documentation-images. We only keep the thumbnail images in that folder these days. So I hosted that here: https://huggingface.co/datasets/huggingface/documentation-images/tree/main/blog/deploy-deepfloydif-using-bentoml. Could you please delete that image from `assets` and update the link wherever necessary?

Thanks. I just fixed it.

2023-08-09 03:42 UTC, sayakpaul approved these changes

2023-08-09 03:43 UTC, sayakpaul commented
@philschmid could you approve so that we can merge?

2023-08-09 06:40 UTC, philschmid approved these changes
Thank you for improving it! :)

2023-08-09 06:47 UTC, merged