HF ONNX Runtime Support
huggingface/blog pull request #1559
Opened 2023-10-03 14:49 UTC by mfuntowicz

2023-10-03 17:51 UTC, sophies927 requested changes
I added a couple of small changes, but otherwise, this looks good to go!

2023-10-03 17:51 UTC, sophies927 commented on ort-accelerating-hf-models.md
> +To learn more about accelerating Hugging Face models with ONNX Runtime, check out our recent post on the [Microsoft Open Source Blog](insert link here).
For now, you can just link to the front page of the Microsoft Open Source Blog: https://cloudblogs.microsoft.com/opensource/.

2023-10-03 17:51 UTC, sophies927 commented on ort-accelerating-hf-models.md
Can you update the title to 'Accelerating over 130,000 Hugging Face models with ONNX Runtime'? (Even more supported models have been added since I wrote the original piece.)

2023-10-03 17:51 UTC, sophies927 commented on ort-accelerating-hf-models.md
> +|       BERT        |           28100            |
Update Approx. No. of Models for BERT to 28180.

2023-10-03 17:51 UTC, sophies927 commented on ort-accelerating-hf-models.md
> +|       GPT2        |           13900            |
Update Approx. No. of Models for GPT2 to 14060.

2023-10-03 17:51 UTC, sophies927 commented on ort-accelerating-hf-models.md
> +|    DistilBERT     |           11400            |
Update Approx. No. of Models for DistilBERT to 11540.

2023-10-03 17:51 UTC, sophies927 commented on ort-accelerating-hf-models.md
> +|      RoBERTa      |           10600            |
Update Approx. No. of Models for RoBERTa to 10800.

2023-10-03 17:51 UTC, sophies927 commented on ort-accelerating-hf-models.md
> +|        T5         |           10300            |
Update Approx. No. of Models for T5 to 10450.

2023-10-03 17:51 UTC, sophies927 commented on ort-accelerating-hf-models.md
> +|     Wav2Vec2      |            6500            |
Update Approx. No. of Models for Wav2Vec2 to 6560.

2023-10-03 17:51 UTC, sophies927 commented on ort-accelerating-hf-models.md
> +| Stable-Diffusion  |            5700            |
Update Approx. No. of Models for Stable-Diffusion to 5880.

2023-10-03 17:51 UTC, sophies927 commented on ort-accelerating-hf-models.md
> +|    XLM-RoBERTa    |            5000            |
Update Approx. No. of Models for XLM-RoBERTa to 5100.

2023-10-03 17:51 UTC, sophies927 commented on ort-accelerating-hf-models.md
> +|      Whisper      |            4300            |
Update Approx. No. of Models for Whisper to 4400.

2023-10-03 17:51 UTC, sophies927 commented on ort-accelerating-hf-models.md
> +|       BART        |            3500            |
Update Approx. No. of Models for BART to 3590.

2023-10-03 17:51 UTC, sophies927 commented on ort-accelerating-hf-models.md
> +|      Marian       |            2800            |
Update Approx. No. of Models for Marian to 2840.

2023-10-03 17:51 UTC, sophies927 commented on ort-accelerating-hf-models.md
> +| Mode Architecture | Approximated No. of Models |
Can we change from 'Mode Architecture' to 'Model Architecture'?

2023-10-03 17:55 UTC, julien-c commented on ort-accelerating-hf-models.md
> +- user: Sophie Schoenmeyer
this should be a HF Hub username @sophies927 so i guess:
```suggestion
- user: sschoenmeyer
```

2023-10-03 17:55 UTC, julien-c commented on ort-accelerating-hf-models.md
> +- user: Morgan Funtowicz
```suggestion
- user: mfuntowicz
```

2023-10-03 17:56 UTC, julien-c reviewed
this short teaser looks good!

2023-10-04 07:11 UTC, mfuntowicz commented on ort-accelerating-hf-models.md
> +- user: Sophie Schoenmeyer
Good catch thanks!

2023-10-04 07:30 UTC, sophies927 approved these changes

2023-10-04 07:32 UTC, sophies927 approved these changes
Looks great - thanks for putting this together!

2023-10-04 08:54 UTC, fxmarty approved these changes
LGTM!

2023-10-04 09:47 UTC, julien-c approved these changes

2023-10-04 10:07 UTC, pcuenca approved these changes

2023-10-04 10:07 UTC, pcuenca commented on ort-accelerating-hf-models.md
> +| Model Architecture | Approximated No. of Models |
```suggestion
| Model Architecture | Approximate No. of Models |
```

(minor nit)

2023-10-04 10:07 UTC, pcuenca commented on ort-accelerating-hf-models.md
> +To learn more about accelerating Hugging Face models with ONNX Runtime, check out our recent post on the [Microsoft Open Source Blog](https://cloudblogs.microsoft.com/opensource/2023/10/04/accelerati
404 for me, I suppose it's not published yet?

2023-10-04 11:48 UTC, mfuntowicz commented on ort-accelerating-hf-models.md
> +To learn more about accelerating Hugging Face models with ONNX Runtime, check out our recent post on the [Microsoft Open Source Blog](https://cloudblogs.microsoft.com/opensource/2023/10/04/accelerati
Yes, live later today 🙂

2023-10-04 15:06 UTC, merged