Prodigy-HF blogpost
huggingface/blog pull request #1622
Opened 2023-10-30 15:36 UTC by koaning

@davanstrien as requested, a blogpost. 

One of the features mentioned in the blogpost is in review right now so this isn't good to share just yet, but should be ready to go out tomorrow. Figured I'd make the PR to ensure the ball is rolling.

2023-10-31 13:37 UTC, merveenoyan approved these changes
Thanks a lot for this blog!

2023-10-31 13:37 UTC, merveenoyan commented on prodigy-hf.md
> +[Prodigy](https://prodi.gy/) is an annotation tool made by [Explosion](https://explosion.ai/), who are well known as the creators of [spaCy](https://spacy.io/). It's a fully scriptable product with a
```suggestion
[Prodigy](https://prodi.gy/) is an annotation tool made by [Explosion](https://explosion.ai/), a company well known as the creators of [spaCy](https://spacy.io/). It's a fully scriptable product with a large community around it. The product has many features, including tight integration with spaCy and active learning capabilities. But the main feature of the product is that it is programmatically customizable with Python. 
```

2023-10-31 13:37 UTC, merveenoyan commented on prodigy-hf.md
> +To encourage this customisability, Explosion has started releasing [plugins](https://prodi.gy/docs/plugins). These plugins integrate with third party tools in an open way that encourages users to wor
```suggestion
To encourage this customisability, Explosion has started releasing [plugins](https://prodi.gy/docs/plugins). These plugins integrate with third-party tools in an open way that encourages users to work on bespoke annotation workflows. However, one customization specifically deserves to be celebrated explicitly. Last week, Explosion introduced [Prodigy-HF](https://github.com/explosion/prodigy-hf), which offers code recipes that directly integrate with the Hugging Face stack. It's been a much-requested feature on the [Prodigy support forum](https://support.prodi.gy/), so we're super excited to have it out there. 
```

2023-10-31 13:37 UTC, merveenoyan commented on prodigy-hf.md
> +The first main feature is that this plugin allows you to train Hugging Face models on your annotated data. That means that if you've been annotating data in our interface for named entity recognition
```suggestion
The first main feature is that this plugin allows you to train Hugging Face models on your annotated data. That means if you've been annotating data in our interface for named entity recognition, you can directly fine-tune BERT models against it. 
```

2023-10-31 13:37 UTC, merveenoyan commented on prodigy-hf.md
> +This will finetune the `distillbert-base-uncased` model for the dataset that you've stored in Prodigy and save it to disk. Similarily, this plugin also supports models for text classification via a v
```suggestion
This will fine-tune the `distilbert-base-uncased` model for the dataset you've stored in Prodigy and save it to disk. Similarly, this plugin also supports models for text classification via a very similar interface. 
```

2023-10-31 13:37 UTC, merveenoyan commented on prodigy-hf.md
> +This offers a lot of flexibility because the tool directly integrations with the `AutoTokenizer` and `AutoModel*` tools from Hugging Face. Any transformer model on the hub can be finedtuned on your o
```suggestion
This offers a lot of flexibility because the tool directly integrates with the `AutoTokenizer` and `AutoModel` classes of Hugging Face transformers. Any transformer model on the hub can be fine-tuned on your own dataset with just a single command. 
```
is there any limits, e.g. maybe some tasks can't be fine-tuned?

2023-10-31 13:37 UTC, merveenoyan commented on prodigy-hf.md
> +The second feature, which is equally exciting, is that you can now also publish your annotated datasets unto the Hugging Face Hub. This is great if you're interested in contributing datasets that oth
```suggestion
The second feature, which is equally exciting, is that you can now also publish your annotated datasets on the Hugging Face Hub. This is great if you're interested in sharing datasets that others would like to use. 
```
very cool feature! just rewritten last sentence for clarity

2023-10-31 13:37 UTC, merveenoyan commented on prodigy-hf.md
> +We're particularily fond of this upload feature, because it encourages collaboration. People can annotate their own datasets independantly of eachother, but still benefit when they share the data to
```suggestion
We're particularly fond of this upload feature because it encourages collaboration. People can annotate their own datasets independently of each other, but still benefit when they share the data with the wider community. 
```

2023-10-31 13:37 UTC, merveenoyan commented on prodigy-hf.md
> +- user: koaning
```suggestion
- user: koaning
  guest: true
```

2023-10-31 15:35 UTC, davanstrien reviewed
This looks great; I made a few minor suggestions, but nothing major. I will also move the images (other than the thumbnail to https://huggingface.co/datasets/huggingface/documentation-images/tree/main, which we use to store assets and keep this repo lighter.

2023-10-31 15:35 UTC, davanstrien commented on _blog.yml
> +- local: researcher-dataset-sharing
```suggestion
- local: prodigy-hf
```

2023-10-31 15:35 UTC, davanstrien commented on prodigy-hf.md
> +
Maybe add a short sentence saying these trained models can also be directly pushed to the Hub?

2023-10-31 15:35 UTC, davanstrien commented on prodigy-hf.md
> +We hope that this direct integration with the Hugging Face stack enables many users to experiment more. The Hugging Face Hub offers _many_ [models](https://huggingface.co/models) for a wide array of
```suggestion
We hope that this direct integration with the Hugging Face ecosystem enables many users to experiment more. The Hugging Face Hub offers _many_ [models](https://huggingface.co/models) for a wide array of tasks as well as a wide array of languages. We really hope that this integration makes it easier to get data annotated, even if you've got a more domain specific and experimental use-case. 
```

2023-10-31 15:35 UTC, davanstrien commented on prodigy-hf.md
> +We hope that this direct integration with the Hugging Face stack enables many users to experiment more. The Hugging Face Hub offers _many_ [models](https://huggingface.co/models) for a wide array of
the `ecosystem` word is a personal preference on my part so feel free to ignore it!

2023-10-31 15:35 UTC, davanstrien commented on prodigy-hf.md
> +We'd also like to thank the team over at Hugging Face for their feedback on this plugin, specifically @davanstrien, who suggested to add the upload feature. Thanks!
Thanks for releasing it so quickly!!

2023-11-07 13:08 UTC, magdaaniol commented on prodigy-hf.md
> +To encourage this customisability, Explosion has started releasing [plugins](https://prodi.gy/docs/plugins). These plugins integrate with third-party tools in an open way that encourages users to wor
```suggestion
To foster this customisability, Explosion has started releasing [plugins](https://prodi.gy/docs/plugins). These plugins integrate with third-party tools in an open way that encourages users to work on bespoke annotation workflows. However, one customization specifically deserves to be celebrated explicitly. Last week, Explosion introduced [Prodigy-HF](https://github.com/explosion/prodigy-hf), which offers code recipes that directly integrate with the Hugging Face stack. It's been a much-requested feature on the [Prodigy support forum](https://support.prodi.gy/), so we're super excited to have it out there. 
```

2023-11-07 14:42 UTC, davanstrien commented on prodigy-hf.md
> +  guest: true
```suggestion
```

2023-11-07 14:42 UTC, davanstrien commented on prodigy-hf.md
> +  guest: true
I think this got duplicated for some reason

2023-11-07 15:09 UTC, davanstrien requested changes
Just updating image link here

2023-11-07 15:09 UTC, davanstrien commented on prodigy-hf.md
> +        <img src="assets/171_prodigy_hf/interface.png" width="100%">
```suggestion
        <img src="https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/blog/prodigy-hf/interface.png" width="100%">
```

2023-11-07 15:58 UTC, merged