Add SetFit ABSA
huggingface/blog pull request #1654
Opened 2023-11-22 10:59 UTC by lewtun

2023-11-22 11:01 UTC, lewtun commented on assets/setfit-absa/intel_hf_logo.png
FYI this image needs updating

2023-11-22 12:06 UTC, osanseviero commented on setfit-absa.md
> +authors:
Remember to mark guests as guests :)

2023-11-22 12:20 UTC, lewtun commented on setfit-absa.md
> +authors:
thanks!

2023-11-22 13:26 UTC, tomaarsen commented on _blog.yml
> +  date: Novemeber XXX, 2023
```suggestion
  date: November XXX, 2023
```

2023-11-22 16:19 UTC, lewtun commented
I think the content is now ready for a "sanity check" review from @pcuenca or @osanseviero (no need to proof read if you don't want to :))

2023-11-22 17:39 UTC, rlaperdo requested changes
Based on Tom's refactoring, change the three lists old output by the new output format

2023-11-22 17:39 UTC, rlaperdo commented on setfit-absa.md
> +[‘O’, ‘positive’, ‘positive’, ‘O’, ‘O’, ‘O’]
```
[[{‘span’: ‘dinner specials’, ‘polarity’: ’positive’}]]
```

2023-11-27 14:46 UTC, lewtun commented on setfit-absa.md
> +[‘O’, ‘positive’, ‘positive’, ‘O’, ‘O’, ‘O’]
Good catch! Fixed in https://github.com/huggingface/blog/pull/1654/commits/28563fcaffbcd0d7b1ca2a3b2cd1f462189d7dea

2023-11-27 15:02 UTC, rlaperdo commented
Hi,

As “dinner specials” is one aspect term,  I think that based on Tom’s new output format it should be:

[
    [
        {"span": "dinner specials", "polarity": "positive"},
    ]
]

And not:

[
    [
        {"span": "dinner", "polarity": "positive"},
        {"span": "specials", "polarity": "positive"},
    ]
]

I’m not promising the algorithm will catch the phrase as an aspect 😊 but as least this is the expected output.

Ronen.
From: lewtun ***@***.***>
Sent: Monday, November 27, 2023 16:47
To: huggingface/blog ***@***.***>
Cc: Laperdon, Ronen ***@***.***>; Comment ***@***.***>
Subject: Re: [huggingface/blog] Add SetFit ABSA (PR #1654)


@lewtun commented on this pull request.

________________________________

In setfit-absa.md<https://github.com/huggingface/blog/pull/1654#discussion_r1406272356>:

> +['their', 'dinner', 'specials', 'are', 'fantastic', '.'],

+[‘O’, B-ASP, I-ASP, ‘O’, ‘O’, ‘O’],

+[‘O’, ‘positive’, ‘positive’, ‘O’, ‘O’, ‘O’]

Good catch! Fixed in 28563fc<https://github.com/huggingface/blog/commit/28563fcaffbcd0d7b1ca2a3b2cd1f462189d7dea>

—
Reply to this email directly, view it on GitHub<https://github.com/huggingface/blog/pull/1654#discussion_r1406272356>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYIU643SRNK2QQMGF7UMTETYGSRUXAVCNFSM6AAAAAA7WA7QUWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONJQGYYTENRRHE>.
You are receiving this because you commented.Message ID: ***@***.******@***.***>>
---------------------------------------------------------------------
Intel Israel (74) Limited

This e-mail and any attachments may contain confidential material for
the sole use of the intended recipient(s). Any review or distribution
by others is strictly prohibited. If you are not the intended
recipient, please contact the sender and delete all copies.

2023-11-27 17:50 UTC, orenpereg commented on setfit-absa.md
> +<p><strong>Extracted aspect candidates:</strong> [Waiters, are, n't, friendly, but, the, cream, pasta, is, out, of, this, world, .]</p>
Are the tokens"waiters", "cream", "pasta" and "world" marked in bold or color as in the google doc?

2023-11-28 08:28 UTC, orenpereg commented
I've proof read the blog. everything looks great!
Just making sure that the words 'waiters', 'cream', 'pasta' and 'world' in the examples in lines 66 and 68 are colored according to the google doc.

2023-11-28 11:46 UTC, pcuenca approved these changes
Awesome work, very engaging!

2023-11-28 11:46 UTC, pcuenca commented on _blog.yml
> +  date: November XXX, 2023
```suggestion
  date: November 28, 2023
```

Just a reminder to update :)

2023-11-28 11:46 UTC, pcuenca commented on setfit-absa.md
> +    <img src="assets/setfit-absa/method.png" width=500>
```suggestion
    <img src="https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/blog/setfit-absa/method.png" width=500>
```

2023-11-28 11:46 UTC, pcuenca commented on setfit-absa.md
> +    <img src="assets/setfit-absa/method.png" width=500>
The image is displayed again later in the post, is that intended?

2023-11-28 11:46 UTC, pcuenca commented on setfit-absa.md
> +<p><strong>Generated aspect/non-aspect Labels:</strong> [Waiters, are, n't, friendly, but, the, cream, pasta, is, out, of, this, world, .]</p>
I'm not following here. Why are the "aspect candidates" and the "aspect/non-aspect labels" equal to the original tokenized text? Also, is the use of BIO format important at this stage? I think it'd be easier to understand if the final result showed true/false labels as described in the intro paragraph.

2023-11-28 11:46 UTC, pcuenca commented on setfit-absa.md
> +Once the system extracts the aspects from the text, it needs to associate a sentiment polarity (e.g., positive, negative or neutral) to each aspect. For this purpose, we use a 2nd SetFit model and tr
```suggestion
Once the system extracts the aspects from the text, it needs to associate a sentiment polarity (e.g., positive, negative or neutral) to each aspect. For this purpose, we use a 2nd SetFit model and train it in a similar fashion to the aspect extraction model as illustrated in the following example:
```

2023-11-28 11:46 UTC, pcuenca commented on setfit-absa.md
> +After generating the training instances, we are ready to use the power of SetFit to train a few-shot domain-specific binary classifier to extract aspects from an input text review.
```suggestion
After generating the training instances, we are ready to use the power of SetFit to train a few-shot domain-specific binary classifier to extract aspects from an input text review. This will be our first fine-tuned SetFit model.
```

Maybe a bit redundant, but I had to retrace when I read "2nd SetFit model" in the sentiment classification phase.

Another way to reinforce would be to use "SetFit Model 1" and "SetFit Model 2" in the method figure.

2023-11-28 11:46 UTC, pcuenca commented on setfit-absa.md
> +At inference time, the test sentence passes through the aspect candidate extraction, resulting in test instances using the template `aspect_candidate:test_sentence`. Next, non-aspects are filtered by
```suggestion
At inference time, the test sentence passes through the spaCy aspect candidate extraction phase, resulting in test instances using the template `aspect_candidate:test_sentence`. Next, non-aspects are filtered by the aspect/non-aspect classifier. Finally, the extracted aspects are fed to the sentiment polarity classifier that predicts the sentiment polarity per aspect.
```

Maybe?

2023-11-28 11:46 UTC, pcuenca commented on setfit-absa.md
> +        {"span": "specials", "polarity": "positive"},
I assume this comes from a post-processing phase. In the example of the training dataset we did not see the `span` or `polarity` fields. We also used different string representations for `positive` and `negative`.

Edit: we can refer to the training section that comes later. Still the labels are `pos` and `neg` there.

2023-11-28 11:46 UTC, pcuenca commented on setfit-absa.md
> +    <img src="https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/blog/SetFitABSA_vs_GPT2.png" width=700>
```suggestion
    <img src="https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/blog/setfit-absa/SetFitABSA_vs_GPT2.png" width=700>
```

2023-11-28 11:46 UTC, pcuenca commented on setfit-absa.md
> +    <img src="https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/blog/SetFitABSA_vs_T5.png" width=700>
```suggestion
    <img src="https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/blog/setfit-absa/SetFitABSA_vs_T5.png" width=700>
```

2023-11-28 11:46 UTC, pcuenca commented on setfit-absa.md
> +Note that the baseline works use different numbers of training sentences and different data splits. For fair comparison, we conducted separate comparisons with our model against each of them, ensurin
Is that what the plots show? I thought it was our method, seeing just a few training sentences in the X axis.

2023-11-28 11:46 UTC, pcuenca commented on setfit-absa.md
> +    <img src="https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/blog/SetFitABSA_vs_Llama2.png" width=700>
```suggestion
    <img src="https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/blog/setfit-absa/SetFitABSA_vs_Llama2.png" width=700>
```

2023-11-28 11:46 UTC, pcuenca commented on setfit-absa.md
> +We notice that increasing the number of in-context training samples for Llama2 did not result in improved performance. This phenomenon has been shown for ChatGPT in [this blog post](https://www.analy
```suggestion
We notice that increasing the number of in-context training samples for Llama2 did not result in improved performance. This phenomenon [has been shown for ChatGPT before](https://www.analyticsvidhya.com/blog/2023/09/power-of-llms-zero-shot-and-few-shot-prompting/), and we think it should be further investigated.
```

2023-11-28 11:46 UTC, pcuenca commented on setfit-absa.md
> +```
Brief guidance on hardware requirements would be great here. I'm assuming this is quite approachable.

2023-11-28 11:46 UTC, pcuenca commented on setfit-absa.md
> +)
Ohhh, nice

2023-11-28 11:46 UTC, pcuenca commented on setfit-absa.md
> +Then, we use the predict API to execute the inference. The input is a list of strings, each representing a textual review:
```suggestion
Then, we use the predict API to rub inference. The input is a list of strings, each representing a textual review:
```

2023-12-06 09:23 UTC, tomaarsen commented on _blog.yml
> +  date: November XXX, 2023
Done :) Updated it to today, as I intend to release this later today

2023-12-06 11:47 UTC, tomaarsen commented on setfit-absa.md
> +    <img src="assets/setfit-absa/method.png" width=500>
I believe so, yes. The first one is meant as a bit of a header image, and the second one to help with explaining how the model works.

2023-12-06 11:48 UTC, tomaarsen commented on setfit-absa.md
> +<p><strong>Generated aspect/non-aspect Labels:</strong> [Waiters, are, n't, friendly, but, the, cream, pasta, is, out, of, this, world, .]</p>
I've updated this according to our internal docs, i.e. I've added the colors that @orenpereg already mentioned.

2023-12-06 11:50 UTC, tomaarsen commented on setfit-absa.md
> +After generating the training instances, we are ready to use the power of SetFit to train a few-shot domain-specific binary classifier to extract aspects from an input text review.
I like your proposal here, I'll add it.

2023-12-06 12:06 UTC, tomaarsen commented on setfit-absa.md
> +```
I've added a section on training time and hardware, i.e. that the SetFitABSA model trains in about 10 minutes on the free T4 from Google Colab.

2023-12-06 12:12 UTC, tomaarsen commented
@rlaperdo @orenpereg 
The blogpost is ready as far as I can tell. I will write the SetFit v1.0.0 changelog, release v1.0.0, and then publish this blogpost.

2023-12-06 12:58 UTC, pcuenca approved these changes
🔥

2023-12-06 12:58 UTC, pcuenca commented on setfit-absa.md
> +Now that we have aspect candidates, we need to train a model to be able to distinguish between nouns that are aspects and nouns that are non-aspects. For this purpose, we need training samples with a
```suggestion
Now that we have aspect candidates, we need to train a model to be able to distinguish between nouns that are aspects and nouns that are non-aspects. For this purpose, we need training samples with aspect/no-aspect labels. This is done by considering aspects in the training set as `True` aspects, while other non-overlapping candidate aspects are considered non-aspects and therefore labeled as `False`:
```

There was a extraneous `rest` in the last sentence.

2023-12-06 12:58 UTC, pcuenca commented on setfit-absa.md
> +Applying the example above to the template, will generate 3 training instances – two with `True` labels representing aspect training instances and one with `False` label representing non-aspect train
```suggestion
Applying the template to the example above will generate 3 training instances – two with `True` labels representing aspect training instances, and one with `False` label representing non-aspect training instance:
```

2023-12-06 12:58 UTC, pcuenca commented on setfit-absa.md
> +| **SetFit (MPNet)** |     110M      |
does this include the two SetFit models?

2023-12-06 12:58 UTC, pcuenca commented on setfit-absa.md
> +* **label**: The (polarity) label corresponding to the aspect span. For example: "positive". The labels names can be chosen arbitrarily when tagging the collected training data.
```suggestion
* **label**: The (polarity) label corresponding to the aspect span. For example: "positive". The label names can be chosen arbitrarily when tagging the collected training data.
```

2023-12-06 12:58 UTC, pcuenca commented on setfit-absa.md
> +* **ordinal**: If the aspect span occurs multiple times in the text, then this ordinal represents the index of those occurrences. Often this is just 0, as usually aspect appears only once in the inpu
```suggestion
* **ordinal**: If the aspect span occurs multiple times in the text, then this ordinal represents the index of those occurrences. Often this is just 0, as each aspect usually appears only once in the input text.
```

2023-12-06 14:01 UTC, tomaarsen commented on setfit-absa.md
> +| **SetFit (MPNet)** |     110M      |
It does not! Well spotted, this is just the one. I'll replace it with 220M (or perhaps `2x 110M`?)

2023-12-06 14:07 UTC, pcuenca commented on setfit-absa.md
> +| **SetFit (MPNet)** |     110M      |
I think `2 x 110M` might be clearer? Then we'd have to change the comments below about being half the size of `T5` :(

2023-12-06 14:31 UTC, tomaarsen commented on setfit-absa.md
> +| **SetFit (MPNet)** |     110M      |
@rlaperdo clarified in a comment on the commit:
> It is true that for the entire ABSA model the size is 220M and this is valid for evaluating a complete flow, i.e. SB1+SB2. However many absa tasks evaluate only aspect extraction (SB1) or aspect polarity (SB2). For these tasks the model size is still 110M, as training aspect_model is independent from the training of the polarity_model.

2023-12-06 14:38 UTC, tomaarsen commented on setfit-absa.md
> +| **SetFit (MPNet)** |     110M      |
I've clarified the situation with "2x 110M" and an additional comment.

2023-12-06 15:03 UTC, tomaarsen commented on setfit-absa.md
> +        {"span": "specials", "polarity": "positive"},
Resolved in f4c1158ce325bc4460a037046e26d91b56f934c5, renames the labels to "positive" and "negative" for clarity. The "span" corresponds with the aspect and the "polarity" with the label. Perhaps I should have used "label" in the output of the SetFitABSA model as well, but this should be okay.

2023-12-06 15:20 UTC, tomaarsen commented on setfit-absa.md
> +Note that the baseline works use different numbers of training sentences and different data splits. For fair comparison, we conducted separate comparisons with our model against each of them, ensurin
I think it just means that SetFitABSA was compared against specifically the splits used by the other works, and the results of that are shown in the plots.

2023-12-06 15:42 UTC, merged