ONNX Runtime SD/SDXL Inference Blog
huggingface/blog pull request #1706
Opened 2023-12-14 21:37 UTC by mfuntowicz

2023-12-15 18:58 UTC, sophies927 reviewed
Suggested a few changes based on some last-minute requests from my team. Most notably, I switched all perf charts from latency to throughput, so I commented the new SVGs + made some changes to the text to reflect these updates.

I am currently waiting on a couple of other features that my team would like to add, each of which would require minor additions to the post as well. I will comment those changes as soon as I have them (hopefully by EOD today or Monday).

2023-12-15 18:58 UTC, sophies927 commented on assets/sdxl_ort_inference/sd_turbo_a100_perf_chart.svg
Was just told to switch this from latency to throughput - I've attached a new SVG.
![SD Turbo A100 Throughput Chart](https://github.com/huggingface/blog/assets/107952697/35a546ed-b542-4e84-90a2-b579f0b2c2d4)

2023-12-15 18:58 UTC, sophies927 commented on assets/sdxl_ort_inference/sd_turbo_rtx_perf_chart.svg
Was just told to switch this from latency to throughput - I've attached a new SVG.
![SD Turbo RTX Throughput Chart](https://github.com/huggingface/blog/assets/107952697/d95e741e-ed81-4b4d-9f3f-58859545833b)

2023-12-15 18:58 UTC, sophies927 commented on assets/sdxl_ort_inference/sdxl_turbo_controlnet_perf_chart.svg
Was just told to switch this from latency to throughput - I've attached a new SVG.
![SDXL Turbo ControlNet Throughput Chart](https://github.com/huggingface/blog/assets/107952697/b6db61a4-dc0b-497a-a69b-10e4be9b1fc3)

2023-12-15 18:58 UTC, sophies927 commented on assets/sdxl_ort_inference/sdxl_turbo_perf_chart.svg
Was just told to switch this from latency to throughput - I've attached a new SVG.
![SDXL Turbo Throughput Chart](https://github.com/huggingface/blog/assets/107952697/ecac9be3-6e7a-4ee4-bc11-5c23ef3e5bd6)

2023-12-15 18:58 UTC, sophies927 commented on sdxl_ort_inference.md
> +- user: sschoenmeyer
Can you also add Tianlei Wu (https://huggingface.co/tlwu) as an author? He's the engineer on my team who co-authored this post.

2023-12-15 18:58 UTC, sophies927 commented on sdxl_ort_inference.md
> +
Can you add the following new paragraph here:

> Not only does ONNX Runtime provide performance benefits when used with SD Turbo and SDXL Turbo, but it also makes the models accessible in languages other than Python, like C#. A tutorial for how to run SD Turbo and SDXL Turbo is coming soon. In the meantime, check out our previous tutorial on [inferencing Stable Diffusion with C# and ONNX Runtime](https://onnxruntime.ai/docs/tutorials/csharp/stable-diffusion-csharp.html).

2023-12-15 18:58 UTC, sophies927 commented on sdxl_ort_inference.md
> +To reproduce these results, we also recommend using the instructions included above in the ‘Diffusers demo’ section of ‘Usage examples.’
Can you replace this sentence with the following (slightly different) sentence?

> To reproduce these results, we also recommend using the instructions included above in the ‘Diffusers demo’ section.

2023-12-15 18:58 UTC, sophies927 commented on sdxl_ort_inference.md
> +The following charts illustrate the end-to-end (e2e) latency in milliseconds (ms) vs. different (batch size, number of steps) combinations for various frameworks. It is worth noting that lower latenc
Can you replace lines 74-75 w/ the following two paragraphs?

> The following charts illustrate the throughput in images per second vs. different (batch size, number of steps) combinations for various frameworks. It is worth noting that the label above each bar indicates the speedup vs. Torch Compile – e.g., in the first chart, ORT_TRT (static) is 2.8X faster than Torch Compile for (batch, steps) combination (1, 1).
> We elected to use 1 and 4 steps because both SD Turbo and SDXL Turbo can generate viable images in as little as 1 step but typically produce images of the best quality in 3-5 steps.

2023-12-15 18:58 UTC, sophies927 commented on sdxl_ort_inference.md
> +The graph below illustrates the end-to-end (e2e) latency in milliseconds (ms) for the SDXL Turbo model.
Can you replace this line w/ the following (was told last minute to switch from latency to throughput, so I updated all of the graphs)?

> The graph below illustrates the throughput in images per second for the SDXL Turbo model.

2023-12-15 18:58 UTC, sophies927 commented on sdxl_ort_inference.md
> +![Performance results for SDXL Turbo on NVIDIA A100 Tensor Cores GPU](assets/sdxl_ort_inference/sdxl_turbo_perf_chart.svg)
Can you replace this chart w/ the new SDXL Turbo Throughput Chart SVG I commented above (see assets folder)?

2023-12-15 18:58 UTC, sophies927 commented on sdxl_ort_inference.md
> +The next graph also illustrates end-to-end latency for the SDXL Turbo models, this time when ControlNet
Can you replace this line w/ the following (was told last minute to switch from latency to throughput, so I updated all of the graphs)?

> The next graph also illustrates throughput in images per second for the SDXL Turbo models, this time when ControlNet is used on the same GPU.

2023-12-15 18:58 UTC, sophies927 commented on sdxl_ort_inference.md
> +![Performance results for SDXL Turbo on NVIDIA A100 Tensor Cores GPU with ControlNet](assets/sdxl_ort_inference/sdxl_turbo_controlnet_perf_chart.svg)
Can you replace this chart w/ the new SDXL Turbo ControlNet Throughput Chart SVG I commented above (see assets folder)?

2023-12-15 18:58 UTC, sophies927 commented on sdxl_ort_inference.md
> +The final two graphs illustrate end-to-end latency for the SD Turbo model on two different types of GPUs: A100-SXM4-80GB and RTX-4090
Can you replace this line w/ the following (was told last minute to switch from latency to throughput, so I updated all of the graphs)?

> The final two graphs illustrate throughput in images per second for the SD Turbo model on two different types of GPUs: A100-SXM4-80GB and RTX-4090.

2023-12-15 18:58 UTC, sophies927 commented on sdxl_ort_inference.md
> +![Performance results for SD Turbo on NVIDIA A100 Tensor Cores GPU with ControlNet](assets/sdxl_ort_inference/sd_turbo_a100_perf_chart.svg)
Can you replace this chart w/ the new SD Turbo A100 Throughput Chart SVG I commented above (see assets folder)?

2023-12-15 18:58 UTC, sophies927 commented on sdxl_ort_inference.md
> +![Performance results for SD Turbo on RTX 4090](assets/sdxl_ort_inference/sd_turbo_rtx_perf_chart.svg)
Can you replace this chart w/ the new SD Turbo RTX Throughput Chart SVG I commented above (see assets folder)?

2023-12-15 18:58 UTC, sophies927 commented on sdxl_ort_inference.md
> +Notably, ONNX Runtime with TensorRT (static shape) is up to 3x faster than Torch Compile for (batch, steps) combination (1, 1), and end-to-end latency increases with an increase in batch size and wit
Can you replace this sentence w/ the following?

> Notably, ONNX Runtime with TensorRT (static shape) is up to 3x faster than Torch Compile for (batch, steps) combination (1, 1).

2024-01-11 08:37 UTC, sophies927 requested changes
Since the updated version of the blog is so different from the original, I went through section by section and provided the updated text / layout w/ markdown. Also worth noting that all of the charts have been replaced + a few have been added - let me know if there are any issues w/ layout or different image types are preferred.

So sorry for all the changes, but this version should be final + has been approved for publication by my team! Here's the PDF version for reference: 
[[NEW] SDXL Turbo Olive Blog Post.pdf](https://github.com/huggingface/blog/files/13900091/NEW.SDXL.Turbo.Olive.Blog.Post.pdf)

2024-01-11 08:37 UTC, sophies927 commented on assets/sdxl_ort_inference/mona_lisa_example_image.svg
Can you remove this image? - We decided against using it.

2024-01-11 08:37 UTC, sophies927 commented on assets/sdxl_ort_inference/sd_turbo_a100_perf_chart.svg
Can you replace this image with the two images I've attached? Let me know if they show up distorted or you think a different format would work better.
![SD Turbo Dynamic A100 Throughput](https://github.com/huggingface/blog/assets/107952697/65f71705-9248-4832-8add-fa0b7a1516a8)
![SD Turbo Static A100 Throughput](https://github.com/huggingface/blog/assets/107952697/03dccdf7-28e1-4399-abe9-c715eed45b26)

2024-01-11 08:37 UTC, sophies927 commented on assets/sdxl_ort_inference/sd_turbo_rtx_perf_chart.svg
Can you replace this image with the two images I've attached? Let me know if they show up distorted or you think a different format would work better.
![SD Turbo Dynamic RTX Throughput](https://github.com/huggingface/blog/assets/107952697/5f06f60b-5cd3-44f3-87e9-912bcb1ad809)
![SD Turbo Static RTX Throughput](https://github.com/huggingface/blog/assets/107952697/91286726-2b29-414b-8f6b-470236a9094d)

2024-01-11 08:37 UTC, sophies927 commented on assets/sdxl_ort_inference/sdxl_turbo_controlnet_perf_chart.svg
Can you remove this image? - We decided against including ControlNet info in this blog.

2024-01-11 08:37 UTC, sophies927 commented on assets/sdxl_ort_inference/sdxl_turbo_perf_chart.svg
Can you replace this image with the two images I've attached? Let me know if they show up distorted or you think a different format would work better.
![SDXL Turbo Dynamic Throughput](https://github.com/huggingface/blog/assets/107952697/122a9bf2-2981-4b17-8096-b32d551deabc)
![SDXL Turbo Static Throughput](https://github.com/huggingface/blog/assets/107952697/8bb48781-f521-434e-ac04-0b5a510f375e)

2024-01-11 08:37 UTC, sophies927 commented on sdxl_ort_inference.md
> +# Accelerating SD Turbo and SDXL Turbo Inference with ONNX Runtime
Change title to "Accelerating SD Turbo and SDXL Turbo Inference with ONNX Runtime and Olive".

2024-01-11 08:37 UTC, sophies927 commented on sdxl_ort_inference.md
> +## Introduction
Replace current 'Introduction' section with the following (includes 'Performance gains' subsection + perf comparison image):
## Introduction
[SD Turbo](https://huggingface.co/stabilityai/sd-turbo) and [SDXL Turbo](https://huggingface.co/stabilityai/sdxl-turbo) are two fast generative text-to-image models capable of generating viable images in as little as one step, a significant improvement over the 30+ steps often required with previous Stable Diffusion models. SD Turbo is a distilled version of [Stable Diffusion 2.1](https://huggingface.co/stabilityai/stable-diffusion-2-1), and SDXL Turbo is a distilled version of [SDXL 1.0](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0). We’ve [previously shown](https://medium.com/microsoftazure/accelerating-stable-diffusion-inference-with-onnx-runtime-203bd7728540) how to accelerate Stable Diffusion inference with ONNX Runtime. Not only does ONNX Runtime provide performance benefits when used with SD Turbo and SDXL Turbo, but it also makes the models accessible in languages other than Python, like C# and Java.

### Performance gains
In this post, we will introduce optimizations in the ONNX Runtime CUDA and TensorRT execution providers that speed up inference of SD Turbo and SDXL Turbo on NVIDIA GPUs significantly.
ONNX Runtime outperformed PyTorch for all (batch size, number of steps) combinations tested, with throughput gains as high as 229% for the SDXL Turbo model and 120% for the SD Turbo model. ONNX Runtime CUDA has particularly good performance for dynamic shape but demonstrates a marked improvement over PyTorch for static shape as well.
![SDXL Turbo Comparison Thumbnail](https://github.com/huggingface/blog/assets/107952697/942cae1b-ca45-46fd-b4f5-73e346c5b5a9)

2024-01-11 08:37 UTC, sophies927 commented on sdxl_ort_inference.md
> +## Diffusion demo
Replace current 'Diffusion demo' section w/ the following (not sure if the gremlin image is showing up correctly):
## How to run SD Turbo and SDXL Turbo
To accelerate inference with the ONNX Runtime CUDA execution provider, access our optimized versions of [SD Turbo](https://huggingface.co/tlwu/sd-turbo-onnxruntime) and [SDXL Turbo](https://huggingface.co/tlwu/sdxl-turbo-onnxruntime) on Hugging Face.
The models are generated by [Olive](https://github.com/microsoft/Olive/tree/main/examples/stable_diffusion), an easy-to-use model optimization tool that is hardware aware. Note that fp16 VAE must be enabled through the command line for best performance, as shown in the optimized versions shared. For instructions on how to run the SD and SDXL pipelines with the ONNX files hosted on Hugging Face, see the [SD Turbo usage example](https://huggingface.co/tlwu/sd-turbo-onnxruntime#usage-example) and the [SDXL Turbo usage example](https://huggingface.co/tlwu/sdxl-turbo-onnxruntime#usage-example).
To accelerate inference with the ONNX Runtime TensorRT execution provider instead, follow the instructions found [here](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/transformers/models/stable_diffusion/README.md#run-demo-with-docker).
The following is an example of image generation with the SDXL Turbo model guided by a text prompt:

```bash
python3 demo_txt2img_xl.py \
  --version xl-turbo \
  "little cute gremlin wearing a jacket, cinematic, vivid colors, intricate masterpiece, golden ratio, highly detailed"
```

<p align="center"> 
 <img src="assets/sdxl_ort_inference/gremlin_example_image.svg" alt="Generated Gremlin Example"><br> 
<em>Figure 1. Little cute gremlin wearing a jacket image generated with text prompt using SDXL Turbo.</em> 
</p> 

Note that the example image was generated in 4 steps, demonstrating the ability of SD Turbo and SDXL Turbo to generate viable images in fewer steps than previous Stable Diffusion models.
For a user-friendly way to try out Stable Diffusion models, see our [ONNX Runtime Extension for Automatic1111’s SD WebUI](https://github.com/tianleiwu/Stable-Diffusion-WebUI-OnnxRuntime). This extension enables optimized execution of the Stable Diffusion UNet model on NVIDIA GPUs and uses the ONNX Runtime CUDA execution provider to run inference against models optimized with Olive. At this time, the extension has only been optimized for Stable Diffusion 1.5. SD Turbo and SDXL Turbo models can be used as well, but performance optimizations are still in progress.

### Applications of Stable Diffusion in C# and Java
Taking advantage of the cross-platform, performance, and usability benefits of ONNX Runtime, members of the community have also contributed samples and UI tools of their own using Stable Diffusion with ONNX Runtime.
These community contributions include [OnnxStack](https://github.com/saddam213/OnnxStack), a .NET library that builds upon our [previous C# tutorial](https://github.com/cassiebreviu/StableDiffusion/) to provide users with a variety of capabilities for many different Stable Diffusion models when performing inference with C# and ONNX Runtime.
Additionally, Oracle has released a [Stable Diffusion sample with Java](https://github.com/oracle-samples/sd4j) that runs inference on top of ONNX Runtime. This project is also based on our C# tutorial.

2024-01-11 08:37 UTC, sophies927 commented on sdxl_ort_inference.md
> +## Benchmark results
Replace current 'Benchmark results' section w/ the following:
## Benchmark results
We benchmarked the SD Turbo and SDXL Turbo models with Standard_ND96amsr_A100_v4 VM using A100-SXM4-80GB and a [Lenovo Desktop](https://www.lenovo.com/us/en/p/desktops/legion-desktops/legion-t-series-towers/legion-tower-7i-gen-8-(34l-intel)/90v7003bus) with RTX-4090 GPU (WSL Ubuntu 20.04) to generate images of resolution 512x512 using the LCM Scheduler and fp16 models. The results are measured using these specifications:
- onnxruntime-gpu==1.17.0 (built from source)
- torch==2.1.0a0+32f93b1
- tensorrt==8.6.1
- transformers==4.36.0
- diffusers==0.24.0
- onnx==1.14.1
- onnx-graphsurgeon==0.3.27
- polygraphy==0.49.0

To reproduce these results, we recommend using the instructions linked in the ‘Usage example’ section.
Since the original VAE of SDXL Turbo cannot run in fp16 precision, we used [sdxl-vae-fp16-fix](https://huggingface.co/madebyollin/sdxl-vae-fp16-fix) in testing SDXL Turbo. There are slight discrepancies between its output and that of the original VAE, but the decoded images are close enough for most purposes.
The PyTorch pipeline for static shape has applied channel-last memory format and torch.compile with reduce-overhead mode.
The following charts illustrate the throughput in images per second vs. different (batch size, number of steps) combinations for various frameworks. It is worth noting that the label above each bar indicates the speedup percentage vs. Torch Compile – e.g., in the first chart, ORT_TRT (Static) is 31% faster than Torch (Compile) for (batch, steps) combination (4, 1).
We elected to use 1 and 4 steps because both SD Turbo and SDXL Turbo can generate viable images in as little as 1 step but typically produce images of the best quality in 3-5 steps.

### SDXL Turbo
The graphs below illustrate the throughput in images per second for the SDXL Turbo model with both static and dynamic shape. Results were gathered on an A100-SXM4-80GB GPU for different (batch size, number of steps) combinations. For dynamic shape, the TensorRT engine supports batch size 1 to 8 and image size 512x512 to 768x768, but it is optimized for batch size 1 and image size 512x512.
![SDXL Turbo Static Throughput](https://github.com/huggingface/blog/assets/107952697/26c589d4-cea6-4164-92b3-de47093654b7)
![SDXL Turbo Dynamic Throughput](https://github.com/huggingface/blog/assets/107952697/a362069c-3c73-49dd-ab2a-968974dce292)

### SD Turbo
The next two graphs illustrate throughput in images per second for the SD Turbo model with both static and dynamic shape on an A100-SXM4-80GB GPU.
![SD Turbo Static A100 Throughput](https://github.com/huggingface/blog/assets/107952697/3d26b605-73a4-4858-a492-e6b1fc5316ee)
![SD Turbo Dynamic A100 Throughput](https://github.com/huggingface/blog/assets/107952697/3d9981cb-3d96-4b05-927f-77f589cf0899)
The final set of graphs illustrates throughput in images per second for the SD Turbo model with both static and dynamic shape on an RTX-4090 GPU. In this dynamic shape test, the TensorRT engine is built for batch size 1 to 8 (optimized for batch size 1) and fixed image size 512x512 due to memory limitation.
![SD Turbo Static RTX Throughput](https://github.com/huggingface/blog/assets/107952697/34223c0f-3a14-49b7-94d9-954519245df5)
![SD Turbo Dynamic RTX Throughput](https://github.com/huggingface/blog/assets/107952697/ca87871e-030a-40a5-b3b8-63603f35ce36)

### How fast are SD Turbo and SDXL Turbo with ONNX Runtime?
These results demonstrate that ONNX Runtime significantly outperforms PyTorch with both CUDA and TensorRT execution providers in static and dynamic shape for all (batch, steps) combinations shown. This conclusion applies to both model sizes (SD Turbo and SDXL Turbo), as well as both GPUs tested. Notably, ONNX Runtime with CUDA (dynamic shape) was shown to be 229% faster than Torch Eager for (batch, steps) combination (1, 4).
Additionally, ONNX Runtime with the TensorRT execution provider performs slightly better for static shape given that the ORT_TRT throughput is higher than the corresponding ORT_CUDA throughput for most (batch, steps) combinations. Static shape is typically favored when the user knows the batch and image size at graph definition time (e.g., the user is only planning to generate images with batch size 1 and image size 512x512). In these situations, the static shape has faster performance. However, if the user decides to switch to a different batch and/or image size, TensorRT must create a new engine (meaning double the engine files in the disk) and switch engines (meaning additional time spent loading the new engine).
On the other hand, ONNX Runtime with the CUDA execution provider is often a better choice for dynamic shape for SD Turbo and SDXL Turbo models when using an A100-SXM4-80GB GPU, but ONNX Runtime with the TensorRT execution provider performs slightly better on dynamic shape for most (batch, steps) combinations when using an RTX-4090 GPU. The benefit of using dynamic shape is that users can run inference more quickly when the batch and image sizes are not known until graph execution time (e.g., running batch size 1 and image size 512x512 for one image and batch size 4 and image size 512x768 for another). When dynamic shape is used in these cases, users only need to build and save one engine, rather than switching engines during inference.

2024-01-11 08:37 UTC, sophies927 commented on sdxl_ort_inference.md
> +## GPU optimizations
Replace 'GPU optimizations' section w/ the following:
## GPU optimizations
Besides the techniques introduced in our [previous Stable Diffusion blog](https://medium.com/microsoftazure/accelerating-stable-diffusion-inference-with-onnx-runtime-203bd7728540), the following optimizations were applied by ONNX Runtime to yield the SD Turbo and SDXL Turbo results outlined in this post:
- Enable CUDA graph for static shape inputs.
- Add Flash Attention V2.
- Remove extra outputs in text encoder (keep the hidden state output specified by clip_skip parameter).
- Add SkipGroupNorm fusion to fuse group normalization with Add nodes that precede it.

Additionally, we have added support for new features, including [LoRA](https://huggingface.co/docs/peft/conceptual_guides/lora) weights for latent consistency models (LCMs).

2024-01-11 08:37 UTC, sophies927 commented on sdxl_ort_inference.md
> +## Next steps
Replace 'Next steps' section w/ the following:
## Next steps
In the future, we plan to continue improving upon our Stable Diffusion work by updating the demo to support new features, such as [IP Adapter](https://github.com/tencent-ailab/IP-Adapter) and Stable Video Diffusion. [ControlNet](https://huggingface.co/docs/diffusers/api/pipelines/controlnet) support will also be available shortly.
We are also working on optimizing SD Turbo and SDXL Turbo performance with our [existing Stable Diffusion web UI extension](https://github.com/tianleiwu/Stable-Diffusion-WebUI-OnnxRuntime) and plan to help add support for both models to a Windows UI developed by a member of the ONNX Runtime community.
Additionally, a tutorial for how to run SD Turbo and SDXL Turbo with C# and ONNX Runtime is coming soon. In the meantime, check out our [previous tutorial on Stable Diffusion](https://onnxruntime.ai/docs/tutorials/csharp/stable-diffusion-csharp.html).

2024-01-11 08:37 UTC, sophies927 commented on sdxl_ort_inference.md
> +## Resources
Replace 'resources' section w/ the following:
## Resources
Check out some of the resources discussed in this post:
- [SD Turbo](https://huggingface.co/tlwu/sd-turbo-onnxruntime): Olive-optimized SD Turbo for ONNX Runtime CUDA model hosted on Hugging Face.
- [SDXL Turbo](https://huggingface.co/tlwu/sdxl-turbo-onnxruntime): Olive-optimized SDXL Turbo for ONNX Runtime CUDA model hosted on Hugging Face.
- [Stable Diffusion GPU Optimization](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/transformers/models/stable_diffusion/README.md): Instructions for optimizing Stable Diffusion with NVIDIA GPUs in ONNX Runtime GitHub repository.
- [ONNX Runtime Extension for Automatic1111’s SD WebUI](https://github.com/tianleiwu/Stable-Diffusion-WebUI-OnnxRuntime): Extension enabling optimized execution of Stable Diffusion UNet model on NVIDIA GPUs.
- [OnnxStack](https://github.com/saddam213/OnnxStack): Community-contributed .NET library enabling Stable Diffusion inference with C# and ONNX Runtime.
- [SD4J (Stable Diffusion in Java)](https://github.com/oracle-samples/sd4j): Oracle sample for Stable Diffusion with Java and ONNX Runtime.
- [Inference Stable Diffusion with C# and ONNX Runtime](https://onnxruntime.ai/docs/tutorials/csharp/stable-diffusion-csharp.html): Previously published C# tutorial.

2024-01-11 18:59 UTC, sophies927 requested changes
Looks great! Just added some comments w/ a few things I missed during the last review (the majority of which are additional lines that I forgot to add originally to separate out the paragraphs). Once these changes are in, it should be good to go!

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +title: "Accelerating SD Turbo and SDXL Turbo Inference with ONNX Runtime"
Update this title to match the one below: "Accelerating SD Turbo and SDXL Turbo Inference with ONNX Runtime and Olive".

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +## Analysis
Can you remove this entire 'Analysis' section? We decided to replace it w/the 'How fast are SD Turbo and SDXL Turbo with ONNX Runtime?' section above.

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +In this post, we will introduce optimizations in the ONNX Runtime CUDA and TensorRT execution providers that speed up inference of SD Turbo and SDXL Turbo on NVIDIA GPUs significantly.
Add a line between lines 18 and 19 so they're separate paragraphs.

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +To accelerate inference with the ONNX Runtime CUDA execution provider, access our optimized versions of [SD Turbo](https://huggingface.co/tlwu/sd-turbo-onnxruntime) and [SDXL Turbo](https://huggingfa
Add a line between lines 25 and 26 so they're separate paragraphs.

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +The models are generated by [Olive](https://github.com/microsoft/Olive/tree/main/examples/stable_diffusion), an easy-to-use model optimization tool that is hardware aware. Note that fp16 VAE must be
Add a line between lines 26 and 27 so they're separate paragraphs.

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +Note that the example image was generated in 4 steps, demonstrating the ability of SD Turbo and SDXL Turbo to generate viable images in fewer steps than previous Stable Diffusion models.
Add a line between lines 41 and 42 so they're separate paragraphs.

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +Taking advantage of the cross-platform, performance, and usability benefits of ONNX Runtime, members of the community have also contributed samples and UI tools of their own using Stable Diffusion wi
Add a line between lines 45 and 46 so they're separate paragraphs.

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +These community contributions include [OnnxStack](https://github.com/saddam213/OnnxStack), a .NET library that builds upon our [previous C# tutorial](https://github.com/cassiebreviu/StableDiffusion/)
Add a line between lines 46 and 47 so they're separate paragraphs.

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +To reproduce these results, we recommend using the instructions linked in the ‘Usage example’ section.
Add a line between lines 61 and 62 so they're separate paragraphs.

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +Since the original VAE of SDXL Turbo cannot run in fp16 precision, we used [sdxl-vae-fp16-fix](https://huggingface.co/madebyollin/sdxl-vae-fp16-fix) in testing SDXL Turbo. There are slight discrepanc
Add a line between lines 62 and 63 so they're separate paragraphs.

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +The PyTorch pipeline for static shape has applied channel-last memory format and torch.compile with reduce-overhead mode.
Add a line between lines 63 and 64 so they're separate paragraphs.

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +The following charts illustrate the throughput in images per second vs. different (batch size, number of steps) combinations for various frameworks. It is worth noting that the label above each bar i
Add a line between lines 64 and 65 so they're separate paragraphs.

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +The graphs below illustrate the throughput in images per second for the SDXL Turbo model with both static and dynamic shape. Results were gathered on an A100-SXM4-80GB GPU for different (batch size,
Add a line between lines 68 and 69 to separate the text from the images.

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +The next two graphs illustrate throughput in images per second for the SD Turbo model with both static and dynamic shape on an A100-SXM4-80GB GPU.
Add a line between lines 73 and 74 to separate the text from the images.

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +![Throughput for SD Turbo on A100 Tensor Cores GPU (dynamic shapes)](assets/sdxl_ort_inference/sd_turbo_a100_perf_chart_dynamic.svg)
Add a line between lines 75 and 76 to separate the text from the images.

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +The final set of graphs illustrates throughput in images per second for the SD Turbo model with both static and dynamic shape on an RTX-4090 GPU. In this dynamic shape test, the TensorRT engine is bu
Add a line between lines 76 and 77 to separate the text from the images.

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +These results demonstrate that ONNX Runtime significantly outperforms PyTorch with both CUDA and TensorRT execution providers in static and dynamic shape for all (batch, steps) combinations shown. Th
Add a line between lines 81 and 82 so they're separate paragraphs.

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +Additionally, ONNX Runtime with the TensorRT execution provider performs slightly better for static shape given that the ORT_TRT throughput is higher than the corresponding ORT_CUDA throughput for mo
Add a line between lines 82 and 83 so they're separate paragraphs.

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +In the future, we plan to continue improving upon our Stable Diffusion work by updating the demo to support new features, such as [IP Adapter](https://github.com/tencent-ailab/IP-Adapter) and Stable
Add a line between lines 112 and 113 so they're separate paragraphs.

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +We are also working on optimizing SD Turbo and SDXL Turbo performance with our [existing Stable Diffusion web UI extension](https://github.com/tianleiwu/Stable-Diffusion-WebUI-OnnxRuntime) and plan t
Add a line between lines 113 and 114 so they're separate paragraphs.

2024-01-11 18:59 UTC, sophies927 commented on sdxl_ort_inference.md
> +To accelerate inference with the ONNX Runtime TensorRT execution provider instead, follow the instructions found [here](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/tra
Add a line between lines 27 and 28 so they're separate paragraphs.

2024-01-12 15:20 UTC, sophies927 approved these changes
Looks great - I don't have any additional changes to suggest, so this should be good to go!

2024-01-15 12:35 UTC, echarlaix approved these changes

2024-01-15 13:50 UTC, merged