New post: Accelerating PyTorch distributed fine-tuning with Intel technologies
huggingface/blog pull request #177
Opened 2021-11-16 10:55 UTC by juliensimon

In this post, you will learn how to accelerate PyTorch training jobs by distributing them on a cluster of Intel Xeon Scalable CPU servers, powered by the Ice Lake architecture and running performance-optimized software libraries. We will build the cluster from scratch using virtual machines, and you should able to easily replicate the demo on your own infrastructure, either in the cloud or on premise.

2021-11-16 12:05 UTC, julien-c commented on intel_dist_training.md
> +---
this file's name will need to be the url slug that the blog post will live under

2021-11-17 00:24 UTC, jeffboudier commented on intel_dist_training.md
> +In this post, you will learn how to accelerate [PyTorch](https://pytorch.org) training jobs by distributing them on a cluster of Intel Xeon Scalable CPU servers, powered by the Ice Lake architecture
```suggestion
In this post, you will learn how to accelerate [PyTorch](https://pytorch.org) training jobs by distributing them on a cluster of Intel Xeon Scalable CPU servers, powered by the Ice Lake architecture and running performance-optimized software libraries. We will build the cluster from scratch using virtual machines, and you should be able to easily replicate the demo on your own infrastructure, either in the cloud or on premise.
```

2021-11-17 01:35 UTC, hshen14 commented on intel_dist_training.md
> +git clone https://github.com/kding1/transformers.git
maybe add a comment to use your own cloned repo

2021-11-17 02:30 UTC, hshen14 commented on intel_dist_training.md
> ++    if "ccl" in sys.argv:
do we need to keep all ccl related stuff (e.g., import, and sys.argv) under if condition?

2021-11-17 03:32 UTC, kding1 commented on intel_dist_training.md
> +export CCL_WORKER_AFFINITY="0,1,2,3,32,33,34,34,35"
34 is repeated.

2021-11-17 04:28 UTC, kding1 commented on intel_dist_training.md
> +* 2 nodes: 7 hours and 52 minutes (1.45x),
this number seems slightly off from scaling efficiency perspective. I am getting a new measurement for your reference, should be ready tomorrow morning. it's trending to be 6 hour 38 min.

2021-11-17 10:28 UTC, juliensimon commented on intel_dist_training.md
> ++    if "ccl" in sys.argv:
Yes, we may want to use another backend, such as 'mpi'

2021-11-17 10:31 UTC, juliensimon commented on intel_dist_training.md
> +export CCL_WORKER_AFFINITY="0,1,2,3,32,33,34,34,35"
Geez.... Fixed.

2021-11-17 10:56 UTC, juliensimon commented on intel_dist_training.md
> +* 2 nodes: 7 hours and 52 minutes (1.45x),
yes, I ran it again for a little while and it converged to a similar value.

2021-11-17 10:58 UTC, juliensimon commented on intel_dist_training.md
> +---
yes, I'll fix it.

2021-11-17 11:14 UTC, juliensimon commented on intel_dist_training.md
> +git clone https://github.com/kding1/transformers.git
we'll keep working on this one, so I'll leave it for now

2021-11-17 11:17 UTC, juliensimon commented
Thanks for the comments. I also added _blog_yml. I believe this is good to go.

2021-11-17 11:38 UTC, julien-c requested changes

2021-11-17 11:38 UTC, julien-c commented on _blog.yml
> +- local: accelerating-pytorch-distributed-fine-tuning
pet peeve of mine, but any way to do a shorter url?

like `accelerating-pytorch` or `faster-pytorch-with-intel` or... ?

Let's say less than 25 chars as a good guideline 😅

2021-11-17 13:04 UTC, juliensimon commented on _blog.yml
> +- local: accelerating-pytorch-distributed-fine-tuning
no problem, renamed it to accelerating-pytorch.

2021-11-17 19:44 UTC, julien-c approved these changes

2021-11-19 09:44 UTC, merged