Gemma PEFT Blogpost
huggingface/blog pull request #1843
Opened 2024-02-21 19:46 UTC by ultrons

Creating the PR for the PEFT blogpost.
cc @jeffboudier @ArthurZucker @younesbelkada

2024-02-21 20:05 UTC, alanwaketan approved these changes
LGTM!

2024-02-21 20:05 UTC, alanwaketan commented on gemma-peft.md
> +We walked through this simple example adapted from the source notebook to illustrate the LoRA finetuning method applied to Gemma models. The full colab for GPU can be found [here](https://huggingface
Will it be better to link to the script directly? Say
1. https://huggingface.co/google/gemma-7b/blob/main/examples/notebook_sft_peft.ipynb
2. https://huggingface.co/google/gemma-7b/blob/main/examples/example_fsdp.py

2024-02-21 22:02 UTC, osanseviero commented on gemma-peft.md
> +Gemma models in HuggingFace transformers are well optimized for both PyTorch and PyTorch/XLA. This enables both TPU and GPU users to access and experiment with Gemma models as needed. Together with t
```suggestion
## PyTorch on GPU and TPU

Gemma models in Hugging Face `transformers` are optimized for both PyTorch and PyTorch/XLA. This enables both TPU and GPU users to access and experiment with Gemma models as needed. Together with the Gemma release, we also improved the [FSDP](https://engineering.fb.com/2021/07/15/open-source/fsdp/) experience for PyTorch/XLA in Hugging Face. This [FSDP via SPMD](https://github.com/pytorch/xla/issues/6379) integration also allows other Hugging Face models to take advantage of TPU acceleration via PyTorch/XLA. In this post, we will focus on PEFT, more specifically, Low-Rank Adaptation (LoRA), for Gemma models. For a more comprehensive set of LoRA techniques, we encourage readers to review the [Scaling Down to Scale Up, from Lialin et al.](https://arxiv.org/pdf/2303.15647.pdf) and [this](https://pytorch.org/blog/finetune-llms/) excellent blog post by Belkada et al. 
```

2024-02-21 22:02 UTC, osanseviero commented on gemma-peft.md
> +Low-Rank Adaptation (LoRA) is one of the parameter-efficient fine-tuning techniques for large language models (LLMs). It incorporates a fraction of total model parameters to be fine-tuned by freezing
```suggestion
## Low-Rank Adaptation for Large Language Models

Low-Rank Adaptation (LoRA) is one of the parameter-efficient fine-tuning techniques for large language models (LLMs). It incorporates a fraction of total model parameters to be fine-tuned by freezing the original model and only training an adapter layer which is decomposed into low-rank matrices. PEFT library provides an easy abstraction that allows users to select particular layers from the model where adapter weights are applied.
```

2024-02-21 22:02 UTC, osanseviero commented on gemma-peft.md
> +In order to access Gemma model artifacts, the users are required to accept the consent form here ([link](https://www.kaggle.com/models/google/gemma/license/consent)).
```suggestion
## Before we begin

In order to access Gemma model artifacts, the users are required to accept the consent form here ([link](https://huggingface.co/google/gemma-7b-it)).
```

2024-02-21 22:02 UTC, osanseviero commented on gemma-peft.md
> +Assuming that you have submitted the consent form, you can access the model artifact from the [Hugging Face models](https://huggingface.co/collections/google/gemma-release-65d5efbccdbb8c4202ec078b).
```suggestion
## Learning to quote

Assuming that you have submitted the consent form, you can access the model artifact from the [Hugging Face models](https://huggingface.co/collections/google/gemma-release-65d5efbccdbb8c4202ec078b).
```

2024-02-21 22:02 UTC, osanseviero commented on gemma-peft.md
> +As mentioned earlier, HuggingFace transformers now support PyTorch/XLA’s latest FSDP implementation. This can greatly accelerate the fine-tuning speed. To enable that, one just need to add a FSDP con
```suggestion

# Accelerate with FSDP via SPMD on TPU
As mentioned earlier, Hugging Face `transformers` now support PyTorch/XLA’s latest FSDP implementation. This can greatly accelerate the fine-tuning speed. To enable that, one just needs to add an FSDP config to the `transformers.Trainer`:
```

2024-02-21 22:02 UTC, osanseviero commented on gemma-peft.md
> +We walked through this simple example adapted from the source notebook to illustrate the LoRA finetuning method applied to Gemma models. The full colab for GPU can be found [here](https://huggingface
```suggestion
## Next Steps

We walked through this simple example adapted from the source notebook to illustrate the LoRA finetuning method applied to Gemma models. The full Colab for GPU can be found [here](https://huggingface.co/google/gemma-7b/tree/main/examples), and the full script for TPU can be found [here](https://huggingface.co/google/gemma-7b/tree/main/examples). We are excited about the endless possibilities for research and learning thanks to this recent addition to our open-source ecosystem. We encourage users to also visit Gemma documentation and our launch blog for more examples to train, finetune and deploy Gemma models. 
```

2024-02-21 22:06 UTC, ultrons commented on gemma-peft.md
> +title: Fine-Tuning Gemma Models in Hugging Face
I noticed that. Should we just use the image we have after the first paragraph. Or do you have any suggestions for the thumbnail?

2024-02-21 22:14 UTC, pcuenca commented on gemma-peft.md
> +- user: arthur
```suggestion
- user: ybelkada
- user: ArthurZ
```

2024-02-21 22:14 UTC, pcuenca commented on gemma-peft.md
> +The Gemma family of models also happens to be well suited for prototyping and experimentation using the free GPU resource via Colab. In this post we will briefly review how you can do Parameter Effic
```suggestion
The Gemma family of models also happens to be well suited for prototyping and experimentation using the free GPU resource via Colab. In this post we will briefly review how you can do Parameter Efficient FineTuning (PEFT) for Gemma models, using the Hugging Face Transformers and PEFT libraries on GPUs and Cloud TPUs for anyone who wants to fine-tune Gemma models on their own dataset.
```

2024-02-21 22:39 UTC, pcuenca reviewed
Thanks a lot for the great contribution! 🔥

2024-02-21 22:39 UTC, pcuenca commented on gemma-peft.md
> +title: Fine-Tuning Gemma Models in Hugging Face
Ideally it should be more visual and with a size ratio of 1300x650 for best results everywhere. Perhaps you can play with the Gemma logo and mention PEFT? You can check [the main page](https://huggingface.co/blog) for inspiration :)

2024-02-21 22:39 UTC, pcuenca commented on gemma-peft.md
> +- user: sivaibhav
```suggestion
- user: svaibhav
```

2024-02-21 22:39 UTC, pcuenca commented on gemma-peft.md
> +
```suggestion

# Fine-Tuning Gemma Models in Hugging Face

```

The title also needs to be present in the body, in addition to being in the metadata :)

2024-02-21 22:39 UTC, pcuenca commented on gemma-peft.md
> +## Introduction
I'd maybe remove this heading since it comes immediately after the title, see https://huggingface.co/blog/gemma for an example of how this is rendered.

2024-02-21 22:39 UTC, pcuenca commented on gemma-peft.md
> +In the following example, we will leverage [QLoRA, from Dettmers et al.](https://arxiv.org/abs/2305.14314) in order to quantize the base model in 4-bit precision for a more memory efficient fine-tuni
There's also a [blog post about QLoRA](https://huggingface.co/blog/4bit-transformers-bitsandbytes), just in case you want to refer to something less technical and closer in style.

2024-02-21 22:39 UTC, pcuenca commented on gemma-peft.md
> +In order to access Gemma model artifacts, the users are required to accept the consent form here ([link](https://huggingface.co/google/gemma-7b-it)).
```suggestion
In order to access Gemma model artifacts, users are required to accept [the consent form](https://huggingface.co/google/gemma-7b-it).
```

2024-02-21 22:39 UTC, pcuenca commented on gemma-peft.md
> +Assuming that you have submitted the consent form, you can access the model artifact from the [Hugging Face models](https://huggingface.co/collections/google/gemma-release-65d5efbccdbb8c4202ec078b).
```suggestion
Assuming that you have submitted the consent form, you can access the model artifacts from the [Hugging Face Hub](https://huggingface.co/collections/google/gemma-release-65d5efbccdbb8c4202ec078b).
```

2024-02-21 22:39 UTC, pcuenca commented on gemma-peft.md
> +We start by downloading the model and tokenizer into the respective objects. Here we are also including BitsAndBytesConfig for weight only quantization.
```suggestion
We start by downloading the model and tokenizer into the respective objects. Here we are also including `BitsAndBytesConfig` for weight only quantization.
```

2024-02-21 22:39 UTC, pcuenca commented on gemma-peft.md
> +from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig, GemmaTokenizer
```suggestion
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
```

2024-02-21 22:39 UTC, pcuenca commented on gemma-peft.md
> +model = AutoModelForCausalLM.from_pretrained(model_id, quantization_config=bnb_config, device_map={"":0}, token=os.environ['HF_TOKEN'])
This requires the user to add the token to the environment. Maybe we could just mention in the text that the user has to be logged in to the Hugging Face Hub. In that case there'd be no need to include the `token` parameter as it will be picked up automatically.

2024-02-21 22:39 UTC, pcuenca commented on gemma-peft.md
> +# Accelerate with FSDP via SPMD on TPU
```suggestion
## Accelerate with FSDP via SPMD on TPU

```

The level-1 heading is reserved for the title :)

2024-02-21 22:39 UTC, pcuenca commented on gemma-peft.md
> +# Next Steps
```suggestion
## Next Steps

```

2024-02-21 22:39 UTC, pcuenca commented on gemma-peft.md
> +We walked through this simple example adapted from the source notebook to illustrate the LoRA finetuning method applied to Gemma models. The full colab for GPU can be found [here](https://huggingface
```suggestion
We walked through this simple example adapted from the source notebook to illustrate the LoRA finetuning method applied to Gemma models. The full colab for GPU can be found [here](https://huggingface.co/google/gemma-7b/blob/main/examples/notebook_sft_peft.ipynb), and the full script for TPU can be found [here](https://huggingface.co/google/gemma-7b/blob/main/examples/example_fsdp.py). We are excited about the endless possibilities for research and learning thanks to this recent addition to our open source ecosystem. We encourage users to also visit the [Gemma documentation](https://huggingface.co/docs/transformers/v4.38.0/en/model_doc/gemma), as well as our launch blog for more examples to train, finetune and deploy Gemma models. 
```

Maybe also link either the HF blog post or Google's.

2024-02-22 20:48 UTC, ultrons commented on gemma-peft.md
> +We walked through this simple example adapted from the source notebook to illustrate the LoRA finetuning method applied to Gemma models. The full colab for GPU can be found [here](https://huggingface
Updated.

2024-02-22 20:49 UTC, ultrons commented on gemma-peft.md
> +- user: sivaibhav
Thanks @osanseviero , does '- guest' line you added solves this?

2024-02-22 21:01 UTC, ultrons commented on gemma-peft.md
> +model = AutoModelForCausalLM.from_pretrained(model_id, quantization_config=bnb_config, device_map={"":0}, token=os.environ['HF_TOKEN'])
In the source colab, we took this approach. Alternatively we could have included the login to the hub  step. I found this approach to be more explicit and intuitive.

2024-02-22 22:37 UTC, pcuenca approved these changes
Looks good! Feel free to ping us to publish when the thumbnail is ready :)

2024-02-23 01:45 UTC, ultrons commented on gemma-peft.md
> +title: Fine-Tuning Gemma Models in Hugging Face
Done. PTAL.

2024-02-23 02:09 UTC, younesbelkada approved these changes
Looking great ! Thank you very much !

2024-02-23 06:28 UTC, jeffboudier requested changes

2024-02-23 06:28 UTC, jeffboudier commented on _blog.yml
> +  title: "Welcome Gemma - Google's new open LLM"
```suggestion
  title: "Fine-Tuning Gemma Models in Hugging Face"
```

2024-02-23 13:10 UTC, younesbelkada commented on _blog.yml
> +  date: Feb 22, 2024
```suggestion
  date: Feb 23, 2024
```

2024-02-23 18:34 UTC, jeffboudier approved these changes
Great post, thanks!

2024-02-23 18:34 UTC, jeffboudier commented on gemma-peft.md
> +We walked through this simple example adapted from the source notebook to illustrate the LoRA finetuning method applied to Gemma models. The full colab for GPU can be found [here](https://huggingface
```suggestion
We walked through this simple example adapted from the source notebook to illustrate the LoRA finetuning method applied to Gemma models. The full colab for GPU can be found [here](https://huggingface.co/google/gemma-7b/blob/main/examples/notebook_sft_peft.ipynb), and the full script for TPU can be found [here](https://huggingface.co/google/gemma-7b/blob/main/examples/example_fsdp.py). We are excited about the endless possibilities for research and learning thanks to this recent addition to our open source ecosystem. We encourage users to also visit the [Gemma documentation](https://huggingface.co/docs/transformers/v4.38.0/en/model_doc/gemma), as well as our [launch blog](https://huggingface.co/blog/gemma) for more examples to train, finetune and deploy Gemma models. 
```

2024-02-23 20:25 UTC, pcuenca commented on gemma-peft.md
> +The default (full weight) training for language models, even for modest sizes, tends to be memory and compute-intensive. On one hand, it can be prohibitive for users relying on openly available compu
```suggestion
The default (full weight) training for language models, even for modest sizes, tends to be memory and compute-intensive. On one hand, it can be prohibitive for users relying on openly available compute platforms for learning and experimentation, such as Colab or Kaggle. On the other hand, and even for enterprise users, the cost of adapting these models for different domains is an important metric to optimize. PEFT, or parameter-efficient fine tuning, is a popular technique to accomplish this at low cost.
```

2024-02-23 20:28 UTC, pcuenca commented on gemma-peft.md
> +Gemma models in Hugging Face `transformers` are optimized for both PyTorch and PyTorch/XLA. This enables both TPU and GPU users to access and experiment with Gemma models as needed. Together with the
```suggestion
Gemma models in Hugging Face `transformers` are optimized for both PyTorch and PyTorch/XLA. This enables both TPU and GPU users to access and experiment with Gemma models as needed. Together with the Gemma release, we also improved the [FSDP](https://engineering.fb.com/2021/07/15/open-source/fsdp/) experience for PyTorch/XLA in Hugging Face. This [FSDP via SPMD](https://github.com/pytorch/xla/issues/6379) integration also allows other Hugging Face models to take advantage of TPU acceleration via PyTorch/XLA. In this post, we will focus on PEFT, and more specifically on Low-Rank Adaptation (LoRA), for Gemma models. For a more comprehensive set of LoRA techniques, we encourage readers to review the [Scaling Down to Scale Up, from Lialin et al.](https://arxiv.org/pdf/2303.15647.pdf) and [this excellent post](https://pytorch.org/blog/finetune-llms/) post by Belkada et al. 
```

2024-02-23 20:30 UTC, pcuenca commented on gemma-peft.md
> +Low-Rank Adaptation (LoRA) is one of the parameter-efficient fine-tuning techniques for large language models (LLMs). It incorporates a fraction of total model parameters to be fine-tuned by freezing
```suggestion
Low-Rank Adaptation (LoRA) is one of the parameter-efficient fine-tuning techniques for large language models (LLMs). It addresses just a fraction of the total number of model parameters to be fine-tuned, by freezing the original model and only training adapter layers that are decomposed into low-rank matrices. The [PEFT library](https://github.com/huggingface/peft) provides an easy abstraction that allows users to select the model layers  where adapter weights should be applied.
```

2024-02-23 20:31 UTC, pcuenca commented on gemma-peft.md
> +In the following example, we will leverage [QLoRA](https://huggingface.co/blog/4bit-transformers-bitsandbytes), from [Dettmers et al.](https://arxiv.org/abs/2305.14314) in order to quantize the base
```suggestion
In the following example, we will leverage [QLoRA](https://huggingface.co/blog/4bit-transformers-bitsandbytes), from [Dettmers et al.](https://arxiv.org/abs/2305.14314), in order to quantize the base model in 4-bit precision for a more memory efficient fine-tuning protocol. The model can be loaded with QLoRA by first installing the `bitsandbytes` library on your environment, then passing a `BitsAndBytesConfig` object to `from_pretrained` when loading the model.
```

2024-02-23 20:33 UTC, pcuenca commented on gemma-peft.md
> +We start by downloading the model and tokenizer into the respective objects. Here we are also including `BitsAndBytesConfig` for weight only quantization.
```suggestion
We start by downloading the model and tokenizer. We also include a `BitsAndBytesConfig` for weight only quantization.
```

2024-02-23 20:33 UTC, pcuenca commented on gemma-peft.md
> +To begin with, let's select an English quotes dataset.
```suggestion

To begin with, let's select an English quotes dataset.

```

2024-02-23 20:34 UTC, pcuenca commented on gemma-peft.md
> +As mentioned earlier, Hugging Face `transformers` now support PyTorch/XLA’s latest FSDP implementation. This can greatly accelerate the fine-tuning speed. To enable that, one just needs to add an FSD
```suggestion
As mentioned earlier, Hugging Face `transformers` now supports PyTorch/XLA’s latest FSDP implementation. This can greatly accelerate the fine-tuning speed. To enable that, one just needs to add an FSDP config to the `transformers.Trainer`:
```

2024-02-23 20:35 UTC, pcuenca commented on gemma-peft.md
> +    "xla_fsdp_grad_ckpt": True}
```suggestion
fsdp_config = {
    "fsdp_transformer_layer_cls_to_wrap": ["GemmaDecoderLayer"],
    "xla": True,
    "xla_fsdp_v2": True,
    "xla_fsdp_grad_ckpt": True
}
```

2024-02-23 20:53 UTC, merged