Add rloo blog post
huggingface/blog pull request #2110
Opened 2024-05-30 14:17 UTC by vwxyzjn

2024-06-11 18:14 UTC, lewtun approved these changes
LGTM apart from needing to move the images to a Hub repo and tweak the user profile!

cc @pcuenca for final approval

2024-06-11 18:14 UTC, lewtun commented on assets/putting_rl_back_in_rlhf_with_rloo/image1.png
All images except the thumbnail should go in a Hub dataset, e.g. here: https://huggingface.co/datasets/huggingface/documentation-images/tree/main/blog

2024-06-11 18:14 UTC, lewtun commented on putting_rl_back_in_rlhf_with_rloo.md
> +- user: ArashAhmadian
```suggestion
- user: ArashAhmadian
  guest: true
```

2024-06-11 20:20 UTC, vwxyzjn commented on assets/putting_rl_back_in_rlhf_with_rloo/image1.png
Have already updated to use the hub images.

2024-06-11 21:00 UTC, osanseviero reviewed
Very nice!

2024-06-11 21:00 UTC, osanseviero commented on putting_rl_back_in_rlhf_with_rloo.md
> +authors:
You can also add `org: X` (where X is from the Hub) to each person so there's a nice logo. See https://github.com/haim-barad/huggingface-blog/blob/main/assisted-generation-support-gaudi.md?plain=1

2024-06-11 21:00 UTC, osanseviero commented on putting_rl_back_in_rlhf_with_rloo.md
> +---
You need t o updat https://github.com/huggingface/blog/blob/main/_blog.yml as well

2024-06-11 21:00 UTC, osanseviero commented on assets/putting_rl_back_in_rlhf_with_rloo/image1.png
The PR still includes many images that should be removed

2024-06-11 21:00 UTC, osanseviero commented on putting_rl_back_in_rlhf_with_rloo.md
> +We are excited to introduce the RLOO (REINFORCE Leave One-Out) Trainer in TRL. As an alternative to PPO, RLOO is a new online RLHF training algorithm that is designed to be more accessible and easier
```suggestion
We are excited to introduce the RLOO (REINFORCE Leave One-Out) Trainer in TRL. As an alternative to PPO, RLOO is a new online RLHF training algorithm designed to be more accessible and easier to implement. In particular, **RLOO requires less GPU memory and takes less wall time to converge.** As shown in the figures below:
```

2024-06-11 21:00 UTC, osanseviero commented on putting_rl_back_in_rlhf_with_rloo.md
> +With RLOO, we bring reinforcement learning back into RLHF, enabling the community to explore online RL methods more easily. This is exciting because more and more studies have shown that online RL is
```suggestion
With RLOO, we bring Reinforcement Learning back into RLHF, enabling the community to explore online RL methods more easily. This is exciting because more and more studies have shown that online RL is more effective than offline methods such as DPO ([https://arxiv.org/abs/2402.04792](https://arxiv.org/abs/2402.04792), [https://arxiv.org/abs/2405.08448](https://arxiv.org/abs/2405.08448)). 
```

2024-06-11 21:00 UTC, osanseviero commented on putting_rl_back_in_rlhf_with_rloo.md
> +
nit
```suggestion
```

2024-06-11 21:00 UTC, osanseviero commented on putting_rl_back_in_rlhf_with_rloo.md
> +1. The policy model would generate some completion tokens and get the per-token logprobs under the current policy and the reference policy.
```suggestion
1. The policy model would generate some completion tokens and get the per-token log probs under the current and reference policies. 
```

2024-06-11 21:00 UTC, osanseviero commented on putting_rl_back_in_rlhf_with_rloo.md
> +2. We then calculate the per-token KL penalties as the difference between the logprobs under the current policy and the reference policy.
```suggestion
2. We then calculate the per-token KL penalties as the difference between the logprobs under the current and reference policies.
```

2024-06-11 21:00 UTC, osanseviero commented on putting_rl_back_in_rlhf_with_rloo.md
> +Second, RLOO uses the REINFORCE loss, which basically multiplies the (reward - baseline) by the logprob of actions. Here we highlight the differences between per-token REINFORCE loss and the entire c
```suggestion
Second, RLOO uses the REINFORCE loss, which basically multiplies the (reward - baseline) by the logprob of actions. Here, we highlight the differences between the per-token REINFORCE loss and the entire completion REINFORCE loss. Note that for PPO's loss, we would need to calculate the advantage additionally based on the value model with
```

2024-06-11 21:00 UTC, osanseviero commented on putting_rl_back_in_rlhf_with_rloo.md
> +# ... continue from above
Maybe you could have all the code in a minimal notebook as well for people to run it easily?

2024-06-11 21:00 UTC, osanseviero commented on putting_rl_back_in_rlhf_with_rloo.md
> +To get started with RLOO, you can install the latest version of of TRL via `pip install --upgrade trl` and import the RLOOTrainer. Below is a short snippet that shows some high-level API usage. Feel
```suggestion
To get started with RLOO, you can install the latest version of TRL via `pip install --upgrade trl` and import the RLOOTrainer. Below is a short snippet that shows some high-level API usage. Feel free to checkout the documentation 
```

2024-06-11 21:00 UTC, osanseviero commented on putting_rl_back_in_rlhf_with_rloo.md
> +```pythonfrom transformers import (
```suggestion
```python
from transformers import (
```

2024-06-11 21:00 UTC, osanseviero commented on putting_rl_back_in_rlhf_with_rloo.md
> +
```suggestion
```

2024-06-11 21:00 UTC, osanseviero commented on putting_rl_back_in_rlhf_with_rloo.md
> +We take the SFT / RM models directly from ([https://arxiv.org/pdf/2403.17031](https://arxiv.org/pdf/2403.17031)). To evaluate, we use vLLM to load the checkpoints and GPT4 as a judge model to assess
Avoid putting links to PDFs. Either put the arxiv abs page or link to the actual models/collection

2024-06-11 21:00 UTC, osanseviero commented on putting_rl_back_in_rlhf_with_rloo.md
> +Despite the performance and compute efficiency advantages of RLOO, we want to highlight some numerical issues. Specifically, the response logprobs obtained during generation are slightly numerically
```suggestion
Despite RLOO's performance and compute efficiency advantages, we want to highlight some numerical issues. Specifically, the response logprobs obtained during generation are slightly numerically different from the logprobs obtained during the training forward passes under `bf16`. This causes an issue for both PPO and RLOO, but it’s much worse for RLOO, as explained below.
```

2024-06-11 21:00 UTC, osanseviero commented on putting_rl_back_in_rlhf_with_rloo.md
> +Note that the ratio for `bf16` is very unstable for some reason. When ratio becomes large, PPO’s clip coefficient = 0.2 kicks in, **nulling** the gradient of the tokens for which the ratio is greater
```suggestion
Note that the ratio for `bf16` is very unstable for some reason. When the ratio becomes large, PPO’s clip coefficient = 0.2 kicks in, **nulling** the gradient of the tokens for which the ratio is greater than 1.2 or lower than 0.8. With RLOO, this issue is more extreme because we are looking at the `(forward_logprob.sum(1) - generation_logprob.sum(1)).exp() = [ 1.0625, 12.1875]`, which means the gradient for the entire second sequence is nulled. 
```

2024-06-11 21:00 UTC, osanseviero commented on putting_rl_back_in_rlhf_with_rloo.md
> +In practice, we noticed PPO nulls the gradient of approximately 3% of the batch data, whereas RLOO nulls about 20-40% of the batch data. Theoretically, RLOO should null 0% of the batch data, when not
```suggestion
In practice, we noticed PPO nulls the gradient of approximately 3% of the batch data, whereas RLOO nulls about 20-40% of the batch data. Theoretically, RLOO should null 0% of the batch data when not using mini-batches. Importantly, we observe that the clipping ratio for RLOO did not change significantly once we increased the number of gradient steps before generating new batches (through num_ppo_epochs and num_mini_batches); this provides empirical evidence that the clipping ratio is indeed due to numerical issues with bf16 as opposed to the behavior and latest policies being significantly different, as positioned in the paper. 
```

2024-06-11 22:04 UTC, vwxyzjn commented on putting_rl_back_in_rlhf_with_rloo.md
> +Second, RLOO uses the REINFORCE loss, which basically multiplies the (reward - baseline) by the logprob of actions. Here we highlight the differences between per-token REINFORCE loss and the entire c
Clarified more.

2024-06-11 22:05 UTC, vwxyzjn commented
Great! Thanks for the review! I will merge it tomorrow morning

2024-06-12 07:55 UTC, osanseviero requested changes
I think there are many missing things that were marked as resolved. Is a push missing?

2024-06-12 13:33 UTC, vwxyzjn commented
@osanseviero I am not sure what happened but they are fixed! Thanks for the catch!!!

2024-06-12 13:46 UTC, osanseviero approved these changes
LGTM!

2024-06-12 14:00 UTC, vwxyzjn commented
Merging! Thanks everyone for the feedback

2024-06-12 14:00 UTC, merged