Add dibt-overview blog post
huggingface/blog pull request #2150
Opened 2024-06-18 12:28 UTC by sdiazlor

2024-06-18 12:55 UTC, davanstrien requested changes
Just a few small nits :)

2024-06-18 12:55 UTC, davanstrien commented on dibt-overview.md
> +For the past few months, we have been working on the [Data Is Better Together](https://github.com/huggingface/data-is-better-together) initiative. With this collaboration between Hugging Face and  Ar
```suggestion
For the past few months, we have been working on the [Data Is Better Together](https://github.com/huggingface/data-is-better-together) initiative. With this collaboration between Hugging Face and Argilla and the support of the open-source ML community, our goal has been to empower the open-source community to create impactful datasets collectively.
```

2024-06-18 12:55 UTC, davanstrien commented on dibt-overview.md
> +Now, we have decided to move forward to explore new possibilities while always keeping our main goal in mind. To provide a clear overview of our achievements and the tasks where everyone can still co
```suggestion
Now, we have decided to move forward to explore new possibilities while always keeping our main goal in mind. To provide a clear overview of our achievements and the tasks to which everyone can still contribute, we have organized this into two sections: community efforts and cookbook efforts.
```

2024-06-19 08:22 UTC, osanseviero reviewed
Looking nice!

2024-06-19 08:55 UTC, pcuenca reviewed
metadata nits

2024-06-19 08:55 UTC, pcuenca commented on _blog.yml
> +  guest: true
```suggestion
```

I guess :)

2024-06-19 08:55 UTC, pcuenca commented on _blog.yml
> +  date: Jun 18, 2024
Reminder to update

2024-06-20 09:30 UTC, davanstrien approved these changes

2024-06-20 09:30 UTC, davanstrien commented on _blog.yml
> +  date: Jun 19, 2024
```suggestion
  date: Jun 20, 2024
```

2024-06-20 09:30 UTC, davanstrien commented
@sdiazlor I think we just need to update the date and then we can publish this :)

2024-06-20 10:16 UTC, sdiazlor commented
@davanstrien Great! You can merge then; I don't have the rights.

2024-06-20 10:28 UTC, merged