[DRAFT]: OpenVINO Gen.AI post
huggingface/blog pull request #2291
Opened 2024-08-12 11:01 UTC by AlexKoff88

2024-08-12 11:27 UTC, yury-gorbachev requested changes

2024-08-12 11:27 UTC, yury-gorbachev commented on deploy-with-openvino.md
> +The export with the former option looks as follows:
Perhaps it makes sense to show how to install Optimum-intel?

2024-08-12 11:27 UTC, yury-gorbachev commented on deploy-with-openvino.md
> +To export 🤗 Transformers model to OpenVINO IR one case use two options: `.from_pretrained()` API method of the Optimum-Intel class or the command-line interface (CLI).
"OpenVINO IR one case use two options"-this is somewhat confusing sentence.  Also you write two options, but show one here and then later write "Alternatively," - which is not entirely fitting the style.

2024-08-12 11:27 UTC, yury-gorbachev commented on deploy-with-openvino.md
> +The `./llam-3.1-8b-ov` folder will contain `.xml` and `bin` IR model files and required configuration files that come from the source model. If `openvino-tokenizers` library is installed the export p
Will openvino-tokenizers be installed by default? I think so, maybe we should not mention this installation alternative and just say that tokenizers will also be converted?

2024-08-12 11:27 UTC, yury-gorbachev commented on deploy-with-openvino.md
> +Recently, OpenVINO introduced [Generative AI (Gen.AI) API](https://docs.openvino.ai/2024/learn-openvino/llm_inference_guide/genai-guide.html) designed to simplify integration of Generative AI model i
Should we mention that OpenVINO Tokenizers is "c++/footprint friendly implementation"?

2024-08-12 11:27 UTC, yury-gorbachev commented on deploy-with-openvino.md
> +Model optimization is a mandatory step when it comes to LLM deployment. And weight-only quantization is a mainstream approach that significantly reduces latency and model footprint. Optimum-Intel pro
I suggest to rephrase to "When running LLMs on the resource constrained edge and client devices, model optimization is highly recommended step"

2024-08-12 11:27 UTC, yury-gorbachev commented on deploy-with-openvino.md
> +For `meta-llama/Meta-Llama-3.1-8B` model we recommend stacking AWQ, quantization scale estimation along with mixed-precision INT4/INT8 quantization of weights using a calibration dataset that reflect
Is it possible to give links to pages that describe AWQ and other methods? Just to make it more information reach...

2024-08-12 11:27 UTC, yury-gorbachev commented on deploy-with-openvino.md
> +In this part, we will show how to run an optimized model with OpenVINO Gen.AI C++ API. The Gen.AI API is designed to be intuitive and provides a seamless migration from 🤗 Transformers API. The basic
"In this part"->"Now, when we have successfully converted and optimized our model, let's see how to run it using OpenVINO Gen.AI C++ API"

2024-08-12 11:27 UTC, yury-gorbachev commented on deploy-with-openvino.md
> +model.save_pretrained("./llam-3.1-8b-ov")
why llam?

2024-08-12 11:27 UTC, yury-gorbachev commented on deploy-with-openvino.md
> +`LLMPipeline` also allows specifying custom generation options by means of `ov::genai::GenerationConfig`. It also supports streaming and chat scenarios as well as Beam Search. You can find more detai
I would suggest adding at least one more example, for instance with streamer to indicate interactive output for generation. It will not add to the paper much, but will show additional capabilities very well.

2024-08-12 11:27 UTC, yury-gorbachev commented on deploy-with-openvino.md
> +
Could we mention that same code could use "GPU" as target device for integrated and discrete GPUs?  i.e. only device name change is required to switch between devices...

2024-08-12 13:11 UTC, AlexKoff88 commented on deploy-with-openvino.md
> +The export with the former option looks as follows:
done

2024-08-12 13:11 UTC, AlexKoff88 commented on deploy-with-openvino.md
> +The `./llam-3.1-8b-ov` folder will contain `.xml` and `bin` IR model files and required configuration files that come from the source model. If `openvino-tokenizers` library is installed the export p
done

2024-08-12 13:11 UTC, AlexKoff88 commented on deploy-with-openvino.md
> +To export 🤗 Transformers model to OpenVINO IR one case use two options: `.from_pretrained()` API method of the Optimum-Intel class or the command-line interface (CLI).
done

2024-08-12 13:11 UTC, AlexKoff88 commented on deploy-with-openvino.md
> +Model optimization is a mandatory step when it comes to LLM deployment. And weight-only quantization is a mainstream approach that significantly reduces latency and model footprint. Optimum-Intel pro
done

2024-08-12 13:12 UTC, AlexKoff88 commented on deploy-with-openvino.md
> +For `meta-llama/Meta-Llama-3.1-8B` model we recommend stacking AWQ, quantization scale estimation along with mixed-precision INT4/INT8 quantization of weights using a calibration dataset that reflect
done

2024-08-12 13:12 UTC, AlexKoff88 commented on deploy-with-openvino.md
> +model.save_pretrained("./llam-3.1-8b-ov")
done

2024-08-12 13:12 UTC, AlexKoff88 commented on deploy-with-openvino.md
> +`LLMPipeline` also allows specifying custom generation options by means of `ov::genai::GenerationConfig`. It also supports streaming and chat scenarios as well as Beam Search. You can find more detai
done

2024-08-12 13:12 UTC, AlexKoff88 commented on deploy-with-openvino.md
> +In this part, we will show how to run an optimized model with OpenVINO Gen.AI C++ API. The Gen.AI API is designed to be intuitive and provides a seamless migration from 🤗 Transformers API. The basic
done

2024-08-12 13:12 UTC, AlexKoff88 commented on deploy-with-openvino.md
> +Recently, OpenVINO introduced [Generative AI (Gen.AI) API](https://docs.openvino.ai/2024/learn-openvino/llm_inference_guide/genai-guide.html) designed to simplify integration of Generative AI model i
done

2024-08-13 16:39 UTC, jeffboudier commented on deploy-with-openvino.md
> +  guest: true
```suggestion
- user: AlexKoff88
  guest: true
  org: Intel
```

Please add the organization to guest authors for attribution, it will show on the blog post nicely

2024-08-13 21:43 UTC, raymondlo84 commented on deploy-with-openvino.md
> +
https://gist.github.com/helena-intel/0acef0ce3342cb26cc4311f612991e59

I tested Helena's instruction here, and I managed to get the chat_sample running! This is pretty awesome indeed. 

![IMG_2267](https://github.com/user-attachments/assets/9c9b3fdb-50be-49d7-9018-fd8fbcde1df7)

2024-08-14 09:56 UTC, AlexKoff88 commented on deploy-with-openvino.md
> +  guest: true
done

2024-08-14 09:56 UTC, AlexKoff88 commented on deploy-with-openvino.md
> +
added

2024-08-14 11:35 UTC, AlexKoff88 commented on deploy-with-openvino.md
> +`LLMPipeline` also allows specifying custom generation options by means of `ov::genai::GenerationConfig`. It also supports streaming and chat scenarios as well as Beam Search. You can find more detai
Added

2024-08-23 05:34 UTC, yeonbok commented on deploy-with-openvino.md
> +model.save_pretrained("./llam-3.1-8b-ov")
There are still "llama-3.1-8b-ov"s :)

2024-08-27 17:10 UTC, echarlaix commented on deploy-with-openvino.md
> +When running LLMs on the resource constrained edge and client devices, model optimization is highly recommended step. And weight-only quantization is a mainstream approach that significantly reduces
```suggestion
When running LLMs on resource constrained edge and client devices, model optimization is a highly recommended step. And weight-only quantization is a mainstream approach that can significantly reduce the latency and model footprint. Optimum Intel provides weight-only quantization capabilities by means of NNCF which has a variety of optimization techniques designed specifically for LLMs: from data-free INT8 and INT4 weight quantization to data-aware methods such as [AWQ](https://huggingface.co/docs/transformers/main/en/quantization/awq), [GPTQ](https://huggingface.co/docs/transformers/main/en/quantization/gptq), quantization scale estimation, mixed-precision quantization.
```

2024-08-27 17:31 UTC, echarlaix commented on deploy-with-openvino.md
> +By default, weights of the models that are larger than one billion parameters are quantized to INT8 precision which is safe in terms of accuracy. It means that the export steps described above lead t
not sure "safe in terms of accuracy" is adapted as it could lead to accuracy degradation in some cases, what abut something like  
```suggestion
By default, weights of the models that are larger than one billion parameters are quantized to INT8 precision which doesn't impact negatively accuracy in most cases. It means that the export steps described above lead to the model with 8-bit weights. However, 4-bit integer weight-only quantization allows achieving a better accuracy-performance trade-off. 
```

2024-08-27 17:31 UTC, echarlaix commented on deploy-with-openvino.md
> +By default, weights of the models that are larger than one billion parameters are quantized to INT8 precision which is safe in terms of accuracy. It means that the export steps described above lead t
Not sure to get the "However, 4-bit integer weight-only quantization allows achieving a better accuracy-performance trade-off." sentence

2024-08-27 17:31 UTC, echarlaix commented on deploy-with-openvino.md
> +- user: sayakpaul
not sure if done intentionally I imagine this is coming from https://github.com/huggingface/blog/blob/197124cb7e56ea06d6d947a32b33fff977589442/train-optimize-sd-intel.md?plain=1#L4-L12

2024-08-27 17:31 UTC, echarlaix commented on deploy-with-openvino.md
> +```pythonTransformers
```suggestion
```python
```

2024-09-02 06:24 UTC, AlexKoff88 commented on deploy-with-openvino.md
> +- optimum-intel==1.20
thanks for the finding,  fixed

2024-09-02 06:24 UTC, AlexKoff88 commented on deploy-with-openvino.md
> +quantization_config = OVWeightQuantizationConfig(awq=True, scale_estimation=True, group_size=64, dataset="c4")
thanks for the finding, fixed

2024-09-02 06:31 UTC, AlexKoff88 commented on deploy-with-openvino.md
> +- user: sayakpaul
you are right. What is wrong with that?

2024-09-05 17:12 UTC, echarlaix commented on deploy-with-openvino.md
> +optimum-cli export openvino -m meta-llama/Meta-Llama-3.1-8B ./llam-3.1-8b-ov
```suggestion
optimum-cli export openvino -m meta-llama/Meta-Llama-3.1-8B ./llama-3.1-8b-ov
```

2024-09-05 17:12 UTC, echarlaix commented on deploy-with-openvino.md
> +model.save_pretrained("./llam-3.1-8b-ov")
```suggestion
model.save_pretrained("./llama-3.1-8b-ov")
```

2024-09-05 17:12 UTC, echarlaix commented on deploy-with-openvino.md
> +optimum-cli export openvino -m meta-llama/Meta-Llama-3.1-8B --weight-format int4 --awq --scale-estimation --group-size 64 --dataset wikitext2 ./llam-3.1-8b-ov
```suggestion
optimum-cli export openvino -m meta-llama/Meta-Llama-3.1-8B --weight-format int4 --awq --scale-estimation --group-size 64 --dataset wikitext2 ./llama-3.1-8b-ov
```

2024-09-05 17:13 UTC, echarlaix commented on deploy-with-openvino.md
> +# Optimize and deploy HuggingFace (🤗) Transformer models with Optimum-Intel and OpenVINO GenAI
here we are talking about the library so should Transformers

```suggestion
# Optimize and deploy HuggingFace (🤗) Transformers models with Optimum-Intel and OpenVINO GenAI
```

2024-09-05 17:16 UTC, echarlaix commented on deploy-with-openvino.md
> +title: Optimize and deploy 🤗 Transformer models with Optimum-Intel and OpenVINO GenAI
needs to be added to https://github.com/huggingface/blog/blob/main/_blog.yml#L4621 before merging

2024-09-05 17:35 UTC, echarlaix commented on deploy-with-openvino.md
> +- user: sayakpaul
OK so we need to have @sayakpaul as a reviewer then

2024-09-05 20:24 UTC, jeffboudier commented on deploy-with-openvino.md
> +title: Optimize and deploy 🤗 Transformer models with Optimum-Intel and OpenVINO GenAI
```suggestion
title: Optimize and deploy with Optimum-Intel and OpenVINO GenAI
```
we try to keep titles short

2024-09-05 20:26 UTC, jeffboudier commented on deploy-with-openvino.md
> +# Optimize and deploy HuggingFace (🤗) Transformer models with Optimum-Intel and OpenVINO GenAI
```suggestion
# Optimize and deploy models with Optimum-Intel and OpenVINO GenAI
```

2024-09-06 06:58 UTC, AlexKoff88 commented on deploy-with-openvino.md
> +title: Optimize and deploy 🤗 Transformer models with Optimum-Intel and OpenVINO GenAI
done

2024-09-06 12:48 UTC, echarlaix commented on deploy-with-openvino.md
> +- user: sayakpaul
```suggestion
```
cc @sayakpaul

2024-09-06 12:50 UTC, echarlaix commented on _blog.yml
> +  title: "Optimize and deploy 🤗 Transformer models with Optimum-Intel and OpenVINO GenAI"
```suggestion
  title: "Optimize and deploy models with Optimum-Intel and OpenVINO GenAI"
```

2024-09-06 12:58 UTC, echarlaix commented on _blog.yml
> +- local: openvino-genai
```suggestion
- local: deploy-with-openvino
```

2024-09-06 18:10 UTC, jeffboudier commented on deploy-with-openvino.md
> +© Intel Corporation. Intel, the Intel logo, and other Intel marks are trademarks of Intel Corporation or its subsidiaries. Other names and brands may be claimed as the property of others.
Do we need this? This is published on HF blog so this feels unnecessary.

2024-09-06 18:12 UTC, jeffboudier commented on deploy-with-openvino.md
> +Raymond Lo, currently based in Silicon Valley, is the global lead of Intel's AI evangelist team, focusing on the OpenVINO™ Toolkit. With a diverse background that includes founding the augmented real
Adding an author bio is atypical for HF blogs. The blog post header has clickable links to the authors Hugging Face profile. This information would be most helpful on a HF user profile.

2024-09-09 08:13 UTC, echarlaix commented on deploy-with-openvino.md
> +4. [Jupyter Notebooks] (https://docs.openvino.ai/2024/learn-openvino/interactive-tutorials-python.html)
```suggestion
3. [OpenVINO Documentation](docs.openvino.ai)
4. [Jupyter Notebooks](https://docs.openvino.ai/2024/learn-openvino/interactive-tutorials-python.html)
5. [Optimum Documentation](https://huggingface.co/docs/optimum/main/en/intel/index)
```

2024-09-09 09:16 UTC, AlexKoff88 commented on deploy-with-openvino.md
> +© Intel Corporation. Intel, the Intel logo, and other Intel marks are trademarks of Intel Corporation or its subsidiaries. Other names and brands may be claimed as the property of others.
@malusos, please take a look

2024-09-09 09:43 UTC, AlexKoff88 commented on deploy-with-openvino.md
> +Raymond Lo, currently based in Silicon Valley, is the global lead of Intel's AI evangelist team, focusing on the OpenVINO™ Toolkit. With a diverse background that includes founding the augmented real
Added bio into my profile on the Hub

2024-09-09 15:07 UTC, echarlaix commented on deploy-with-openvino.md
> +Raymond Lo, currently based in Silicon Valley, is the global lead of Intel's AI evangelist team, focusing on the OpenVINO™ Toolkit. With a diverse background that includes founding the augmented real
removing 
```suggestion
```

2024-09-12 11:48 UTC, AlexKoff88 commented on deploy-with-openvino.md
> +© Intel Corporation. Intel, the Intel logo, and other Intel marks are trademarks of Intel Corporation or its subsidiaries. Other names and brands may be claimed as the property of others.
resolved

2024-09-12 11:48 UTC, AlexKoff88 commented
@echarlaix, @jeffboudier, can we proceed with publication?

2024-09-13 12:33 UTC, echarlaix commented on _blog.yml
> +    - hub
```suggestion
  date: September 13, 2024
  tags:
    - intel
    - optimum
    - quantization
    - inference
```

2024-09-13 12:34 UTC, echarlaix approved these changes

2024-09-13 12:38 UTC, echarlaix commented
> @echarlaix, @jeffboudier, can we proceed with publication?

Works for me, when would you like to have it published?

2024-09-13 12:43 UTC, echarlaix commented on deploy-with-openvino.md
> +To export Transformer models to OpenVINO Intermediate Representation (IR) one can use two options: This can be done using Python’s `.from_pretrained()` method or the Optimum command-line interface (C
```suggestion
To export Transformers models to OpenVINO Intermediate Representation (IR) one can use two options: This can be done using Python’s `.from_pretrained()` method or the Optimum command-line interface (CLI). Below are examples using both methods:
```

2024-09-20 06:19 UTC, AlexKoff88 commented
@echarlaix, @jeffboudier, can we finally publish this?

2024-09-20 08:18 UTC, echarlaix commented
> @echarlaix, @jeffboudier, can we finally publish this?

Yes, do you want it to be published today or beginning of next week @AlexKoff88 ?

2024-09-20 10:02 UTC, echarlaix commented on _blog.yml
> +  date: September 13, 2024
```suggestion
  date: September 20, 2024
```

2024-09-20 12:39 UTC, echarlaix commented on deploy-with-openvino.md
> +![OpenVINO GenAI C++ chat demo](/blog/assets/deploy-with-openvino/demo.gif "OpenVINO GenAI C++ chat demo")
```suggestion
![OpenVINO GenAI C++ chat demo](https://huggingface.co/datasets/OpenVINO/documentation/resolve/main/blog/openvino_genai_workflow/demo.gif)
```

2024-09-20 15:48 UTC, merged

2024-09-20 19:03 UTC, jeffboudier commented
Thanks @echarlaix ! Congrats @AlexKoff88 
The thumbnail is a very busy visual, gets cropped. @AlexKoff88 I would recommend creating a more compelling visual and updating the post in a follow up PR

2024-09-21 05:48 UTC, AlexKoff88 commented
> Thanks @echarlaix ! Congrats @AlexKoff88 The thumbnail is a very busy visual, gets cropped. @AlexKoff88 I would recommend creating a more compelling visual and updating the post in a follow up PR

Sure, I will update it.

2024-09-23 06:47 UTC, AlexKoff88 commented
> Thanks @echarlaix ! Congrats @AlexKoff88 The thumbnail is a very busy visual, gets cropped. @AlexKoff88 I would recommend creating a more compelling visual and updating the post in a follow up PR

@jeffboudier, @echarlaix, I've updated the image in the PR #2356. Please check and merge.