feat: add protect ai partnership blog post
huggingface/blog pull request #2422
Opened 2024-10-21 16:28 UTC by McPatate

2024-10-21 16:45 UTC, julien-c commented on protectai-partnership.md
for filename you can do just `protectai`

2024-10-21 19:41 UTC, chrisking commented on protectai.md
> +To share models, we serialize the data structures we use to interact with the models, in order to facilitate storage and transport. Some serialization formats are vulnerable to nasty exploits, such a
Love the shame directed at pickle.

2024-10-21 19:43 UTC, chrisking commented on protectai.md
> +As Hugging Face has become the de facto platform for model sharing, we’d like to protect the community from this, hence why we have developed tools like [picklescan](https://github.com/mmaitre314/pic
alt: we'd like to protect our community from this, 

This way it implies ownership and engagement with the HF community overall.

2024-10-21 19:44 UTC, chrisking commented on protectai.md
> +Pickle is not the only exploitable format out there, [see for reference](https://github.com/Azure/counterfit/wiki/Abusing-ML-model-file-formats-to-create-malware-on-AI-systems:-A-proof-of-concept) ho
catches both of these exploits and more!

2024-10-21 20:59 UTC, seanpmorgan requested changes

2024-10-21 20:59 UTC, seanpmorgan commented on protectai.md
> +Pickle is not the only exploitable format out there, [see for reference](https://github.com/Azure/counterfit/wiki/Abusing-ML-model-file-formats-to-create-malware-on-AI-systems:-A-proof-of-concept) ho
```suggestion
Pickle is not the only exploitable format out there, [see for reference](https://github.com/Azure/counterfit/wiki/Abusing-ML-model-file-formats-to-create-malware-on-AI-systems:-A-proof-of-concept) how one can exploit Keras Lambda layers to achieve arbitrary code execution. The good news is that Guardian catches both of these exploits and more in additional file formats! See their [Knowledge Base](https://insights-db.protectai.dev/insights/knowledge-base/) for up to date scanner information.
```

2024-10-22 09:31 UTC, julien-c reviewed
reminder that you need to link from _blog.yml @McPatate

2024-10-22 12:11 UTC, pcuenca commented on protectai.md
> +Note that you might not see a scan for your model as of today, as we have over 1 million model repos, it may take some time to catch up.
```suggestion
Note that you might not see a scan for your model as of today, as we have over 1 million model repos. It may take us some time to catch up 😅.
```

2024-10-22 12:12 UTC, pcuenca commented on protectai.md
> +[Protect AI](https://protectai.com/) is a company founded with a mission to create a safer AI powered world. They are developing powerful tools, namely [Guardian](https://protectai.com/guardian), to
```suggestion
[Protect AI](https://protectai.com/) is a company founded with a mission to create a safer AI-powered world. They are developing powerful tools, namely [Guardian](https://protectai.com/guardian), to ensure that the rapid pace of AI innovation can continue without compromising security.
```

2024-10-22 12:15 UTC, pcuenca commented on protectai.md
> +thumbnail: /blog/assets/protectai-partnership/thumbnail.png
```suggestion
thumbnail: /blog/assets/protectai/thumbnail.png
```

2024-10-22 12:17 UTC, McPatate commented on protectai.md
> +thumbnail: /blog/assets/protectai-partnership/thumbnail.png
ah good catch, thought I'd done it

2024-10-22 12:19 UTC, McPatate commented on protectai.md
> +Our decision to partner with Protect AI stems from their [community driven](https://huntr.com/) approach to security, active support of [open source](https://github.com/protectai) and expertise in al
Sorry about the commas, I keep missing them, French be damned!

2024-10-25 15:31 UTC, merged