Can LLMs fix their mistakes? A chatbot arena experiment with Keras and TPUs.
huggingface/blog pull request #2503
Opened 2024-11-29 12:09 UTC by martin-gorner

The companion Space for this blog post is here: [Keras Chatbot Arena](https://huggingface.co/spaces/huggingface/keras-chatbot-battle)

2024-11-29 13:29 UTC, andimarafioti requested changes

2024-11-29 13:29 UTC, andimarafioti commented on keras-chatbot-arena.md
> +[![screenshot](assets/keras-chatbot-arena/screenshot.png)](https://huggingface.co/spaces/huggingface/keras-chatbot-battle)
We shouldn't upload images to this repo (only the thumbnail!). Otherwise it will be huge. Please upload the image to: https://huggingface.co/datasets/huggingface/documentation-images

2024-11-29 13:29 UTC, burtenshaw commented on keras-chatbot-arena.md
> +I'm not interested in having LLMs solve big problems, quite the opposite. I want them to dispatch drudgery, and if they don't get it right
This is a cool sentence and it makes the post fun to read, but I would start of with 1 or 2 sentences that say something like "In this blog post we will...". Just to help out the less caffeinated readers.

2024-11-29 13:31 UTC, tomaarsen commented on keras-chatbot-arena.md
> +I'm not interested in having LLMs solve big problems, quite the opposite. I want them to dispatch drudgery, and if they don't get it right
The easiest way to keep both is to add a TL;DR before your introduction, e.g. in https://huggingface.co/blog/smolvlm

2024-11-29 13:33 UTC, andimarafioti requested changes
Some errors with format and several TODOs left.

2024-11-29 13:33 UTC, andimarafioti commented on keras-chatbot-arena.md
> +# Can LLMs fix their mistakes?
You need to follow a template here to add a title and the thumbnail and authors, check the other blog entries

2024-11-29 13:33 UTC, andimarafioti commented on keras-chatbot-arena.md
> +[computers](https://en.wikipedia.org/wiki/HAL_9000) in old sci-fi movies, minus the "[I'm sorry Dave, I'm afraid I can't do that](https://youtu.be/ARJ8cAGm6JE?si=LnI39hH7EhiXunw6)" bit 😅.
very cool intro

2024-11-29 13:49 UTC, martin-gorner commented on keras-chatbot-arena.md
> +
on Hugging Face spaces!

2024-11-29 13:54 UTC, martin-gorner commented on keras-chatbot-arena.md
> +[![screenshot](assets/keras-chatbot-arena/screenshot.png)](https://huggingface.co/spaces/huggingface/keras-chatbot-battle)
ack - I'll fix it

2024-11-29 13:55 UTC, martin-gorner commented on keras-chatbot-arena.md
> +# Can LLMs fix their mistakes?
done

2024-11-29 14:14 UTC, tengomucho commented on keras-chatbot-arena.md
> +on the first try, a short English sentence should be enough to fix it. In short, I want an asistant, like the
typo: assistant

2024-11-29 14:21 UTC, tengomucho commented on keras-chatbot-arena.md
> +For their fast inference and large memory. A TPU v5e 2x4 has 8 cores and 48GB of RAM per core for an aggregate 384GB of memory. With this
each core has 16GB of RAM, for an aggregate of 128GB (source: https://cloud.google.com/tpu/docs/v5e)

2024-11-29 14:23 UTC, tengomucho commented on keras-chatbot-arena.md
> +And yes, debugging and a few layout map adjustments [were necessary](https://huggingface.co/spaces/huggingface/keras-chatbot-battle/blob/c16851db4f6aaac90c2d06d8bdb06890a86e24e7/models.py#L34).
are you sure about this link? it goes 404 for me.

2024-11-29 14:26 UTC, tengomucho commented on keras-chatbot-arena.md
> +I did not know what to expect before starting this test. The API the models were plaing with is unrealistically simple. Just 2 API calls 'add_calendar_entry'
plaing -> playing

2024-11-29 14:36 UTC, martin-gorner commented on keras-chatbot-arena.md
> +For their fast inference and large memory. A TPU v5e 2x4 has 8 cores and 48GB of RAM per core for an aggregate 384GB of memory. With this
fixed - I copied this from the wrong page 😓

2024-11-29 14:37 UTC, martin-gorner commented on keras-chatbot-arena.md
> +[computers](https://en.wikipedia.org/wiki/HAL_9000) in old sci-fi movies, minus the "[I'm sorry Dave, I'm afraid I can't do that](https://youtu.be/ARJ8cAGm6JE?si=LnI39hH7EhiXunw6)" bit 😅.
Thx!

2024-11-29 14:45 UTC, martin-gorner commented
> What's potentially missing (but given previous point, it can be in another post) is more **details on Spaces TPUs** i.e. what's the setup, how many models / params can you load, response times IMO

I can add that the TPU had enough RAM for loading five 8B-ish models (+multiple smaller ones) in bfloat16 format. It would OOM on the sixth.

2024-11-29 20:57 UTC, julien-c commented
> I can add that the TPU had enough RAM for loading five 8B-ish models (+multiple smaller ones) in bfloat16 format. It would OOM on the sixth.

yes that's great info – either in this blog or we could do a short follow up focused on Spaces TPUs, up to you

2024-12-02 15:56 UTC, martin-gorner commented
I'm surprised that none of the reviewers here asked for SmallLM2 to be included in this comparison? There might be some work in getting it to play nice with Keras, but it may be manageable if it uses one of the "standard" architectures like Llama.

2024-12-02 20:29 UTC, tengomucho commented
I think SmolLM2 is indeed a llama compatible model, cf. the [config](https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct/blob/main/config.json#L15).

2024-12-03 11:50 UTC, martin-gorner commented on keras-chatbot-arena.md
> +I'm not interested in having LLMs solve big problems, quite the opposite. I want them to dispatch drudgery, and if they don't get it right
2 other reviewers like the intro so keeping this as is. I think that the title works as a TL;DR.

2024-12-03 11:51 UTC, martin-gorner commented on keras-chatbot-arena.md
> +[computers](https://en.wikipedia.org/wiki/HAL_9000) in old sci-fi movies, minus the "[I'm sorry Dave, I'm afraid I can't do that](https://youtu.be/ARJ8cAGm6JE?si=LnI39hH7EhiXunw6)" bit 😅.
fixed

2024-12-03 11:51 UTC, martin-gorner commented on keras-chatbot-arena.md
> +**[TODO] insert links to full conversation transcripts**
fixed

2024-12-03 13:31 UTC, martin-gorner commented on keras-chatbot-arena.md
> +[![screenshot](assets/keras-chatbot-arena/screenshot.png)](https://huggingface.co/spaces/huggingface/keras-chatbot-battle)
done

2024-12-04 13:14 UTC, andimarafioti approved these changes
didn't re-review but I trust that it's good. Please do rebase before merging such that the image doesn't stay in the git history 
<img src="https://media1.giphy.com/media/2dQ3FMaMFccpi/giphy.gif"/>

2024-12-05 15:59 UTC, merged