Create Students’ Ambassadors Program
huggingface/blog pull request #267
Opened 2022-04-13 10:11 UTC by VioletteLepercq

2022-04-13 16:49 UTC, NimaBoscarino reviewed
So excited for the student ambassador program to take off! I think people are going to love this 😄

2022-04-13 16:49 UTC, NimaBoscarino commented on Students’ Ambassadors Program
> +# 🤗 **Students’ Ambassadors Program call for applications is open!**
If the file gets renamed to something like `student-ambassador-program.md` then the Markdown will render nicely in GitHub.

2022-04-13 16:49 UTC, NimaBoscarino commented on Students’ Ambassadors Program
> +*As an Open Source company democratizing Machine Learning, Hugging Face believes it is essential to* [educate](https://www.notion.so/About-Hugging-Face-for-Education-afca12e2bc7c4e1ea9346ef2306a0a69)
Not sure about the `*`'s in this line. Are they emphasizing items?

2022-04-13 16:49 UTC, NimaBoscarino commented on Students’ Ambassadors Program
> +- Acknowledge the [Code of Conduct](https://docs.google.com/document/d/1D-HtACsgPjh3qfeueqkgUr2jMipaP_JsLTYydbEuG2c/edit)**.** Community is at the center of the Hugging Face ecosystem. Because of tha
```suggestion
- Acknowledge the [Code of Conduct](https://docs.google.com/document/d/1D-HtACsgPjh3qfeueqkgUr2jMipaP_JsLTYydbEuG2c/edit). Community is at the center of the Hugging Face ecosystem. Because of that, we strictly adhere to our [Code of conduct](https://docs.google.com/document/d/1D-HtACsgPjh3qfeueqkgUr2jMipaP_JsLTYydbEuG2c/edit#). If any ambassador infringes it or behaves inadequately, they will be excluded from the Program.
```

2022-04-13 16:49 UTC, NimaBoscarino commented on Students’ Ambassadors Program
> +- Acknowledge the [Code of Conduct](https://docs.google.com/document/d/1D-HtACsgPjh3qfeueqkgUr2jMipaP_JsLTYydbEuG2c/edit)**.** Community is at the center of the Hugging Face ecosystem. Because of tha
Heads up that the Code of Conduct is being linked with edit permissions, so even in incognito mode I'm able to make changes to it.

2022-04-13 16:49 UTC, NimaBoscarino commented on Students’ Ambassadors Program
> +- Agreement with the [Program Code of Conduct](https://docs.google.com/document/d/1D-HtACsgPjh3qfeueqkgUr2jMipaP_JsLTYydbEuG2c/edit).
Same permissions issue with the Google Doc here (edit for all)

2022-04-14 08:13 UTC, VioletteLepercq commented on Students’ Ambassadors Program
> +# 🤗 **Students’ Ambassadors Program call for applications is open!**
I agree. Will change that :)

2022-04-14 08:15 UTC, VioletteLepercq commented on Students’ Ambassadors Program
> +- Acknowledge the [Code of Conduct](https://docs.google.com/document/d/1D-HtACsgPjh3qfeueqkgUr2jMipaP_JsLTYydbEuG2c/edit)**.** Community is at the center of the Hugging Face ecosystem. Because of tha
The code of conduct should also be added to a blog post, so the final link will not be this one

2022-04-14 08:16 UTC, VioletteLepercq commented on Students’ Ambassadors Program
> +- Agreement with the [Program Code of Conduct](https://docs.google.com/document/d/1D-HtACsgPjh3qfeueqkgUr2jMipaP_JsLTYydbEuG2c/edit).
same comment

2022-04-14 08:16 UTC, VioletteLepercq commented on Students’ Ambassadors Program
> +- A motivation letter that should include the following information:
you are right. I will propose a size :-)

2022-04-14 14:48 UTC, merveenoyan commented on Students’ Ambassadors Program
> +    - What are some of your ideas for campus/local community building and evangelization (the more creative the better)?
```suggestion
    - What are some of your ideas for campus/local community building?
```
Wanted to tone it down 😅 feel free to raise an objection

2022-04-14 14:49 UTC, VioletteLepercq commented on Students’ Ambassadors Program
> +    - What are some of your ideas for campus/local community building and evangelization (the more creative the better)?
agree :)

2022-04-14 14:50 UTC, merveenoyan commented on Students’ Ambassadors Program
> +- Proof that you are enrolled in a post-secondary formal education institution
```suggestion
- Proof of enrollment in a post-secondary formal education institution
```

2022-04-14 14:53 UTC, merveenoyan commented on Students’ Ambassadors Program
> +- Results: July 10, 2022
```suggestion
- Results will be announced on July 10, 2022.
```

2022-04-14 14:55 UTC, merveenoyan requested changes
I applied nits to the language to be a little bit more official and fixes to grammar.

2022-04-15 11:16 UTC, merveenoyan approved these changes
LGTM (speaking for myself I don't know what others have to say so I'd wait)

2022-04-20 14:30 UTC, osanseviero reviewed
Overall this looks good, but it requires some changes to make this work in the blog. I left some comments. Thank you :rocket: :rocket: :rocket: 

I'm a bit wary of publishing 3 blog posts about similar/somewhat overlapping topics in same dates.

2022-04-20 14:30 UTC, osanseviero commented on Students’ Ambassadors Program
> +- If you are willing to help your peers build machine learning, using open-source technologies and the Hugging Face community & tools, you have until June 20 to [apply](https://docs.google.com/forms/
I would suggest upper casing machine learning consistently.

2022-04-20 14:30 UTC, osanseviero commented on Students’ Ambassadors Program
> +# 🤗 **Student Ambassador Program’s call for applications is open!**
The file should be renamed to something like `ambassadors-program.md`

2022-04-20 14:30 UTC, osanseviero commented on Students’ Ambassadors Program
> +- A one page motivation letter that should include the following information:
Could we ask to make it shorter? It seems very complex to apply for this

2022-04-21 08:50 UTC, VioletteLepercq commented on Students’ Ambassadors Program
> +# 🤗 **Student Ambassador Program’s call for applications is open!**
first the blog post on edu 
then (when we will decide when to open application), we will share this blog post

2022-04-21 08:51 UTC, VioletteLepercq commented on Students’ Ambassadors Program
> +- If you are willing to help your peers build machine learning, using open-source technologies and the Hugging Face community & tools, you have until June 20 to [apply](https://docs.google.com/forms/
in the blog post https://github.com/huggingface/blog/pull/265, Abubakar is suggesting to maintain "machine learning" without upper cases. I do not have strong opinion on this

2022-04-21 08:51 UTC, VioletteLepercq commented on Students’ Ambassadors Program
> +# 🤗 **Student Ambassador Program’s call for applications is open!**
I think I renamed it but not sure I did it correctly

2022-04-21 08:51 UTC, VioletteLepercq commented on Students’ Ambassadors Program
> +- A one page motivation letter that should include the following information:
Yes, I will make a V2

2022-04-21 10:15 UTC, VioletteLepercq commented on Students’ Ambassadors Program
> +- A one page motivation letter that should include the following information:
@osanseviero I tried to shorten it, https://docs.google.com/forms/d/e/1FAIpQLScY9kTi-TjZipRFRviluRCwSjFf3CCsMbKedzO1tq2S0wtbNQ/viewform?usp=sf_link

Wdyt?

2022-04-21 18:56 UTC, NimaBoscarino commented on Students’ Ambassadors Program
> +# 🤗 **Student Ambassador Program’s call for applications is open!**
Looks like you can rename the file from the same view as where you edit it on GitHub:

![Screen Shot 2022-04-21 at 11 54 25 AM](https://user-images.githubusercontent.com/6765188/164533171-2592a313-668a-4da8-8b83-2b08269dba75.png)

I renamed it!

2022-04-24 15:07 UTC, osanseviero commented on Students’ Ambassadors Program
> +# 🤗 **Student Ambassador Program’s call for applications is open!**
Thanks Nima!

2022-04-24 15:07 UTC, osanseviero commented on Students’ Ambassadors Program
> +- A one page motivation letter that should include the following information:
Discussed offline

2022-04-24 15:36 UTC, osanseviero commented
Hey all, I did a series of changes:

https://github.com/huggingface/blog/pull/267/commits/f73f2dfa81f02d910c9fe126b04ba74849107af2
* Added blog post to `_blog.yml` which enables it.
* Adds a heading section 
(thumbnail still missing)

https://github.com/huggingface/blog/pull/267/commits/66a4c4a9a44cc117a01f79a11cccbbf00e8f5d81
* Uses lowercase for machine learning *
* Solves a comment about using * in first sentence from @NimaBoscarino 

https://github.com/huggingface/blog/pull/267/commits/5a4099fd6dee9aa4a8850f48e2a88b3788e57299
Aims to make things more concise and nicer to read. @VioletteLepercq I removed a part at the end that I felt was a bit repetitive with the form, and I wanted to keep the  blog post more lightweight. Does this sound good?

2022-04-24 15:38 UTC, osanseviero reviewed
This seems almost ready :rocket: I added a couple of comments

2022-04-24 15:38 UTC, osanseviero commented on _blog.yml
> +  thumbnail: /blog/assets/57_ai_residency/residency-thumbnail.jpg
We need to add an image for thumbnail here

2022-04-24 15:38 UTC, osanseviero commented on ambassadors-program.md
> +thumbnail: /blog/assets/57_ai_residency/residency-thumbnail.jpg
We need to update the thumbnail here

2022-04-24 15:38 UTC, osanseviero commented on ambassadors-program.md
> +As an Open Source company democratizing machine learning, Hugging Face believes it is essential to **[educate](https://www.notion.so/About-Hugging-Face-for-Education-afca12e2bc7c4e1ea9346ef2306a0a69)
I'm wondering if educate is the right word here. At least to me it doesn't read right.

2022-04-24 15:38 UTC, osanseviero commented on ambassadors-program.md
> +As an Open Source company democratizing machine learning, Hugging Face believes it is essential to **[educate](https://www.notion.so/About-Hugging-Face-for-Education-afca12e2bc7c4e1ea9346ef2306a0a69)
```suggestion
As an Open Source company democratizing machine learning, Hugging Face believes it is essential to **[educate](https://www.notion.so/About-Hugging-Face-for-Education-afca12e2bc7c4e1ea9346ef2306a0a69)** people from all kinds of backgrounds worldwide. **We aim to teach machine learning to 5 million people by 2023**.
```

2022-04-24 15:38 UTC, osanseviero commented on ambassadors-program.md
> +Wanna be part of Hugging Face’s machine learning democratization journey and teach & gather your campus communities around collaborative ML? Do you use Hugging Face's Hub and its open-source librarie
```suggestion
Wanna be part of Hugging Face’s machine learning democratization journey and teach & gather your campus communities around collaborative ML? Do you use Hugging Face and its open-source libraries? 
```

2022-04-24 15:38 UTC, osanseviero commented on ambassadors-program.md
> +As an Open Source company democratizing machine learning, Hugging Face believes it is essential to **[educate](https://www.notion.so/About-Hugging-Face-for-Education-afca12e2bc7c4e1ea9346ef2306a0a69)
Let's consistently say open-source or Open Source, but not both

2022-04-25 08:07 UTC, VioletteLepercq commented on _blog.yml
> +  thumbnail: /blog/assets/57_ai_residency/residency-thumbnail.jpg
Will create it

2022-04-25 08:08 UTC, VioletteLepercq commented on ambassadors-program.md
> +As an Open Source company democratizing machine learning, Hugging Face believes it is essential to **[educate](https://www.notion.so/About-Hugging-Face-for-Education-afca12e2bc7c4e1ea9346ef2306a0a69)
ok

2022-04-25 09:03 UTC, VioletteLepercq commented on ambassadors-program.md
> +thumbnail: /blog/assets/57_ai_residency/residency-thumbnail.jpg
here is a first proposal 
<img width="428" alt="image" src="https://user-images.githubusercontent.com/95622912/165056958-d07a802a-e2af-430c-b8aa-be4eab6007e7.png">

2022-04-25 09:16 UTC, VioletteLepercq commented on ambassadors-program.md
> +thumbnail: /blog/assets/57_ai_residency/residency-thumbnail.jpg
or 
<img width="390" alt="image" src="https://user-images.githubusercontent.com/95622912/165059163-9ba4289a-76e6-4544-b72e-45a214040e7d.png">

2022-04-25 09:17 UTC, VioletteLepercq commented on ambassadors-program.md
> +thumbnail: /blog/assets/57_ai_residency/residency-thumbnail.jpg
or 
<img width="390" alt="image" src="https://user-images.githubusercontent.com/95622912/165059353-12f1e1f6-68c7-4d97-b3a8-4dd779230a28.png">

2022-04-25 09:21 UTC, VioletteLepercq commented on ambassadors-program.md
> +thumbnail: /blog/assets/57_ai_residency/residency-thumbnail.jpg
or 
<img width="341" alt="image" src="https://user-images.githubusercontent.com/95622912/165060197-7e00cff1-9c9d-438f-b276-b22971923f9b.png">

2022-04-25 09:40 UTC, VioletteLepercq commented on _blog.yml
> +  thumbnail: /blog/assets/57_ai_residency/residency-thumbnail.jpg
also, I you are afraid of too many blog posts, we can replicate what you did with the Fellowship Program and create a one-pager notion doc  https://www.notion.so/huggingface2/Student-Ambassador-One-Pager-0e6b7dc66377461087a3c6e57a112db6

2022-04-28 15:19 UTC, merveenoyan commented on _blog.yml
> +=======
I think you should remove this line @VioletteLepercq for this to be parsed correctly

2022-04-28 15:20 UTC, VioletteLepercq commented on _blog.yml
> +=======
done :)

2022-05-09 14:07 UTC, omarespejel approved these changes
LGTM and the impact of this program is quite papable! 🚀
- Added some nits fix suggestions.
- Access to exclusive benefits and collaborators could be at odds with HF's goal of democratizing good ML. We remove this from our [Fellowship announcement](https://github.com/huggingface/blog/pull/268/files#diff-b541d154bc3c6c0f04992ab8203b0a473bddc73bc3dded01c6a0843a38b527e2R45) thanks to a comment from Patrick. Added a comment on this.
- For a possible iteration it could be valuable to consider as a Student Ambassadors, non-traditional forms of education. For example, not necessarily be part of a university. A lot of students get to know about ML and HF after their formal education.

2022-05-09 15:11 UTC, osanseviero reviewed
Overall looks good, but I agree some of the concerns from @omarespejel

2022-05-09 15:11 UTC, osanseviero commented on ambassadors-program.md
> +As an open-source company democratizing machine learning, Hugging Face believes it is essential to **[educate](https://huggingface.co/blog/education)** people from all kinds of backgrounds worldwide.
I really don't like the usage of "educate".

2022-05-09 15:11 UTC, osanseviero commented on ambassadors-program.md
> +* use free open-source technologies,
```suggestion
* learn and use free, open-source technologies,
```

2022-05-09 15:11 UTC, osanseviero commented on ambassadors-program.md
> +🤗 Direct contact with the HF team, including insight into the latest projects, features, and more!
Maybe we can just say

```suggestion
🤗 Insight into the latest projects, features, and more!
```

2022-05-09 15:42 UTC, VioletteLepercq commented on ambassadors-program.md
> +As an open-source company democratizing machine learning, Hugging Face believes it is essential to **[educate](https://huggingface.co/blog/education)** people from all kinds of backgrounds worldwide.
we will use teach instead :)

2022-05-09 15:42 UTC, VioletteLepercq commented on _blog.yml
> +  date: May 11, 2022
ok

2022-05-10 11:11 UTC, merveenoyan commented
I do not have any more changes :)

2022-05-11 14:22 UTC, osanseviero approved these changes

2022-05-11 14:22 UTC, osanseviero commented on _blog.yml
> +  - local: ambassadors-program
Consider changing this to just `ambassadors` and renaming the file as well for simplicity.

2022-05-11 14:22 UTC, osanseviero commented on _blog.yml
> +    - open-source-collab
I would remove this tag

2022-05-13 10:03 UTC, merged