Add Fellowship announcement to the Blog
huggingface/blog pull request #268
Opened 2022-04-14 01:17 UTC by omarespejel

A blog post announcing the Hugging Face Fellowship.

2022-04-14 14:28 UTC, merveenoyan commented on fellowship.md
> +There are no strings attached with the 🤗 Fellowship. This is Hugging Face supporting the amazing work of contributors! Being a Fellow works differently for everyone. The key question here is:
I wouldn't say this is no strings attached, it doesn't give any trust to the person and sounds unofficial.
```suggestion
This is Hugging Face supporting the amazing work of contributors! Being a Fellow works differently for everyone. The key question here is:
```

2022-04-14 14:33 UTC, merveenoyan commented on fellowship.md
> +Fellows are currently nominated by members of the Hugging Face team or by another Fellow. How can you get noticed? This is the main criteria:
```suggestion
Fellows are currently nominated by members of the Hugging Face team or by another Fellow, applications will soon be open. How can you get noticed? The main criterion is that you have contributed to democratization of open-source machine learning.
```

2022-04-14 14:33 UTC, merveenoyan commented on fellowship.md
> +- You have advanced the goal of democratizing good, open source machine learning.
```suggestion
```

2022-04-14 14:33 UTC, merveenoyan commented on fellowship.md
> +How? In the way you prefer. These are some examples of the first Fellows:
```suggestion
How? In the ways that you prefer. Here are some examples of our first Fellows:
```

2022-04-14 14:34 UTC, merveenoyan commented on fellowship.md
> +- **María Grandury** - She created the [largest NLP community](https://somosnlp.org/) in Spanish. Then she organized a Hackathon that achieved more than 20 models that advanced the SOTA for Spanish.
```suggestion
- **María Grandury** - She created the [largest NLP community](https://somosnlp.org/) and organized a Hackathon that achieved more than 20 models that advanced the SOTA for Spanish. 👩🏼‍🎤
```

2022-04-14 14:35 UTC, merveenoyan commented on fellowship.md
> +- **Aritra Roy Gosthipathy**: Contributed new architectures for TensorFlow in the transformers library and helped create the Keras working group. 🦹🏻
```suggestion
- **Aritra Roy Gosthipathy**: Contributed new architectures for TensorFlow in the transformers library, improved Keras tools and helped in creation of the Keras working group. 🦹🏻
```

2022-04-14 14:39 UTC, merveenoyan commented on fellowship.md
> +* **I'm starting to contribute. Can I be a fellow?**<br>Preferably people with more contributions are accepted as Fellows. That said, the program is flexible and we might consider it especially if yo
```suggestion
* **I'm starting to contribute. Can I be a fellow?**<br>You will definitely stand out from the crowd! ✨
```

2022-04-14 14:39 UTC, merveenoyan commented on fellowship.md
> +* **Will I be an employee of Hugging Face?**<br>No, the Fellowship does not mean you are an employee of Hugging Face. However, feel free to mention in any forum, including LinkedIn, that you are a Hu
```suggestion
* **Will I be an employee of Hugging Face?**<br>No, the Fellowship does not mean you are an employee of Hugging Face. However, feel free to mention in any forum, including LinkedIn, that you are a Hugging Face Fellow. Hugging Face is growing and this *could* be a good path for a bigger relationship in the future 😎.
```

2022-04-14 14:40 UTC, merveenoyan commented on fellowship.md
> +* **Will I receive benefits during the Residency?**<br>Yes, the benefits will depend on the particular needs and projects that each Fellow wants to undertake.
```suggestion
```
Residency is another program, so it might be confusing.

2022-04-14 14:41 UTC, merveenoyan requested changes
I added my notes, since this document was initially aimed for people who were already close to us, I feel like we should have a bit of less playful language if we want to onboard new contributors and fellows.

2022-04-14 17:08 UTC, omarespejel commented on fellowship.md
> +* **I'm starting to contribute. Can I be a fellow?**<br>Preferably people with more contributions are accepted as Fellows. That said, the program is flexible and we might consider it especially if yo
I think I did not write the question well. It would rather be something like "I am **just** starting to contribute. Can I be a fellow?" And there we can encourage them to continue contributing more in order to be considered for the Fellowship. We might not be interested in individuals with no contributions. WDYT?

2022-04-14 17:11 UTC, omarespejel commented on fellowship.md
> +✨ By being officially recognized as a Fellow, your career could be boosted.
Makes sense!

2022-04-14 17:23 UTC, omarespejel commented
Thanks @merveenoyan! Your comments made complete sense to me! I applied them. 

I believe the next step would be to add the list of priority fields where Hugging Face would want contributions. It would be the [same document you created for the current Fellows](https://docs.google.com/document/d/11mh36a4fgBlj8sh3_KoP2TckuPcnD-_S_UAtsEWgs50/edit). I added it to the public one-pager.

2022-04-15 11:13 UTC, merveenoyan commented on fellowship.md
> +* **I'm starting to contribute. Can I be a fellow?**<br>Preferably people with more contributions are accepted as Fellows. That said, the program is flexible and we might consider it especially if yo
yes but I wanted it to sound more encouraging instead of giving false hopes or demotivating them

2022-04-15 11:14 UTC, merveenoyan approved these changes
LGTM but I'd like to wait and see what @osanseviero has to say

2022-04-19 10:31 UTC, osanseviero reviewed
Thanks for setting this up! I left some comments :rocket:

2022-04-19 10:31 UTC, osanseviero commented on _blog.yml
> +  date: April 18, 2022
To update before merge

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +title: "Announcing the Hugging Face 🤗 Fellowship Program"
I would remove the emoji since it would be repeating hugging face twice

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +    <small>Published April 18, 2022.</small>
To update before merge

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +The 🤗 Fellowship is a network of exceptional people from different backgrounds who contribute to the open source ecosystem of Machine Learning 🚀. Our goal is to empower the key contributors and enabl
I usually prefer to not use the :hugs: emoji since it might not be super accessible. When it's an emoji that adds (such as :rocket: , :raised_hands:), that's perfect. But when you are replacing a word (Hugging Face) with an emoji (:hugs: ), it might make reading experience slightly worse.

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +The 🤗 Fellowship is a network of exceptional people from different backgrounds who contribute to the open source ecosystem of Machine Learning 🚀. Our goal is to empower the key contributors and enabl
```suggestion
The 🤗 Fellowship is a network of exceptional people from different backgrounds who contribute to the Machine Learning open-source ecosystem🚀. The goal of the program is to empower key contributors to enable them to scale their impact while inspiring others to contribute as well.
```

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +Fellows of all backgrounds are welcome! The progress of Machine Learning depends on grassroots contributions. Each person has a unique set of knowledge that can be used to democratize our field in a
```suggestion
Fellows of all backgrounds are welcome! The progress of Machine Learning depends on grassroots contributions. Each person has a unique set of skills and knowledge that can be used to democratize the field in a variety of ways. Each Fellow achieves impact differently and that is perfect 🌈. Hugging Face supports them to continue creating and sharing the way that fits their needs the best🤗.
```

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +Fellows of all backgrounds are welcome! The progress of Machine Learning depends on grassroots contributions. Each person has a unique set of knowledge that can be used to democratize our field in a
I would avoid using 2nd person (you) too much in this blog, I think 3rd person works better

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +The benefits will be based on the interests of each individual. Some examples of how we can support you:
```suggestion
The benefits will be based on the interests of each individual. Some examples of how we support Fellows:
```

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +Fellows are currently nominated by members of the Hugging Face team or by another Fellow. Applications will soon be open. How can you get noticed? The main criterion is that you have contributed to t
I would not say that applications will soon be open, since we've not decided we want the program to be application-based. Everything you mention still holds though (it is a nomination-based program, how to get noticed, etc).

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +- **María Grandury** - She created the [largest Spanish-speaking NLP community](https://somosnlp.org/) and organized a Hackathon that achieved more than 20 models that advanced the SOTA for Spanish.
Let's avoid pronouns since you just use them for the first two. 

```suggestion
- **María Grandury** - Created the [largest Spanish-speaking NLP community](https://somosnlp.org/) and organized a Hackathon that achieved more than 20 models that advanced the SOTA for Spanish. 👩🏼‍🎤
```

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +- **María Grandury** - She created the [largest Spanish-speaking NLP community](https://somosnlp.org/) and organized a Hackathon that achieved more than 20 models that advanced the SOTA for Spanish.
Maybe we can also add a link to https://huggingface.co/hackathon-pln-es and mention # of datasets and spaces

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +- **Aritra Roy Gosthipathy**: Contributed new architectures for TensorFlow in the transformers library, improved Keras tooling, and helped in the creation of the Keras working group. 🦹🏻
Maybe let's link to one or two of Aritra's projects

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +- **Vaibhav Srivastav** - Advocacy in the field of speech. He has led the ML4Audio working group, paper discussion sessions, and contributed to setting up Discord. 🦹🏻
I would remove the Discord thing. I would also add a link to https://github.com/Vaibhavs10/ml-with-audio and https://www.youtube.com/playlist?list=PLo2EIpI_JMQtOQK_B4G97yn1QWZ4Xi4Tu

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +- **Christopher Akiki** - Helped the Hugging Face team on many fronts, contributed to sprints, organized workshops! 🦹🏻‍♀️
Similarly, I would add a link to their work

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +- **Ceyda Çınarel** - Contributed to many Hugging Face models in various sprints! 👸🏻
You can add https://huggingface.co/spaces/huggan/butterfly-gan here

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +Additionally, there are strategic areas where Hugging Face is looking for open source contributions. These areas will be added and updated frequently on the [one-pager of the Fellowship](https://hugg
Instead of suggesting DM'ing in twitter, maybe you can take this as an opportunity to suggest them to go to Discord (hf.co/join/discord) and write in #looking-for-collaboratoes

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +* **I'm starting to contribute. Can I be a fellow?**<br>Preferably people with more contributions are accepted as Fellows. That said, the program is flexible and we might consider it especially if yo
Maybe

"Fellows are nominated based on their open-source and community contributions. If you would like to participate in it, the best way to get started it to start contributing!" WDTT>

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +* **I'm starting to contribute. Can I be a fellow?**<br>Preferably people with more contributions are accepted as Fellows. That said, the program is flexible and we might consider it especially if yo
And to make it even more actionable, you could maybe have a section about how to start with OS since we saw lots of interest on the topic both in twitter and YT in the past, with some actionable ideas (e.g. translate, minor doc issues, forum, pet projects, etc)

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +* **Will I be an employee of Hugging Face?**<br>No, the Fellowship does not mean you are an employee of Hugging Face. However, feel free to mention in any forum, including LinkedIn, that you are a Hu
```suggestion
* **Will I be an employee of Hugging Face?**<br>No, the Fellowship does not mean you are an employee of Hugging Face. However, feel free to mention in any forum, including LinkedIn, that you are a Hugging Face Fellow. Hugging Face is growing and this could be a good path for a bigger relationship in the future 😎.
```

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +* **Will I be an employee of Hugging Face?**<br>No, the Fellowship does not mean you are an employee of Hugging Face. However, feel free to mention in any forum, including LinkedIn, that you are a Hu
I would also suggest to apply to hf.co/jobs if they are interested

2022-04-19 10:31 UTC, osanseviero commented on fellowship.md
> +* **I'm starting to contribute. Can I be a fellow?**<br>Preferably people with more contributions are accepted as Fellows. That said, the program is flexible and we might consider it especially if yo
Why are you using `<br>`, since this is markdown you can just add the new line yourself

2022-04-27 08:55 UTC, patrickvonplaten commented on fellowship.md
> +🧑🏻‍💻 Exclusive workshops and support from the Hugging Face team!
Not a fan of having exclusive workshops - I don't think this is in line with "democratizing" machine learning. I think everything we do should be accessible by everybody no?

2022-04-27 08:56 UTC, patrickvonplaten commented on fellowship.md
> +🎎 Network of expert peers with whom fellows can collaborate.
Are the expert peers other fellows? This also sounds a bit like an exclusive club to me. I think hugging fellows should collaborate with everybody not just between themselves

2022-04-27 08:57 UTC, patrickvonplaten commented on fellowship.md
> +- **Manuel Romero** - He contributed [over 300 models](https://huggingface.co/mrm8488) to the Hugging Face Hub. He has trained multiple SOTA models in Spanish and has contributed to many different ef
```suggestion
- **Manuel Romero** - He contributed [over 300 models](https://huggingface.co/mrm8488) to the Hugging Face Hub. He has trained multiple SOTA models in Spanish 🤴🏻
```

2022-04-27 09:01 UTC, patrickvonplaten commented on fellowship.md
> +- **Bram Vanroy** - Helped many contributors and the Hugging Face team early on both GitHub and the forum 🦸🏼
Bram has done contributions to Transformers already 2 years ago - maybe a link to one of his first PRs / issues?

2022-04-27 09:02 UTC, patrickvonplaten commented on fellowship.md
> +- **Ceyda Çınarel** - Contributed to many Hugging Face models in various sprints! 👸🏻
Ceyda has also done this space for the Flax/JAX community event which was top 7: https://huggingface.co/spaces/flax-community/clip-reply-demo

2022-04-27 09:12 UTC, patrickvonplaten reviewed
It's very nicely written! I'm still generally a bit worried about making this a somewhat exclusive club, which I don't think we want to do.

1. I would remove all mentions of exclusivity and "expert" contributors. Calling only contributors in this group "experts" can make people that are not in this group feel like 2nd class contributors.
2. Think it could help to make a distinction between "community contribution" and "open-source contribution". To me, an open-source contribution is a code contribution to a GitHub library and maybe a model contribution, but "open-source" initially is about code no? So writing that many "open-source" contribution can make you a fellow doesn't look to be the case here at the moment. Can we frame this maybe more as "community contributors" 
3. It should be clear how to become a hugging fellow IMO and whoever is motivated to join the group should be able to do so. If this is not clear, it makes the group again look quite exclusive.
4. Hugging fellows should not only collaborate with other hugging fellows but with fellow open-source contributors which include **everybody** - it sounds a bit to me that collaborations should only happen within the hugging fellows.

2022-05-02 21:07 UTC, omarespejel commented on fellowship.md
> +The 🤗 Fellowship is a network of exceptional people from different backgrounds who contribute to the open source ecosystem of Machine Learning 🚀. Our goal is to empower the key contributors and enabl
Makes complete sense! Thanks.

2022-05-03 02:02 UTC, omarespejel commented on fellowship.md
> +Fellows of all backgrounds are welcome! The progress of Machine Learning depends on grassroots contributions. Each person has a unique set of knowledge that can be used to democratize our field in a
Agree! I changed this in every part of the blog except in the FAQs.

2022-05-03 02:03 UTC, omarespejel commented on fellowship.md
> +    <small>Published April 18, 2022.</small>
Added a placeholder date of May 5th. I will update this before the merge.

2022-05-03 02:25 UTC, omarespejel commented on fellowship.md
> +🧑🏻‍💻 Exclusive workshops and support from the Hugging Face team!
Completely agree! I will remove this part. Anything regarding "exclusive" material does not go with our premise of democratizing good ML. Thanks for noting

2022-05-03 02:59 UTC, omarespejel commented on fellowship.md
> +* **I'm starting to contribute. Can I be a fellow?**<br>Preferably people with more contributions are accepted as Fellows. That said, the program is flexible and we might consider it especially if yo
Great thanks Merve and Omar! Applied your feedback with:
- "Fellows are nominated based on their open source and community contributions. If you want to participate in the Fellowship, the best way to start is to begin contributing!"
- And a brand new FAQ "Where and how can I contribute?" with actionable projects/ideas.

2022-05-03 03:00 UTC, omarespejel commented
Thanks for your reviews @merveenoyan @osanseviero and @patrickvonplaten! Everything makes sense to me.

- Regarding your points, @patrickvonplaten, I applied them all. Thank you for noting those gaps. Indeed, the exclusivity of content and collaborations does not go hand in hand with our goal as a company (thanks @merveenoyan also for your last suggestion).
- I believe both "community contributors" (e.g. María Grandury) and "open-source contributors" (Bram) are accepted as Fellows. 

WDYT?

2022-05-17 08:10 UTC, osanseviero reviewed
Overall looks good, I left some comments. I would be more explicit that this is in an alpha/beta stage.

2022-05-17 08:10 UTC, osanseviero commented on _blog.yml
> +  date: May 5, 2022
to update

2022-05-17 08:10 UTC, osanseviero commented on _blog.yml
> +    - open-source-collab
this is not really an open source collaboration, so I would remove this

2022-05-17 08:10 UTC, osanseviero commented on fellowship.md
> +    <small>Published May 5, 2022.</small>
to update

2022-05-17 08:10 UTC, osanseviero commented on fellowship.md
> +    Announcing the Hugging Face Fellowship Program
Should it say Alpha or Beta or something like that?

2022-05-17 08:10 UTC, osanseviero commented on fellowship.md
> +Fellows are currently nominated by members of the Hugging Face team or by another Fellow. How can prospects get noticed? The main criterion is that they have contributed to the democratization of ope
```suggestion
Fellows are currently nominated by members of the Hugging Face team or by another Fellow. How can prospects get noticed? The main criterion is that they have contributed to the democratization of open-source Machine Learning.
```

2022-05-17 08:10 UTC, osanseviero commented on fellowship.md
> +Additionally, there are strategic areas where Hugging Face is looking for open source contributions. These areas will be added and updated frequently on the [one-pager of the Fellowship](https://hugg
Do we want to share this one-pager? I feel it will get out of data soon, and instead we could have this blog post as the central place. Also, the ideas are in https://docs.google.com/document/u/1/d/11mh36a4fgBlj8sh3_KoP2TckuPcnD-_S_UAtsEWgs50/edit?usp=sharing, not in the one-pager

2022-05-17 08:10 UTC, osanseviero commented on fellowship.md
> +Additionally, there are strategic areas where Hugging Face is looking for open source contributions. These areas will be added and updated frequently on the [one-pager of the Fellowship](https://hugg
When referring to the question, you can also add a link directly to that question

2022-05-17 08:10 UTC, osanseviero commented on fellowship.md
> +
```suggestion
It depends on your interests. Here are some ideas of areas where you can contribute, but you should work on things that get **you** excited!
- Share interesting models with the community through the Hub. These can be for Computer Vision, Reinforcement Learning and any other ML domain!
- Create tutorials and projects using different open-source libraries For example, Stable-Baselines 3, fastai or Keras.
- Organize local sprints to promote open source Machine Learning in different languages ​​or niches. For example, the Hackathon Somos PNL focused on Spanish speakers. The HugGAN sprint focused in generative models.
- Translate the [Hugging Face Course](https://github.com/huggingface/course#-languages-and-translations), the [Transformers documentation](https://github.com/huggingface/transformers/blob/main/docs/TRANSLATING.md) or the [Educational Toolkit](https://github.com/huggingface/education-toolkit/blob/main/TRANSLATING.md).
- [Doc with specific projects](https://docs.google.com/document/d/11mh36a4fgBlj8sh3_KoP2TckuPcnD-_S_UAtsEWgs50/edit) where contributions would be valuable. The doc will be frequently updated with new projects.
```

2022-05-17 08:10 UTC, osanseviero commented on fellowship.md
> +
I would add a short paragraph saying that if you're still a student you should also look at the ambassadors program and link to that blog post

2022-05-17 08:10 UTC, osanseviero commented on fellowship.md
> +In whatever way you think will have the greatest impact on the mission of democratizing good Machine Learning. In addition, we will constantly add strategic areas of contribution in the [Fellowship's
I think this can be removed as it's a bit redundant with the other question above

2022-05-17 11:36 UTC, merveenoyan commented
> Overall looks good, I left some comments. I would be more explicit that this is in an alpha/beta stage.

I don't think it's good to give that signal, it sounds a bit insecure and sloppy tbh

2022-05-17 11:37 UTC, merveenoyan commented on fellowship.md
> +    Announcing the Hugging Face Fellowship Program
I suggest we don't say that.

2022-05-17 11:37 UTC, merveenoyan commented on fellowship.md
> +Additionally, there are strategic areas where Hugging Face is looking for open source contributions. These areas will be added and updated frequently on the [one-pager of the Fellowship](https://hugg
Agreed!

2022-05-17 11:38 UTC, merveenoyan commented on fellowship.md
> +- **Bram Vanroy** - Helped many contributors and the Hugging Face team from the beginning. He has [issues](https://github.com/huggingface/transformers/issues/1332) and merged [pull requests](https://
He has issues sounds weird 😂  
```suggestion
- **Bram Vanroy** - Helped many contributors and the Hugging Face team from the beginning. He reported many [issues](https://github.com/huggingface/transformers/issues/1332), opened and merged [pull requests](https://github.com/huggingface/transformers/pull/1346) in the Transformers library since September 2019. 🦸🏼 
```

2022-05-17 11:40 UTC, merveenoyan commented
I did pick couple of nits, not many suggestions.

2022-05-17 18:44 UTC, omarespejel commented on fellowship.md
> +    Announcing the Hugging Face Fellowship Program
I believe it would be worth specifying this is a Beta program (being tested open to public). Being clear that a lot of pieces are still falling into place and we are iterating.

However @merveenoyan if you are sure that it should no have this, it is ok for me.

2022-05-17 21:22 UTC, merged