Add an example showing deployment using TensorFlow Serving and Kubernetes
huggingface/blog pull request #453
Opened 2022-08-07 13:15 UTC by sayakpaul

Done with @deep-diver. 

Cc: @osanseviero

2022-08-07 13:18 UTC, sayakpaul commented on _blog.yml
> +  date: August 15, 2022
Tentative.

2022-08-07 13:18 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +thumbnail: /blog/assets/56_fine_tune_segformer/thumb.png
Pending. Will be updated as available.

2022-08-08 05:36 UTC, deep-diver commented on deploy-tfserving-kubernetes.md
> +thumbnail: /blog/assets/56_fine_tune_segformer/thumb.png
thumbnail is updated

2022-08-08 14:47 UTC, merveenoyan requested changes
Thanks a lot for this blog post, I refreshed my GCP knowledge while reviewing! I left couple of suggestions and nits 🙂

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +things like embedding preprocessing and postprocessing operations within
```suggestion
topics like embedding preprocessing and postprocessing operations within
```

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +the ViT model, handling gRPC requests, etc.
```suggestion
the vision transformer model, handling gRPC requests, and more!
```

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +recommend reading it if not already done. You can find all the code
```suggestion
recommend reading it if it's not already read. You can find all the code
```

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +  goto.
```suggestion
  go-to.
```

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +- **Deploying the Docker container**: You have many options. The most
```suggestion
- **Deploying the Docker container**: You have various options, the most
```

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +  widely used is to deploy the Docker container on a Kubernetes
```suggestion
  widely used option is deploying the Docker container on a Kubernetes
```

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +  (autoscaling, security, for example). You can use a solution like
```suggestion
  (e.g. autoscaling, or security). You can use a solution such as
```

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +Recall from the previous post that the serving model can handle raw
Do you mean `SavedModel` format?

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +just in case. Then SavedModel should be placed in the special directory
would be nice to put SavedModel in backticks as well 🙂

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +```bash
Where should we run this script in? (directory) 🙂

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +one. There are various approaches for this, but you’ll do this by
maybe you could give link to base image 🙂

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +[<u>AVX512</u>](https://en.wikipedia.org/wiki/AVX-512). These
```suggestion
**Note**: TensorFlow Serving benefits from hardware optimizations, that leverage instruction sets such as
[<u>AVX512</u>](https://en.wikipedia.org/wiki/AVX-512). These
```

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +Now that the running container has all the required files in the
That'd be nice to show a directory of file outputs inside a codeblock so people know what's required 🙂 I might be a bit too in detail, but as a person who has followed TF for production tutorials before, it's a bit important to be thorough for newcomers.

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +```bash
Where do we run this on GKE terminal?

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +way you want. We encourage you to consult the
```suggestion
way you want. We encourage you to refer to the
```

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +- `deployment.yaml` defines the desired state of the Deployment by
```suggestion
- `deployment.yaml` defines the desired state of the deployment by
```

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +  inside Pods in the Kubernetes cluster.
```suggestion
  inside pods in the Kubernetes cluster.
```

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +    "image.jpg", "http://images.cocodataset.org/val2017/000000039769.jpg"
maybe mention later they can get it from bucket URI as well (I think it's cool for the sake of being end-to-end here)

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +**`enable_batching`** enables the batch inference capability that
Batching in cloud is particularly useful if you don't want to pay continuously (I think this is a super cool info to mention to people can save 💴 💵 ) but it's your choice 😅

2022-08-08 14:47 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +excited as we’re.
```suggestion
excited as we are.
```

2022-08-08 15:14 UTC, deep-diver commented on deploy-tfserving-kubernetes.md
> +**`enable_batching`** enables the batch inference capability that
Once we have an instance of TFServing, people could choose where to deploy it. So we left just a general ideas about batching capability. We will discuss more in-depth in the next blog posts.

However, I really appreciate your comment since I have not thought about it as a money saver :)

2022-08-08 15:17 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +the ViT model, handling gRPC requests, etc.
I would prefer to keep it to `Vision Transformer`.

2022-08-08 15:17 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +recommend reading it if not already done. You can find all the code
Not too sure about this passive voicing.

2022-08-08 15:18 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +  (autoscaling, security, for example). You can use a solution like
It's an "and" rather a "or"/

2022-08-08 15:19 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +Recall from the previous post that the serving model can handle raw
Yes.

2022-08-08 15:20 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +```bash
The script is standalone. You can run it on a Unix machine.

2022-08-08 15:20 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +one. There are various approaches for this, but you’ll do this by
I think we did it earlier. @deep-diver Cc.

2022-08-08 15:20 UTC, deep-diver commented on deploy-tfserving-kubernetes.md
> +- `deployment.yaml` defines the desired state of the Deployment by
Deployment, Pod, Service, HPA, ... are the terminologies(actually objects) for Kubernetes. When written with the capital letter at the beginning, they can be easily distinguished from standard English words. So, we wrote "Deployment" instead of "deployment.

2022-08-08 15:20 UTC, deep-diver commented on deploy-tfserving-kubernetes.md
> +  inside Pods in the Kubernetes cluster.
Same reason for this one too

2022-08-08 15:21 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +```bash
As long as you have `gcloud` configured on a system, you should be able to run it. 

We mentioned about `gcloud` earlier.

2022-08-08 15:22 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +Now that the running container has all the required files in the
Cc: @deep-diver

2022-08-08 15:23 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +- `deployment.yaml` defines the desired state of the Deployment by
Since `Deployment` is a concept in K8s, we decided to keep it this way.

2022-08-08 15:23 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +  inside Pods in the Kubernetes cluster.
Since Pods are a concept in K8s ...

2022-08-08 15:23 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +    "image.jpg", "http://images.cocodataset.org/val2017/000000039769.jpg"
Could you elaborate?

2022-08-08 15:24 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +**`enable_batching`** enables the batch inference capability that
It's a money saver only when you can afford to run things in an offline mode. We can definitely mention that in a bit more detail.

2022-08-08 15:28 UTC, deep-diver commented on deploy-tfserving-kubernetes.md
> +one. There are various approaches for this, but you’ll do this by
The link is provided. Please read the first and the second paragraphs in `Containerization with Docker` section.

2022-08-08 15:32 UTC, deep-diver commented on deploy-tfserving-kubernetes.md
> +    "image.jpg", "http://images.cocodataset.org/val2017/000000039769.jpg"
I think it depends on who is the end-user. For service consumers from personal devices, it is common to make requests with data from arbitrary sources. However, if TF Serving is just a part of micro service architecture, then it would make sense to say "end-to-end" with GCS bucket URI. 

Maybe we could just a leave a short comment like `you can get a file from GCS with get_file API as well`.

2022-08-08 15:41 UTC, deep-diver commented on deploy-tfserving-kubernetes.md
> +Now that the running container has all the required files in the
maybe this would be enough? @merveenoyan @sayakpaul 

```shell
models
models/hf-vit
models/hf-vit/1
models/hf-vit/1/keras_metadata.pb
models/hf-vit/1/variables
models/hf-vit/1/variables/variables.index
models/hf-vit/1/variables/variables.data-00000-of-00001
models/hf-vit/1/assets
models/hf-vit/1/saved_model.pb
```

2022-08-08 16:53 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +```bash
Can you mention this very briefly? 🙂

2022-08-08 16:54 UTC, merveenoyan commented on deploy-tfserving-kubernetes.md
> +Now that the running container has all the required files in the
it works, yes!

2022-08-09 02:44 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +one. There are various approaches for this, but you’ll do this by
Provided link to reduce back and forth.

2022-08-09 02:45 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +```bash
Added brief instructions before the `Containerization with Docker` section.

2022-08-09 02:45 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +```bash
Mentioned.

2022-08-09 02:50 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +    "image.jpg", "http://images.cocodataset.org/val2017/000000039769.jpg"
I don't think `get_file()` supports `gs://` URIs. 

I tried the following (`video-api-storage` bucket has public viewing enabled):

```
video_gcs_uri = "gs://video-api-storage/sample_video.mp4"
path_to_downloaded_file = tf.keras.utils.get_file("video.mp4", video_gcs_uri)
```

It results it:

```
Exception                                 Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/keras/utils/data_utils.py](https://localhost:8080/#) in get_file(fname, origin, untar, md5_hash, file_hash, cache_subdir, hash_algorithm, extract, archive_format, cache_dir)
    279         raise Exception(error_msg.format(origin, e.code, e.msg))
    280       except urllib.error.URLError as e:
--> 281         raise Exception(error_msg.format(origin, e.errno, e.reason))
    282     except (Exception, KeyboardInterrupt) as e:
    283       if os.path.exists(fpath):

Exception: URL fetch failure on gs://video-api-storage/sample_video.mp4: None -- unknown url type: gs
```

2022-08-09 02:54 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +**`enable_batching`** enables the batch inference capability that
Added a note.

2022-08-09 02:56 UTC, sayakpaul commented
@merveenoyan @deep-diver addressed almost all the PR comments. PTAL.

2022-08-09 09:15 UTC, osanseviero approved these changes
Cool blog post! Two suggestions:
* Consistently capitalize `Pods`. It's somewhat inconsistent at the moment.
* Try to be a bit more consistent between first and second person. Not a big issue though!

Thanks a lot for the contribution :fire: it's amazing! :rocket:

2022-08-09 09:15 UTC, osanseviero commented on deploy-tfserving-kubernetes.md
> +**Note**: TensorFlow Serving benefits from hardware optimizations, that leverage instruction sets such as
```suggestion
**Note**: TensorFlow Serving benefits from hardware optimizations that leverage instruction sets such as
```

2022-08-09 09:15 UTC, osanseviero commented on deploy-tfserving-kubernetes.md
> +out of the sum of `requests.cpu` across all pods to make scaling
Please capitalize Pods consistently

2022-08-09 09:19 UTC, sayakpaul commented
> Try to be a bit more consistent between first and second person. Not a big issue though!

You'd notice "you" and "we" both. Yes, we're aware of it. 

If you look into it a bit more deeply, you will notice that "we" is used quite sparingly and in cases where we deliberately want to highlight something about us rather than deflecting the reader. 

In all the other cases, we have tried maintaining "you" throughout. 

With this in mind, if you spot any inconsistencies regarding this, please let us know.

2022-08-09 12:41 UTC, deep-diver commented on _blog.yml
> +  authors: chansung, sayakpaul
Looks like there is an example? 
: https://github.com/huggingface/blog/blob/main/pytorch-xla.md

2022-08-09 12:44 UTC, osanseviero commented on _blog.yml
> +  authors: chansung, sayakpaul
Yes there can be multiple authors within the blog post (in the markdown file), but in the `.yml` file which is used to show the name in hf.co/blog we only have one author https://github.com/huggingface/blog/blob/main/_blog.yml#L137

2022-08-09 12:58 UTC, deep-diver commented
@osanseviero @sayakpaul 

addressed the comments

2022-08-09 13:30 UTC, mishig25 commented on _blog.yml
> +  authors: chansung, sayakpaul
yes, we currently only support single author in .yml file

2022-08-09 13:37 UTC, sayakpaul commented on _blog.yml
> +  authors: chansung, sayakpaul
@osanseviero resolved this.

2022-08-09 14:50 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +Vision Transformer model. For more details, check out [this link](https://github.com/sayakpaul/deploy-hf-tf-vision-models/tree/main/hf_vision_model_onnx_gke). ONNX-optimized models are especially ben
@osanseviero @merveenoyan added a note regarding ONNX deployments since many HF users are already familiar with it. Our repository supports deploying an ONNX-optimized version of the same ViT model to a Kubernetes cluster :) 

Cc: @deep-diver

2022-08-09 23:14 UTC, deep-diver commented
we need an approval from @merveenoyan :) more suggestions?

2022-08-11 13:01 UTC, merveenoyan approved these changes
LGTM! But I'd like @stevhliu to have a final look to see if there's anything. @stevhliu you can also merge given Omar and me will be gone next week. (Omar is already off)

2022-08-11 16:07 UTC, stevhliu reviewed
Super interesting read, especially for someone who doesn't know too much about Docker/Kubernetes! 🤗

2022-08-11 16:07 UTC, stevhliu commented on deploy-tfserving-kubernetes.md
> +can learn more about the auto-scaling algorithm internally used by
```suggestion
can learn more about the autoscaling algorithm internally used by
```

2022-08-11 16:07 UTC, stevhliu commented on deploy-tfserving-kubernetes.md
> +like autoscaling, cluster management, etc. while letting you focus on
```suggestion
like autoscaling and cluster management while letting you focus on
```

2022-08-11 16:07 UTC, stevhliu commented on deploy-tfserving-kubernetes.md
> +can let HPA (discussed later) decide to scale up or down the number of
I would spell out Horizontal Pod Autoscaler here since its the first time you're introducing it.

2022-08-11 16:10 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +This post builds on top of the [<u>previous post</u>](https://huggingface.co/blog/tf-serving-vision). So, we highly
"recommend" missing?

2022-08-11 16:12 UTC, sayakpaul commented on deploy-tfserving-kubernetes.md
> +in the [`SavedModel`](https://www.tensorflow.org/guide/saved_model) format. Recall how you
Maybe keep this one to empathize with the reader in case they feel clueless about the SavedModel?

2022-08-11 16:16 UTC, stevhliu commented on deploy-tfserving-kubernetes.md
> +This post builds on top of the [<u>previous post</u>](https://huggingface.co/blog/tf-serving-vision). So, we highly
Oh yes sorry!

2022-08-11 16:19 UTC, stevhliu commented on deploy-tfserving-kubernetes.md
> +in the [`SavedModel`](https://www.tensorflow.org/guide/saved_model) format. Recall how you
Sure, that's a good compromise :)

2022-08-11 16:23 UTC, sayakpaul commented
@stevhliu all comments addressed :)

2022-08-11 16:26 UTC, merged