setfit blog draft v0
huggingface/blog pull request #525
Opened 2022-09-16 09:03 UTC by eunseojo

2022-09-16 10:12 UTC, LuketheDukeBates commented on setfit.md
> +In a collaborative effort between Hugging Face and Intel, we introduce SetFit, a prompt-free few-shot regime made with practicality and efficiency in mind. Recent discussions in ML have focused on fe
To avoid repetition, how about alternating between "few-shot regimes" and "few-shot training"?

"inaccessible compute" sounds a little off to me. What about "inaccessible computational resources/infrastructure"?

Setfit --> SetFit

Here's a suggestion for the last two sentences:
SetFit shows similar or improved performance compared to other few-shot methods while also being prompt-free and only requiring small models that can fit on commercial personal computers. We make all code and data used in the development of SetFit publicly available..

2022-09-16 10:17 UTC, LuketheDukeBates commented on setfit.md
> +While run prompt-free and on much smaller base models, SetFit performs on par or better than state of the art few-shot regimes on a variety of benchmarks. On the RAFT, a few-shot benchmark dataset, (
"the RAFT" --> RAFT

SetFit Roberta (using the Roberta-Large ST base model)

"and comes just under average human performance" --> and places just under average human performance

"the 11 billion parameter T-few a model 30" --> the 11 billion parameter T-few, a model 30

2022-09-16 10:18 UTC, LuketheDukeBates commented on setfit.md
> +On non-few-shot datasets, SetFit shows robustness across a variety of tasks. It outperforms PERFECT, T-FEW 3 billion, ADAPET and vanilla transformers, on most tasks on sentiment, emotion, counterfact
"language classification at very" --> lanaguage classification tasks

2022-09-16 10:20 UTC, LuketheDukeBates commented on setfit.md
> +The strength of SetFit is its efficiency and simplicity. SetFit first finetunes a Sentence Transformer (ST) model then trains a classifier head on the generated ST embeddings.
"trains a classifier head on the generated ST embeddings." --> trains a classifier head on the embeddings generated from the finetuned ST.

2022-09-21 08:36 UTC, lewtun reviewed
Thanks for drafting this blog post - it's looking nice! 

I think we want to target industry practitioners, so we should write in a less academic style. I've left a suggestion on how to hook the reader and structure the rest of the blog post - we can discuss offline if that's more efficient

2022-09-21 08:36 UTC, lewtun commented on setfit.md
> +### Hugging Face, Intel labs, and the UKP team introduce a new prompt-free few-shot learning regime called Setfit with accompanying [code](https://github.com/SetFit/setfit), longer [paper](), and dat
I wouldn't use this text as a subheader. Instead, I suggest using a hook to excite the reader, e.g. something like: 

Few-shot learning with pretrained language models has emerged as a promising solution to every data scientist's nightmare: dealing with data that has few to no labels 😱. 

Together with our research partners at [Intel Labs](https://www.intel.com/content/www/us/en/research/overview.html) and the [UKP Lab](https://www.informatik.tu-darmstadt.de/ukp/ukp_home/index.en.jsp), we are excited to introduce SetFit: an efficient framework for few-shot fine-tuning of Sentence Transformers. 

Compared to other few-shot learning methods, SetFit has several unique features:

* 📈 **High accuracy with little labeled data:** SetFit achieves comparable (or better) results than current state-of-the-art methods for text classification. For example, with only 8 labelled examples per class on the CR sentiment dataset, SetFit is competitive with fine-tuning RoBERTa-large on the full training set of 3k examples.
* 🗣 **No prompts or verbalisers:** Current techniques for few-shot fine-tuning require handcrafted prompts or verbalisers to convert examples into a format that's suitable for the underlying language model. SetFit dispenses with prompts altogether by generating rich embeddings directly from text examples.
* 🏎 **Fast to train:** SetFit doesn't require large-scale models like T0 or GPT-3 to achieve high accuracy. As a result, it is typically an order of magnitude (or more) faster to train and run inference with.

For more details, you can check out our paper (ADD LINK) and code (ADD LINK). In this blog post, we'll explain how SetFit works and how to train your very own models. Let's dive in!

## How does it work?

[High level overview, with image of process from paper]

[Show Fig. 1 from the paper as comparison to standard fine tuning]

## Benchmarking SetFit

[Idea: pick 3 datasets from Table 2 and create box plots from the `final_results` to show the spread of values visually. If time doesn't allow, just show the table]

### Fast training and inference

[Idea: convert table 5 to 2 plots, with score on y-axis, FLOPs on x-axis, and model size as radius of circle]

## Training your own model

[Show quickstart]

2022-09-23 09:02 UTC, lewtun requested changes
Thanks for iterating @eunseojo - the blog looks much better now!

I've left a few comments and thing we need to also:

* Double check the boxplot figure for accuracy
* Delete outdated images

2022-09-23 09:02 UTC, lewtun commented on setfit.md
> +        <img class="avatar avatar-user" src="https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=-I2EZeEAAAAJ&citpid=8" title="Gravatar">
Should we add profile pics of everyone in the colab?

2022-09-25 13:23 UTC, lewtun approved these changes
Looking good! I've left a few final nits - if you agree you can accept them via the GitHub UI to save you some time :)

2022-09-25 13:23 UTC, lewtun commented on setfit.md
> +Together with our research partners at [Intel Labs](https://www.intel.com/content/www/us/en/research/overview.html) and the [UKP Lab](https://www.informatik.tu-darmstadt.de/ukp/ukp_home/index.en.jsp)
I realised that our first comparison point to few-shot methods ("High accuracy with little labeled data") isn't quite accurate since they also do well. Instead I suggest we remove this point and add the following sentence:

```suggestion
Together with our research partners at [Intel Labs](https://www.intel.com/content/www/us/en/research/overview.html) and the [UKP Lab](https://www.informatik.tu-darmstadt.de/ukp/ukp_home/index.en.jsp), we are excited to introduce SetFit: an efficient framework for few-shot fine-tuning of [Sentence Transformers](https://sbert.net/). SetFit achieves high accuracy with little labeled data - for example, with only 8 labeled examples per class on the Customer Reviews sentiment dataset, SetFit is competitive with fine-tuning RoBERTa Large on the full training set of 3k examples 🤯!

<p align="center">
    <img src="assets/103_setfit/setfit_curves.png" width=400>
</p>
<p align="center">
    SetFit and fine-tuning performance on the Customer Reviews sentiment dataset.
</p>
```

2022-09-25 13:23 UTC, lewtun commented on setfit.md
> +<p>📈 <strong>High accuracy with little labeled data</strong>: SetFit achieves comparable (or better) results than current state-of-the-art methods for text classification. For example, with only 8 la
Delete this point as suggested above:

```suggestion
```

2022-09-25 13:23 UTC, lewtun commented on setfit.md
> +<p>🌎 <strong>Multilingual support</strong>: SetFit can be used with any Sentence Transformer on the Hub, which means you can classify text in multiple languages by simply switching the backbone to a
```suggestion
<p>🌎 <strong>Multilingual support</strong>: SetFit can be used with any [Sentence Transformer](https://huggingface.co/models?library=sentence-transformers&sort=downloads) on the Hub, which means you can classify text in multiple languages by simply fine-tuning a multilingual checkpoint. </p>
```

2022-09-25 13:23 UTC, lewtun commented on setfit.md
> +For more details, you can check out our [paper](https://arxiv.org/abs/2209.11055), [data](https://huggingface.co/SetFit) and [code](https://github.com/huggingface/setfit). In this blog post, we'll ex
turbo nit:
```suggestion
For more details, you can check out our [paper](https://arxiv.org/abs/2209.11055), [data](https://huggingface.co/SetFit), and [code](https://github.com/huggingface/setfit). In this blog post, we'll explain how SetFit works and how to train your very own models. Let's dive in!
```

2022-09-25 13:23 UTC, lewtun commented on setfit.md
> +<p align="center">
I suggest moving this image up, so let's delete this snippet here

2022-09-25 13:23 UTC, lewtun commented on setfit.md
> +    Fig.2: SetFit's 2-Part Process
```suggestion
    SetFit's two-stage training process
```

2022-09-25 13:23 UTC, lewtun commented on setfit.md
> +SetFit is designed with efficiency and simplicity in mind. SetFit first finetunes a Sentence Transformer model then trains a classifier head on the embeddings generated from the finetuned Sentence Tr
```suggestion
SetFit is designed with efficiency and simplicity in mind. SetFit first fine-tunes a Sentence Transformer model on a small number of labeled examples (typically 8 or 16 per class). This is followed by training a classifier head on the embeddings generated from the fine-tuned Sentence Transformer. 
```

2022-09-25 13:23 UTC, lewtun commented on setfit.md
> +SetFit takes advantage of sentence transformers’ ability to generate dense embeddings based on paired sentences. In the data input stage, it maximizes the limited labeled input data by contrastive tr
```suggestion
SetFit takes advantage of Sentence Transformers’ ability to generate dense embeddings based on paired sentences. In the data input stage, it maximizes the limited labeled input data by contrastive training, where positive and negative pairs are created by in-class and out-class selection. The Sentence Transformer model then trains on these pairs (or triplets) and generates dense vectors per example. This is SetFit’s fine-tuning step. In the second step, the classification head, such as a logistic regression model, trains on the encoded embeddings with their respective class labels. At inference time, the unseen example passes through the fine-tuned Sentence Transformer, generating an embedding that when fed to the classification head outputs a class label prediction.
```

2022-09-25 13:23 UTC, lewtun commented on setfit.md
> +<h4>Table 1: RAFT performance leaderboard as of September 2022</h4>
```suggestion
<h4>Prominent methods on the RAFT leaderboard (as of September 2022)</h4>
```

2022-09-25 13:23 UTC, lewtun commented on setfit.md
> +Although based on much smaller models than existing few-shot methods, SetFit performs on par or better than state of the art few-shot regimes on a variety of benchmarks. On [RAFT](https://huggingface
```suggestion
Although based on much smaller models than existing few-shot methods, SetFit performs on par or better than state of the art few-shot regimes on a variety of benchmarks. On [RAFT](https://huggingface.co/spaces/ought/raft-leaderboard), a few-shot classification benchmark, SetFit Roberta (using the [`all-roberta-large-v1`](https://huggingface.co/sentence-transformers/all-roberta-large-v1) base model) with 355 million parameters outforms PET and GPT-3 and places just under average human performance and the 11 billion parameter T-few, a model 30 times the size of SetFit Roberta (Table 1). SetFit also outperforms the human baseline on 7 of the 11 RAFT tasks.
```

2022-09-25 13:23 UTC, lewtun commented on setfit.md
> +    Fig.3: Comparing Setfit performance against other methods on 3 tasks
```suggestion
    Comparing Setfit performance against other methods on 3 classification datasets.
```

2022-09-25 13:23 UTC, lewtun commented on setfit.md
> +On other datasets, SetFit shows robustness across a variety of tasks. It outperforms PERFECT, T-Few 3B, ADAPET and fine-tuned vanilla transformers, on many tasks on sentiment, emotion, counterfactual
```suggestion
On other datasets, SetFit shows robustness across a variety of tasks. It outperforms PERFECT, T-Few 3B, ADAPET and fine-tuned vanilla transformers, on many tasks on sentiment, emotion, counterfactual, and unwanted language classification tasks at very few (n=8) and few (n=64) - shot learning scenarios. Figure 3 shows a comparison on three chosen tasks: Emotion, CR, and Amazon Counterfactual. 
```

2022-09-25 13:23 UTC, lewtun commented on setfit.md
> +On other datasets, SetFit shows robustness across a variety of tasks. It outperforms PERFECT, T-Few 3B, ADAPET and fine-tuned vanilla transformers, on many tasks on sentiment, emotion, counterfactual
```suggestion
On other datasets, SetFit shows robustness across a variety of tasks. It outperforms standard fine-tuning, PERFECT, and ADAPET with 8 and 64 labeled examples per class, and is comparable to T-Few (the current SOTA). Figure 3 shows a comparison on three chosen tasks: Emotion, SentEval-CR, and Amazon Counterfactual. 
```

2022-09-25 18:27 UTC, lewtun commented on setfit.md
> +<p>🗣 <strong>No prompts or verbalisers</strong>: Current techniques for few-shot fine-tuning require handcrafted prompts or verbalisers to convert examples into a format that's suitable for the under
```suggestion
<p>🗣 <strong>No prompts or verbalisers</strong>: Current techniques for few-shot fine-tuning require handcrafted prompts or verbalisers to convert examples into a format that's suitable for the underlying language model. SetFit dispenses with prompts altogether by generating rich embeddings directly from a small number of labeled text examples. </p>
```

2022-09-25 18:28 UTC, lewtun commented on setfit.md
> +For more details, you can check out our [paper](https://arxiv.org/abs/2209.11055), [data](https://huggingface.co/SetFit) and [code](https://github.com/huggingface/setfit). In this blog post, we'll ex
```suggestion
For more details, check out our [paper](https://arxiv.org/abs/2209.11055), [data](https://huggingface.co/SetFit) and [code](https://github.com/huggingface/setfit). In this blog post, we'll explain how SetFit works and how to train your very own models. Let's dive in!
```

2022-09-25 19:03 UTC, lewtun commented on setfit.md
> +Although based on much smaller models than existing few-shot methods, SetFit performs on par or better than state of the art few-shot regimes on a variety of benchmarks. On [RAFT](https://huggingface
Should the `Setfit_RAFT.png` image appear below this paragraph?

2022-09-25 19:09 UTC, lewtun commented on setfit.md
> +    Fig.4: Comparing T-Few 3B and SetFit (MP-Net) train cost on AWS for N=8 and average accuracy across test tasks
```suggestion
    Comparing training cost and average performance for T-Few 3B and SetFit (MPNet), with 8 labeled examples per class.
```

2022-09-25 19:20 UTC, lewtun commented on setfit.md
> +Using SetFit is as simple as just a few lines of code. There is need for hyperparameter searching or prompt-engineering.
```suggestion
To make SetFit accessible to the community, we've created a small `setfit` [library](https://github.com/huggingface/setfit) that allows you to train your own models with just a few lines of code. 
```

2022-09-25 19:20 UTC, lewtun commented on setfit.md
> +To start using SetFit, first install it using pip. This will also install dependencies such as datasets and sentence-transformers.
```suggestion
The first thing to do is install it by running the following command:
```

2022-09-25 19:24 UTC, lewtun commented on setfit.md
> +We first import relevant functions. In particular we import SetFitModel and SetFitTrainer, two functions that have streamlined the SetFit procedure for us.
```suggestion
Next, we import `SetFitModel` and `SetFitTrainer`, two core classes that streamline the SetFit training process:
```

2022-09-25 19:24 UTC, lewtun commented on setfit.md
> +from setfit.modeling import SetFitModel
I tweaked the lib so this is now possible (and simpler):
```suggestion
from setfit import SetFitModel, SetFitTrainer
```

2022-09-25 19:24 UTC, lewtun commented on setfit.md
> +from setfit.trainer import SetFitTrainer
```suggestion
```

2022-09-25 19:25 UTC, lewtun commented on setfit.md
> +We download our dataset from the HF hub. In this case we start with the SentEval-CR task, the performance of which is shown in our Fig.1.
```suggestion
Now, let's download a text classification dataset from the Hugging Face Hub. We'll use the `SentEval-CR` dataset, which is a dataset of customer reviews: 
```

2022-09-25 19:26 UTC, lewtun commented on setfit.md
> +```sh
```suggestion
```python
```

2022-09-25 19:26 UTC, lewtun commented on setfit.md
> +# Load a dataset
```suggestion
```

2022-09-25 19:27 UTC, lewtun commented on setfit.md
> +Let's now select our N, the number of examples per class. In this case we make this 8. N will vary depending on your dataset constraints.
```suggestion
To simulate a real-world scenario with just a few labeled examples, we'll sample 8 examples per class from the training set: 
```

2022-09-25 19:27 UTC, lewtun commented on setfit.md
> +```sh
```suggestion
```python
```

2022-09-25 19:28 UTC, lewtun commented on setfit.md
> +We will load a pretrained Sentence Transformer model from the HF hub then create a SetFitTrainer.
```suggestion
Now that we have a dataset, the next step is to load a pretrained Sentence Transformer model from the Hub and instantiate a `SetFitTrainer`. Here we use the  `paraphrase-mpnet-base-v2` model, which we found to give great results across many datasets:
```

2022-09-25 19:28 UTC, lewtun commented on setfit.md
> +```sh
```suggestion
```python
```

2022-09-25 19:29 UTC, lewtun commented on setfit.md
> +Training this is easy! We can then evaluate with train.evaluate().
The last step is to train and evaluate the model:

2022-09-25 19:29 UTC, lewtun commented on setfit.md
> +```sh
```suggestion
```python
```

2022-09-25 19:29 UTC, lewtun commented on setfit.md
> +Remember to push your trained model to the HF hub :)
```suggestion
And that's it - you've now trained your first SetFit model! Remember to push your trained model to the Hub :) 
```

2022-09-25 19:30 UTC, lewtun commented on setfit.md
> +While this example showed how this can be done with one specific type of base model, any Sentence Transformer base model could be traded in here for different performance and tasks. For intance, usin
```suggestion
While this example showed how this can be done with one specific type of base model, any [Sentence Transformer](https://huggingface.co/models?library=sentence-transformers&sort=downloads) model could be traded in here for different performance and tasks. For instance, using a multilingual Sentence Transformer body can extend few-shot classification to multilingual settings.
```

2022-09-25 19:40 UTC, lewtun commented on setfit.md
> +
Let's add a small closing :)

```suggestion
## Next steps

So far, we've shown that SetFit is an effective method for few-shot classification tasks. In the coming months, we'll be exploring how well the method generalises to tasks like natural language inference and token classification. In the meantime, we're excited to see how industry practitioners apply SetFit to their use cases - if you have any questions or feedback, open an issue on our [GitHub repo](https://github.com/huggingface/setfit) 🤗!
```

2022-09-26 09:29 UTC, lewtun commented on setfit.md
> +SetFit takes advantage of sentence transformers’ ability to generate dense embeddings based on paired sentences. In the initial fine-tuning phase stage, it makes use of the limited labeled input data
```suggestion
SetFit takes advantage of Sentence Transformers’ ability to generate dense embeddings based on paired sentences. In the initial fine-tuning phase stage, it makes use of the limited labeled input data by contrastive training, where positive and negative pairs are created by in-class and out-class selection. The Sentence Transformer model then trains on these pairs (or triplets) and generates dense vectors per example. In the second step, the classification head trains on the encoded embeddings with their respective class labels. At inference time, the unseen example passes through the fine-tuned Sentence Transformer, generating an embedding that when fed to the classification head outputs a class label prediction.
```

2022-09-26 09:55 UTC, merged