Audio Datasets
huggingface/blog pull request #636
Opened 2022-11-16 10:21 UTC by sanchit-gandhi

Whistle stop tour of audio datasets with 🤗 Datasets and the HF Hub.

Proposed structure:

**Intro**
Explain motivations: plant the seed that 🤗 Datasets is the number one place for downloading and preparing audio datasets.

**Sec 1: Loading a Dataset**

- Show how easy it is to download an audio dataset in one line of Python code
- Explain briefly the args to the `load_dataset` function
- Explain what's going on under the hood: download, extract, prepare data & splits

**Sec 2: Easy to Download, Easy to Process**

- Example for preparing an audio dataset for inference / fine-tuning
- Use `AutoProcessor` to load a processor from any checkpoint
- How to resample to a desired sampling rate
- How to pre-process the audio inputs (feature extractor) and tokenise the transcriptions

**Sec 3: The Hub**

- Datasets Card -> dataset info, everything you need to know about the dataset in one place
- Highlight Datasets Viewer -> the ease with which datasets can be viewed/experienced
- Repos for storing raw audio data

**Sec 4: A Tour of Audio Datasets on the Hub**
Synopsis of the major audio datasets.

- English ASR (ESB datasets)
- Multilingual ASR
- Speech Translation
- Audio Classification

+ streaming mode -> think about which section this falls best under or an entirely new section

2022-11-16 10:57 UTC, Vaibhavs10 commented
A couple of suggestions:
1. Loading a Dataset: We should also talk about Audio Folder here. Leveraging local datasets would be a key part for researchers, hobbyists, and professionals alike.
2. Easy to load: Maybe we extend this a bit and talk about streaming a bit here. This way we nail the point that datasets are quite resilient and can do whatever they want.
3. Process: We should definitely talk about map and cast_column here, this will be quite useful for snipping audio/ adding noise/ etc. One function to rule them all.

WDYT?

2022-11-16 12:02 UTC, sanchit-gandhi commented
1. We could feature the audio folder prominently on the Google Colab example too -> would be well suited here in the 'hands on' accompaniment
2. Yep, streaming will slot into the loading section most probably
3. Process: absolutely, will highlight `cast_column` and `map` through pre-processing examples. I'm not sure if data aug is the way to go though - I had in mind the more conventional steps of resampling (`cast_column`) and preparing a dataset for a model (`map`)

2022-11-22 15:18 UTC, sanchit-gandhi commented on audio-datasets.md
> +
Potentially missing a (sub-) section on Audio Folder - could be nice to showcase how one can upload their own audio data to the Hub

2022-11-22 16:02 UTC, sanchit-gandhi commented
Colab link: https://colab.research.google.com/drive/1ySCQREPZEl4msLfxb79pYYOWjUZhkr9y
Will move to GH once finalised.

2022-11-22 16:03 UTC, sanchit-gandhi commented on audio-datasets.md
> +<!--- TODO: insert link to Colab --->
Colab link: https://colab.research.google.com/drive/1ySCQREPZEl4msLfxb79pYYOWjUZhkr9y
Will move to GH once finalised.

2022-11-23 09:00 UTC, osanseviero reviewed
Very very cool blog post 🔥

2022-11-23 09:35 UTC, lhoestq reviewed
Awesome thank you !

2022-11-23 09:35 UTC, lhoestq commented on audio-datasets.md
> +<!--- TODO: make this statement valid --->
```suggestion
The only change is that you can no longer access one sample in particular using `dataset[sample_idx]`, but instead have to iterate over the dataset (using a for loop for example).
```

2022-11-23 09:35 UTC, lhoestq commented on audio-datasets.md
> +common_voice = load_dataset("mozilla-foundation/common_voice_11", "en", use_auth_token=True)
maybe mention why you need a token to access this one

2022-11-24 13:33 UTC, sanchit-gandhi commented on audio-datasets.md
> +<!--- TODO: insert link to Colab --->
Resolved in https://github.com/huggingface/blog/pull/636/commits/5c797aa54cb6196c06d7389a86842e76255f7ba8

2022-11-25 10:47 UTC, patrickvonplaten commented on audio-datasets.md
> +prepare the most popular audio datasets in just one line of Python code.
We'll that's a bit the message we want to convey to people though IMO :sweat_smile:

2022-11-25 10:47 UTC, patrickvonplaten commented on audio-datasets.md
> +prepare the most popular audio datasets in just one line of Python code.
But yeah maybe a bit aggressive

2022-11-25 10:51 UTC, patrickvonplaten commented on audio-datasets.md
> +1. [Load an Audio Dataset](#load-an-audio-dataset)
actually before jumping into code, I think we should present the Hub first, that's more visually and a "softer" introduction I think. 

E.g. I'd start with the "Hub" section, then brag about all the datasets we have with the nice list you made, then maybe add one sentence to explain how people can find other audio datasets using the task categories.

And only then jump into the code.

E.g. people first need to find the dataset they want to load and this is a very important step!

2022-11-25 10:52 UTC, patrickvonplaten reviewed
Looks very clean, but I would change the order a bit. I think "The Hub" and "Tour of audio datasets" should go in the beginning. That's the most exciting part, it's always "softer" to first see visuals and demos and then the code.

2022-11-25 11:46 UTC, polinaeterna commented on audio-datasets.md
> +depicted graphically in Figure 1. Streaming allows us to download data progressively as we iterate over the dataset:
strictly speaking, data is not being downloaded in streaming mode, as it's not saved on disk. it's just opened and iterated over

2022-11-28 15:16 UTC, polinaeterna requested changes
Love it! 

I've left a few mostly technical comments. My main suggestion is to reformulate streaming explanation a bit so that it sounds correct but without diving into technical details. Basically, we don't have any chunks of data that's being iteratively downloaded - we just stream example one by one progressively not downloading anything locally. I've left a few suggestions in some places (but probably not everywhere), feel free to reformulate them :)

2022-11-28 15:16 UTC, polinaeterna commented on audio-datasets.md
> +2. **Download and processing speed:** audio datasets are large and need a significant amount of time to download. With streaming, downloading is done on the fly, meaning you can start using the datas
```suggestion
2. **Processing time:** audio datasets are large and need a significant amount of time to download. With streaming, you don't need to spend time on data download, meaning you can start iterating over examples straightaway.

2022-11-28 15:16 UTC, polinaeterna commented on audio-datasets.md
> +
maybe worth noting that benefits of streaming result in its drawback - as the data is not downloaded and cached and prepared in arrow on disk, reusing the dataset would require yielding from streamed file(s) again and eventually is slower than loading and generating for arrow tables. 

but maybe we can skip this :D

2022-12-03 09:36 UTC, sanchit-gandhi commented on _blog.yml
> +  date: Nov 21, 2022
Resolved in https://github.com/huggingface/blog/pull/636/commits/1ade028af76b5c4137b3e866f192da498450eec9

2022-12-03 09:36 UTC, sanchit-gandhi commented on audio-datasets.md
> +---
Resolved in https://github.com/huggingface/blog/pull/636/commits/d97c1a07bcd3d3627a5769f6a33bd5066d7253be

2022-12-03 09:36 UTC, sanchit-gandhi commented on audio-datasets.md
> +thumbnail: /blog/assets/116_audio_datasets/thumbnail.jpg
Resolved in https://github.com/huggingface/blog/pull/636/commits/609fff09022c526a6dee83914a5e5acebaeb19ca

2022-12-03 09:37 UTC, sanchit-gandhi commented on audio-datasets.md
> +    <small>Published 21 November, 2022.</small>
Resolved in https://github.com/huggingface/blog/pull/636/commits/5798551150e14e537cf6695a8ee0473a5ec724d5

2022-12-03 09:38 UTC, sanchit-gandhi commented on audio-datasets.md
> +1. [Load an Audio Dataset](#load-an-audio-dataset)
Good suggestion! Moving "The Hub" section to the start. Keeping the "tour of audio datasets on the Hub" section at the end as a reference guide (people will stop reading if this is too early on).

Resolved in https://github.com/huggingface/blog/pull/636/commits/e2ec7744e3f56b28a6eea53aa24725f7a74f36a6

2022-12-03 09:38 UTC, sanchit-gandhi commented on audio-datasets.md
> +## A Tour of Audio Datasets on The Hub
See https://github.com/huggingface/blog/pull/636#discussion_r1038755739

2022-12-03 09:39 UTC, sanchit-gandhi commented on audio-datasets.md
> +depicted graphically in Figure 1. Streaming allows us to download data progressively as we iterate over the dataset:
Resolved in https://github.com/huggingface/blog/pull/636/commits/06e2200b7e77b6736d3bab7e4c43895c736b613a

2022-12-03 09:39 UTC, sanchit-gandhi commented on audio-datasets.md
> +Once we're ready to move on to the next chunk of data, we delete the one that we currently have and move on to the
Resolved in https://github.com/huggingface/blog/pull/636/commits/06e2200b7e77b6736d3bab7e4c43895c736b613a

2022-12-03 09:59 UTC, sanchit-gandhi commented on audio-datasets.md
> +1. **Disk space:** you have complete control over the size of the chunks downloaded, so you can download chunks of data that will fit your device.
Resolved in https://github.com/huggingface/blog/pull/636/commits/cd6dc002d5421a235a1f6b643bc4e6f40668ad8a

2022-12-03 09:59 UTC, sanchit-gandhi commented on audio-datasets.md
> +rather than downloading the whole dataset at once, we download small chunks of the dataset at a time. These chunks of
Resolved in https://github.com/huggingface/blog/pull/636/commits/06e2200b7e77b6736d3bab7e4c43895c736b613a

2022-12-03 09:59 UTC, sanchit-gandhi commented on audio-datasets.md
> +2. **Download and processing speed:** audio datasets are large and need a significant amount of time to download. With streaming, downloading is done on the fly, meaning you can start using the datas
Resolved in https://github.com/huggingface/blog/pull/636/commits/d8f3f5edb7201375f60c7359803acb4408181f39

2022-12-03 10:00 UTC, sanchit-gandhi commented on audio-datasets.md
> +
This is a very good point! I think we should include this

Resolved in https://github.com/huggingface/blog/pull/636/commits/d8f3f5edb7201375f60c7359803acb4408181f39

2022-12-03 10:03 UTC, sanchit-gandhi commented on audio-datasets.md
> +We can see that there are a number of features returned by the `DatasetDict`, including `segment_id`, `speaker`, `text`,
Resolved in https://github.com/huggingface/blog/pull/636/commits/8a3f54a340ebe4cdea97a30cc9b4a254c05e3de3

2022-12-03 10:04 UTC, sanchit-gandhi commented on audio-datasets.md
> +```python
Resolved in https://github.com/huggingface/blog/pull/636/commits/1aeea0571f2ca98de09c1ef3cbe0fcfcd732f123

2022-12-03 10:10 UTC, sanchit-gandhi commented on audio-datasets.md
> +all_columns = next(iter(gigaspeech.values())).column_names
Does look easier, let's do that!

I think we can skip the assertion for the purpose of the blog - 99.9% of the time datasets will have consistent features across their splits so should be ok for the most part.

2022-12-03 10:12 UTC, sanchit-gandhi commented on audio-datasets.md
> +<!--- TODO: is this on the Hub? --->
Is FLEURS the best one that we have then? Any other cool audio classification datasets you think are worth adding?

2022-12-03 10:13 UTC, sanchit-gandhi commented on audio-datasets.md
> +introduced streaming mode, a method for downloading and preparing chunks of audio data on the fly.
Resolved in https://github.com/huggingface/blog/pull/636/commits/511d78e0f3e559f9825a3e2cbc4ffd7e14beb20e

2022-12-03 10:14 UTC, sanchit-gandhi commented on audio-datasets.md
> +| [AMI](https://huggingface.co/datasets/edinburghcstr/ami)                                | Meetings                    | Spontaneous           | 100         | ✅      | ✅           | CC-BY-4.0
I just went with the ESB benchmark datasets (we've built the Google Colab script around this)

2022-12-03 10:15 UTC, sanchit-gandhi commented on audio-datasets.md
> +#### [LibriSpeech ASR](https://huggingface.co/datasets/librispeech_asr)
IMO our first priority should be getting people to use the 'popular' ASR datasets - we see in the Whisper paper that they use HF models for their baselines, but torchaudio for their datasets. This suggests that people aren't aware that we have the top audio datasets available on the Hub -> let's try and change that by making them more visible!

2022-12-03 10:21 UTC, sanchit-gandhi commented on audio-datasets.md
> +_on the fly_ the first time they are loaded. The following code cell will set the sampling rate to 8kHz:
Good point! Clarified in https://github.com/huggingface/blog/pull/636/commits/9c41865f168ca661aa45c7ac09907f0aa2944d52

> maybe worth mentioning somewhere that indexing a single element is preferred over indexing a column
Think we can omit this from writing, but strongly reinforce it through our code statements

2022-12-03 10:26 UTC, sanchit-gandhi commented on audio-datasets.md
> +common_voice = load_dataset("mozilla-foundation/common_voice_11", "en", use_auth_token=True)
Resolved in https://github.com/huggingface/blog/pull/636/commits/2661666b7567417021436502a7d253b84b9284bb

2022-12-03 10:39 UTC, sanchit-gandhi commented on audio-datasets.md
> +prepare the most popular audio datasets in just one line of Python code.
Paraphrased it, but would still like to make the point that Datasets is the go-to place!

https://github.com/huggingface/blog/pull/636/commits/fd950f60da53fa109eb2813c009fd147e6096d86

2022-12-06 11:19 UTC, polinaeterna approved these changes
thank you for the streaming fix! looks more correct from the technical point of view now to me :) 

I have left a few small nits and a suggestion to add SpeechCommands and MLSpokenWords to the list of audio classification datasets. the first one used to be a classic one as far as I know and the second one is multilingual and big!

2022-12-06 11:19 UTC, polinaeterna commented on audio-datasets.md
> +### Audio Classification
oh I've missed that we also have [Speech Commands](https://huggingface.co/datasets/speech_commands) and [MLSpokenWords](https://huggingface.co/datasets/MLCommons/ml_spoken_words) for keyword spotting

2022-12-15 12:07 UTC, sanchit-gandhi commented on audio-datasets.md
> +### Audio Classification
Thanks for the suggestions! Resolved in https://github.com/huggingface/blog/pull/636/commits/2dbeaf12f4ae2c2e74c637636abf6e69bada7dba

2022-12-15 15:47 UTC, merged