First draft of Accelerated inference Blogpost.
huggingface/blog pull request #68
Opened 2020-12-30 12:55 UTC by Narsil

2021-01-06 17:06 UTC, clmnt commented
same feedback as for the documentation, if I'm a potential client reading this, I feel like I'll probably end up exploring pipelines as it's the first thing you redirect to. Also, it sounds like the optimizations are kind of doable/easy to do so I'm thinking that we should rather do it ourselves rather than pay for the API. What do you think @jeffboudier?

2021-01-06 17:10 UTC, julien-c requested changes

2021-01-06 17:10 UTC, julien-c commented on _blog.yml
> +  thumbnail: ./assets/accelerated-inference/thumbnail.png
can you nest the assets into a numbered folder like:

```suggestion
  thumbnail: ./assets/09_accelerated-inference/thumbnail.png
```

2021-01-06 17:10 UTC, julien-c commented on accelerated-inference.md
> +title: "Speeding up inference by 10-100x for 4000 models"
```suggestion
title: "Speeding up inference by 10-100x for 4000 models"
thumbnail: ./assets/09_accelerated-inference/thumbnail.png
```

2021-01-06 17:10 UTC, julien-c commented on accelerated-inference.md
> +title: "Speeding up inference by 10-100x for 4000 models"
add thumbnail here too so you get a nice social sharing thumbnail

2021-01-06 17:10 UTC, julien-c commented on accelerated-inference.md
> +# **Speeding up inference by 10-100x for 4000 models**
```suggestion
# **Speeding up inference by 10-100x for 5,000 models**
```

2021-01-06 17:10 UTC, julien-c commented on accelerated-inference.md
> +your own is that we provide with accelerated API that speeds up models by up to 100x (mostly likely 10x). This blogpost describes how we are achieving it.
```suggestion
your own is that we provide an accelerated API that speeds up models by up to 100x (mostly likely 10x). This blogpost describes how we are achieving it.
```

2021-01-06 17:10 UTC, julien-c commented on accelerated-inference.md
> +by using [pipelines](https://huggingface.co/transformers/main_classes/pipelines.html?highlight=pipelines) instead of coming up with your own code to run the inference.
```suggestion
by using [pipelines](https://huggingface.co/transformers/main_classes/pipelines.html?highlight=pipelines) instead of rolling out your own code to run the inference.
```

2021-01-06 17:10 UTC, julien-c commented on accelerated-inference.md
> +the most important part of it's success. The core of it, is that it's a NxN
```suggestion
the most important part of its success. The core of it, is that it's a NxN
```

2021-01-06 17:10 UTC, julien-c commented on accelerated-inference.md
> +the same principles can be also applied to GPU.
```suggestion
the same principles can also be applied to GPU.
```

2021-01-07 17:05 UTC, julien-c commented on _blog.yml
> +  date: January 07, 2021
```suggestion

# - local: accelerated-inference
#   title: Accelerated Inference (up to 100x speedup from naive implementations)
#   thumbnail: ./assets/09_accelerated_inference/thumbnail.png
#   date: January 07, 2021
```

2021-01-07 17:08 UTC, julien-c commented on accelerated-inference.md
> +thumbnail: ./assets/09_accelerated-inference/thumbnail.png
```suggestion
thumbnail: /blog/assets/09_accelerated_inference/thumbnail.png
```

2021-01-07 22:16 UTC, philschmid commented on accelerated-inference.md
> +that is implemented in Rust for performance.
Therefore we create a completely new performance-optimized `tokenizers` library implemented in Rust.

2021-01-07 22:16 UTC, philschmid commented on accelerated-inference.md
> +Tokenizing is also an operation that is likely to be cached in most inference situation
2 thats in the sentences again. 

either: an operation "which" is likely.... 
or: speedups of you do "it" correctly...

2021-01-07 22:16 UTC, philschmid commented on accelerated-inference.md
> +Overall the Fast tokenizers get a ~10x speedup for the tokenization part, so depending of
tokenizers achieves a ~10x speedup

2021-01-07 22:16 UTC, philschmid commented on accelerated-inference.md
> +For the last part of the speedup (another ~10x) we're going to need to dive
For the last part of the speedup (another ~10x) we are taking a deep dive into gory details

2021-01-07 22:16 UTC, philschmid commented on accelerated-inference.md
> +
a calculation with the values would be cool here -> how the 100x are achieved

2021-01-07 22:16 UTC, philschmid commented on accelerated-inference.md
> +your model with a runtime + quantization optimizations. And that the real trick
remove "And that"

2021-01-07 22:16 UTC, philschmid commented on accelerated-inference.md
> +To test all these optimizations right now, you can check out the results in our [Hosted API inference](https://huggingface.co/pricing). Be mindful that we require paid subscription for the accelerate
i would be a little more aggressive here. 

"To use all these optimizations, you can check out our [Inference API]. To give you a headstart we offer a 7-day free trial. After that, you can choose between 3 different subscription models. 
we not only optimizing all the models but scaling the API according to your needs up to thousands of concurrent requests. 
Besides, it is possible for you to switch between CPU and GPU with a simple parameter change. 
If you want to know more check out our [API product page](Dont have an link here -> pls add)

2021-01-08 14:14 UTC, mfuntowicz commented on accelerated-inference.md
> +inference speed on a simple CPU (GPU is only 40% faster, but it's 4x times the cost).
May be mention than GPU is still very attractive for cases where batching can happen?

2021-01-12 16:08 UTC, stefan-it commented on accelerated-inference.md
> +If you want to benefit from our experience optimizing inference on your own infrastructure, [contact us](mailto:api-enterprise@huggingface.co?subject:Expert%20Acceleration%20Program)! We can support
Hi @Narsil ,

I think the mailto link should be corrected, otherwise the subject would be empty:
```suggestion
If you want to benefit from our experience optimizing inference on your own infrastructure, [contact us](mailto:api-enterprise@huggingface.co?subject=Expert%20Acceleration%20Program)! We can support your team through the 🤗 Expert Acceleration Program.
```

2021-01-18 09:25 UTC, julien-c commented
Merging this, but @jeffboudier i feel like the call to action for subscription and/or Expert Acceleration program could be even more obvious

(maybe a form to input one's email address, and we then get in touch?)

cc @clmnt

2021-01-18 09:25 UTC, merged

2021-01-18 17:08 UTC, jeffboudier commented
Yes I want to create a landing page with lead capture form for premium
support

On Mon, Jan 18, 2021 at 1:26 AM Julien Chaumond <notifications@github.com>
wrote:

> Merging this, but @jeffboudier <https://github.com/jeffboudier> i feel
> like the call to action for subscription and/or Expert Acceleration program
> could be even more obvious
>
> (maybe a form to input one's email address, and we then get in touch?)
>
> cc @clmnt <https://github.com/clmnt>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/huggingface/blog/pull/68#issuecomment-762112605>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARWHZBJTLSE5LU3P6OF6LRDS2P5C3ANCNFSM4VOJRS3Q>
> .
>