Add switch blogpost
huggingface/blog pull request #682
Opened 2022-12-02 09:26 UTC by ArthurZucker

cc @ybelkada

2022-12-06 15:23 UTC, osanseviero reviewed
Cool blog post! I did a first pass

I found it quite technical (which is alright), but maybe it assumes too much background knowledge. Maybe some brief intro to what MoEs are would be useful here

2022-12-06 15:23 UTC, osanseviero commented on switch_transformers.md
> +    <small>Published December 2, 2022.</small>
To update

2022-12-06 15:23 UTC, osanseviero commented on switch_transformers.md
> +<a target="_blank" href="https://colab.research.google.com/drive/1aGGVHZmtKmcNBbAwa9hbu58DDpIuB5O4#scrollTo=xsgNPx4FrtH_">
Would be good to add the notebook to https://github.com/huggingface/blog/tree/main/notebooks

2022-12-06 15:23 UTC, osanseviero commented on switch_transformers.md
> +Mixture of Experts (MoE) -based models make their way to the Hugging Face ecosystem
```suggestion
Mixture of Experts (MoE) based models make their way to the Hugging Face ecosystem
```

2022-12-06 15:23 UTC, osanseviero commented on switch_transformers.md
> +If you are following the recent advances in NLP, you have probably heard about the sparse architecture called Mixture of Experts (MoE) models. Research on MoEs has been around for a few years, but th
Incomplete sentence

2022-12-06 15:23 UTC, osanseviero commented on switch_transformers.md
> +The model is now publicly available on Hugging Face Hub, making it the biggest model available.
Maybe add a link to the model repo

2022-12-06 15:23 UTC, osanseviero commented on switch_transformers.md
> +Let’s dive into the technical specifications of this architecture and how to train and evaluate your first MoE model using Hugging Face `transformers`! Let’s get started ! :hugs: :party:
```suggestion
Let’s dive into the technical specifications of this architecture and how to train and evaluate your first MoE model using 🤗  `transformers`! Let’s get started ! 🤗  🥳 
```

2022-12-06 15:23 UTC, osanseviero commented on switch_transformers.md
> +Switch Transformers in a nutshell
Should this be a heading?

2022-12-06 15:23 UTC, osanseviero commented on switch_transformers.md
> +In early concepts, the experts defined an entire neural network and the MoE was similar to ensemble methods.
What this sentence intended to say was not very clear to me

2022-12-06 15:23 UTC, osanseviero commented on switch_transformers.md
> +![MoE figure](/assets/119_switch_transformers/routing.png)
What's the source of this image?

2022-12-06 15:23 UTC, osanseviero commented on switch_transformers.md
> +As it can be seen on the figure above, the blue token is going to be ignored by the expert 1, even though it has been routed there since the expert has already reached its maximum expert capacity. Th
```suggestion
As seen in the figure above, Expert 1 will ignore the blue token as it has already reached its maximum capacity (even though the token was router there).  This will result in using the hidden state in the next stage as it is.
```

2022-12-06 15:23 UTC, osanseviero commented on switch_transformers.md
> +How to ensure the diversity of the routing mechanism, i.e, make sure that the distribution of routed experts is uniform. Some recent studies have shown that learning such a routing mechanism encourag
```suggestion
How can we ensure the diversity of the routing mechanism? I.e, make sure that the distribution of routed experts is uniform. Some recent studies have shown that learning such a routing mechanism encourages token clustering around expert centroids. A poor expert routing strategy can cause certain experts to be under-trained, leading to an expert being under or over-specialized.
```

2022-12-09 16:23 UTC, younesbelkada commented on switch_transformers.md
> +    <small>Published December 2, 2022.</small>
```suggestion
    <small>Published December 9, 2022.</small>
```

2022-12-09 16:23 UTC, younesbelkada commented on switch_transformers.md
> +![MoE figure](/assets/119_switch_transformers/routing.png)
```suggestion
| ![MoE figure](/assets/119_switch_transformers/routing.png) | 
|:--:|
| <b>Image source: https://arxiv.org/abs/2101.03961 </b>|
```

2022-12-09 16:29 UTC, younesbelkada commented on switch_transformers.md
> +If you are following the recent advances in NLP, you have probably heard about the sparse architecture called Mixture of Experts (MoE) models. Research on MoEs has been around for a few years, but th
```suggestion
If you are following the recent advances in NLP, you have probably heard about the sparse architecture called Mixture of Experts (MoE) models. Research on MoEs has been around for a few years, but the advance of huge clusters allowed the democratization of the architecture.
```
I don't think we expected a sentence there :/

2022-12-09 16:30 UTC, younesbelkada commented on switch_transformers.md
> +The model is now publicly available on Hugging Face Hub, making it the biggest model available.
```suggestion
The model is now publicly available on [Hugging Face Hub](https://huggingface.co/models?search=switch), making it the biggest model available.
```

2022-12-09 16:32 UTC, younesbelkada commented on switch_transformers.md
> +Switch Transformers in a nutshell
```suggestion
## Switch Transformers in a nutshell
```

2022-12-09 16:39 UTC, ArthurZucker commented on switch_transformers.md
> +The model is now publicly available on Hugging Face Hub, making it the biggest model available.
Yeah, makes sense!

2022-12-12 14:21 UTC, ArthurZucker commented on switch_transformers.md
> +## Mixture of Experts models in few words
```suggestion
## Mixture of Experts (MoE) models in a few words
```

2022-12-12 14:21 UTC, ArthurZucker commented on switch_transformers.md
> +Mixture of Experts (MoE) have been widely democratized by Shazeer et al. in the paper ["Outrageously Large Neural Networks: the Sparsely-Gated Mixture of Experts Layer"](https://openreview.net/pdf?id
```suggestion
Mixture of Experts (MoE) have been widely democratized by Shazeer et al. in the paper ["Outrageously Large Neural Networks: the Sparsely-Gated Mixture of Experts Layer"](https://openreview.net/pdf?id=B1ckMDqlg) - the main motivation behind the creation of these layers is the need to increase the number of parameters (therefore the model's capacity) with minor losses in computational efficiency. In the paper, authors claim to obtain greater than 1000x improvements in model capacity while observing a small loss in computational efficiency. 

The basic idea is to replace a single model that can take `N` inputs by `nb_expert` models, and chose for each input, which model will process it. This way, you are still only using `N` weights, but the number of weights that you can be using is `N x nb_experts` instead of `N`. 
```

2022-12-12 14:21 UTC, ArthurZucker commented on switch_transformers.md
> +Mixture of Experts (MoE) have been widely democratized by Shazeer et al. in the paper ["Outrageously Large Neural Networks: the Sparsely-Gated Mixture of Experts Layer"](https://openreview.net/pdf?id
Maybe this is even less technical so can keep it with your next description

2022-12-13 11:05 UTC, younesbelkada commented
Hi @osanseviero
Thanks so much for the review!
I beleive we have addressed your main comments, would love to have a second round of review 🙏

2023-01-05 11:07 UTC, sayakpaul requested changes
Thanks a lot for working on this and Switch Transformers! Really cool stuff!

2023-01-05 11:07 UTC, sayakpaul commented on switch_transformers.md
> +The models that have been publicly released are pre-trained on C4 dataset, on masked language modeling task. Therefore they are not ready to use as Flan-T5 for instance. One needs to fine-tune the mo
```suggestion
Switch Transformer checkpoints that have been publicly released were pre-trained on the [C4 dataset](https://huggingface.co/datasets/c4), with [masked language modeling](https://huggingface.co/tasks/fill-mask). Therefore they are not ready to use in a sequence-to-sequence formulation such as [Flan-T5](https://huggingface.co/docs/transformers/model_doc/flan-t5), for instance. One needs to fine-tune the models to a task of preference before using it. However, the authors published some results of the fine-tuned checkpoints and the results seem to be better than classic T5 models.
```

2023-01-05 11:07 UTC, sayakpaul commented on switch_transformers.md
> +Together with the Trillion parameter model, google has released a set of smaller models so that anyone can experiment with this architecture, check them out here: https://huggingface.co/models?sort=d
I suggest adding this note after showing the code:

> Together with the Trillion parameter model, google has released a set of smaller models so that anyone can experiment with this architecture, check them out here: https://huggingface.co/models?sort=downloads&search=google%2Fswitch-

2023-01-05 11:07 UTC, sayakpaul commented on switch_transformers.md
> +If you are interested in training your first MoE, please checkout the [fine tuning google colab script](https://colab.research.google.com/drive/1aGGVHZmtKmcNBbAwa9hbu58DDpIuB5O4#scrollTo=xsgNPx4FrtH_
```suggestion
If you are interested in training your first MoE-based model, please check out this [Colab Notebook](https://colab.research.google.com/drive/1aGGVHZmtKmcNBbAwa9hbu58DDpIuB5O4#scrollTo=xsgNPx4FrtH_). It shows you how to fine-tune a Switch Transformer model for summarization and how you can easily share the fine-tuned model on the Hugging Face Hub.
```

2023-01-05 11:07 UTC, sayakpaul commented on switch_transformers.md
> +If you are interested in training your first MoE, please checkout the [fine tuning google colab script](https://colab.research.google.com/drive/1aGGVHZmtKmcNBbAwa9hbu58DDpIuB5O4#scrollTo=xsgNPx4FrtH_
Also change the Colab Notebook link with one added in this PR.

2023-01-05 11:07 UTC, sayakpaul commented on switch_transformers.md
> +- More MoE-related papers and code: https://github.com/XueFuzhao/awesome-mixture-of-experts
Maybe repurpose this section to also add a conclusion first and then a list of references for further reading?

2023-03-02 10:57 UTC, ArthurZucker commented
Thanks a lot for your review and sorry for this long delay! Had my hands full, but should be able to adress your comments! :wink

2023-04-14 10:35 UTC, osanseviero commented
Should this PR be merged?

2023-04-14 11:34 UTC, ArthurZucker commented
Thing I adressed most of the comments, so if it is alright with you, sure! Was thinking of maybe adding a mention to the NLLB-MoE models too, didn't have the bandwidth to do so yet

2023-08-18 11:46 UTC, closed without merging

2023-08-18 11:47 UTC, ArthurZucker commented
Bit outdated and don't have time to do this! Does not seem like it was requested anyway!