Add header about Infinity deprecation redirecting to other solutions
huggingface/blog pull request #695
Opened 2022-12-05 15:16 UTC by fxmarty

Following: https://github.com/huggingface/blog/issues/675

2022-12-05 15:38 UTC, julien-c requested changes

2022-12-05 16:50 UTC, julien-c commented on infinity-cpu-performance.md
> +<div class="infobox">
yes i don't think it's ideal

2022-12-06 02:05 UTC, jeffboudier reviewed
Thanks for starting this PR! Suggested some copy.

2022-12-06 02:05 UTC, jeffboudier commented on infinity-cpu-performance.md
> +  * Our team can assist you in the optimizations for training and inference! Reach out to us through the [Expert Acceleration Program](https://huggingface.co/support).
```suggestion
  Infinity is no longer offered by Hugging Face as a commercial inference solution. To deploy and accelerate your models, we recommend the following new solutions:

  * [Inference Endpoints](https://huggingface.co/docs/inference-endpoints/index) to easily deploy models on dedicated infrastructure managed by Hugging Face

  * Our open source acceleration libraries [🤗 Optimum Intel](https://huggingface.co/blog/openvino) and [🤗 Optimum ONNX Runtime](https://huggingface.co/docs/optimum/main/en/onnxruntime/overview) to accelerate your models on CPU.

  * Hugging Face [Expert Acceleration Program](https://huggingface.co/support), a commercial service for Hugging Face experts to work directly with your team to accelerate your Machine Learning roadmap and models. 
```

2022-12-06 09:10 UTC, fxmarty commented on infinity-cpu-performance.md
> +<div class="infobox">
done

2022-12-06 09:10 UTC, fxmarty commented
Thanks!

2022-12-06 11:18 UTC, julien-c reviewed
can you share a screenshot of what it looks like, if you have one?

Thanks!

2022-12-06 13:43 UTC, fxmarty commented
I'm not sure if it will work since there is no preview available for the blog, but:

![image](https://user-images.githubusercontent.com/9808326/205928221-09d92fdc-2765-4705-801f-e4e268c7cfa3.png)


![image](https://user-images.githubusercontent.com/9808326/205928351-7bf28534-b1fd-40c1-8c16-b42dc42c5310.png)

2022-12-12 11:01 UTC, fxmarty commented
@julien-c @jeffboudier How does it sound?

2022-12-12 12:38 UTC, philschmid commented
@fxmarty you should be able to run the blog locally using codespaces.

2022-12-12 13:36 UTC, fxmarty commented
Awesome thanks for the recommentation, it works!

Here's how it looks like (did not manage to have the bullets in black):

![image](https://user-images.githubusercontent.com/9808326/207058078-ff1f6b0a-9c1b-4bf8-850a-644b73a78e5f.png)

2022-12-13 04:07 UTC, jeffboudier requested changes
lgtm! Thanks for the screenshot. Made a suggestion to contextualize the inserted block.

2022-12-13 04:07 UTC, jeffboudier commented on infinity-cpu-performance.md
> +  Infinity is no longer offered by Hugging Face as a commercial inference solution. To deploy and accelerate your models, we recommend the following new solutions:
```suggestion
  December 2022 Update: Infinity is no longer offered by Hugging Face as a commercial inference solution. To deploy and accelerate your models, we recommend the following new solutions:
```

2022-12-13 08:25 UTC, fxmarty commented
@jeffboudier can you approve?

2022-12-13 08:37 UTC, philschmid commented
Maybe @stevhliu can also take a look regarding the language and @Reeray if he has some UI improvements, i think there is room to improve to better fit the Hub design.

2022-12-13 18:05 UTC, stevhliu reviewed
Looks good to me!

2022-12-16 15:13 UTC, fxmarty commented
Let me know if there is anything I should do.

2023-01-31 16:29 UTC, julien-c approved these changes
lgtm

2023-02-02 14:52 UTC, merged