Zero-shot image segmentation with CLIPSeg
huggingface/blog pull request #740
Opened 2022-12-16 16:45 UTC by segments-tobias

Hi all! I'm back with another blog post written by @NielsRogge and myself.
The blog post aims to do the following:

- Introduce segmentation and zero-shot segmentation
- Explain how CLIP and CLIPSeg work
- Show how people can use CLIPSeg with `transformers` for both text **and image** prompts
- Show how to combine multiple outputs of CLIPSeg and upload this result to a labeling platform ([Segments.ai](segments.ai) in this case) for further refinement

2022-12-17 21:39 UTC, osanseviero commented
@nateraw and @sayakpaul would you be up for reviewing this blog post? :D

2022-12-18 06:17 UTC, sayakpaul commented
I will review it :)

2022-12-19 04:01 UTC, sayakpaul requested changes
Thanks for the great work! 

I really enjoyed the step-by-step instructions and the bit on programmatic label refinement. 

Some minor comments to address and we should be good to ship this 🚀

2022-12-19 09:19 UTC, segments-tobias commented on clipseg-zero-shot.md
> +thumbnail: /blog/assets/123_clipseg-zero-shot/thumb.png
Done! [https://huggingface.co/datasets/huggingface/documentation-images/discussions/18](https://huggingface.co/datasets/huggingface/documentation-images/discussions/18)

Do the image urls stay the same, or should I change them?

2022-12-19 09:43 UTC, segments-tobias commented on clipseg-zero-shot.md
> +[CLIPSeg](https://arxiv.org/abs/2112.10003) is a model that uses CLIP representations to create image segmentation masks. It was published by Timo Lüddecke and Alexander Ecker. They achieved zero-sho
So as I try to explain two paragraphs later, you can either input a piece of text (e.g. "an orange"), or a picture (of an orange) to segment oranges in a picture (e.g. of an orange tree). Will try to clarify more in that paragraph!

2022-12-19 10:00 UTC, segments-tobias commented on clipseg-zero-shot.md
> +## Text prompting
Good catch

2022-12-19 10:14 UTC, segments-tobias commented on clipseg-zero-shot.md
> +  <medium-zoom background="rgba(0,0,0,.7)" alt="Colab output" src="assets/123_clipseg-zero-shot/14c048ea92645544c1bbbc9e55f3c620eaab8886.png"></medium-zoom>
I'll properly add alt texts. I don't think the image names are very important, since they won't have to be touched anymore.

2022-12-19 10:19 UTC, segments-tobias commented on clipseg-zero-shot.md
> +One interesting feature of CLIPSeg is that we input a CLIP embedding to specify which thing we want to segment. This CLIP embedding can come from a word or a piece of text, but also from another imag
Let me know what you think of the new paragraphs I wrote.

2022-12-19 10:21 UTC, segments-tobias commented
Thanks @sayakpaul for the review. I fixed your comments and created a PR for the assets.
Let me know if you have any other comments!

2022-12-19 10:23 UTC, sayakpaul commented on clipseg-zero-shot.md
> +thumbnail: /blog/assets/123_clipseg-zero-shot/thumb.png
Thank you so much!

You need to change the URLs accordingly.

2022-12-19 10:44 UTC, segments-tobias commented on clipseg-zero-shot.md
> +thumbnail: /blog/assets/123_clipseg-zero-shot/thumb.png
Updated them now :)

2022-12-19 10:55 UTC, sayakpaul approved these changes
Awesome! LGTM from my end.

2022-12-21 11:34 UTC, NielsRogge commented on clipseg-zero-shot.md
> +**This guide shows how you can use [CLIPSeg](https://arxiv.org/abs/2112.10003), a zero-shot image segmentation model, using [`🤗 transformers`](https://huggingface.co/transformers). CLIPSeg creates ro
```suggestion
**This guide shows how you can use [CLIPSeg](https://huggingface.co/docs/transformers/main/en/model_doc/clipseg), a zero-shot image segmentation model, using [`🤗 transformers`](https://huggingface.co/transformers). CLIPSeg creates rough segmentation masks that can be used for robot perception, image inpainting, and many other tasks. If you need more precise segmentation masks, we’ll show how you can refine the results of CLIPSeg on [Segments.ai](https://segments.ai/?utm_source=hf&utm_medium=blog&utm_campaign=clipseg).**
```

2022-12-21 11:37 UTC, NielsRogge commented on clipseg-zero-shot.md
> +[CLIP](https://openai.com/blog/clip/), which stands for **C**ontrastive **L**anguage–**I**mage **P**re-training, is a model developed by OpenAI in 2021. You can give CLIP an image or a piece of text,
```suggestion
[CLIP](https://huggingface.co/docs/transformers/main/en/model_doc/clip), which stands for **C**ontrastive **L**anguage–**I**mage **P**re-training, is a model developed by OpenAI in 2021. You can give CLIP an image or a piece of text, and CLIP will output an abstract *representation* of your input. This abstract representation, also called an *embedding*, is really just a vector (a list of numbers). You can think of this vector as a point in high-dimensional space. CLIP is trained so that the representations of similar pictures and texts are similar as well. This means that if we input an image and a text description that fits that image, the representations of the image and the text will be similar (i.e., the high-dimensional points will be close together).
```

2022-12-21 11:38 UTC, NielsRogge commented on clipseg-zero-shot.md
> +[CLIPSeg](https://arxiv.org/abs/2112.10003) is a model that uses CLIP representations to create image segmentation masks. It was published by Timo Lüddecke and Alexander Ecker. They achieved zero-sho
```suggestion
[CLIPSeg](https://arxiv.org/abs/2112.10003) is a model that uses CLIP representations to create image segmentation masks. It was published by Timo Lüddecke and Alexander Ecker. They achieved zero-shot image segmentation by training a Transformer-based decoder on top of the CLIP model, which is kept frozen. The decoder takes in the CLIP representation of an image, and the CLIP representation of the thing you want to segment. Using these two inputs, the CLIPSeg decoder creates a binary segmentation mask. To be more precise, the decoder doesn’t only use the final CLIP representation of the image we want to segment, but it also uses the outputs of some of the layers of CLIP. 
```

2022-12-21 11:42 UTC, NielsRogge commented on clipseg-zero-shot.md
> +prompt_alt
```suggestion
alternative_prompt = Image.open(requests.get(url, stream=True).raw)
alternative_prompt
```

2022-12-21 11:42 UTC, NielsRogge commented on clipseg-zero-shot.md
> +preds = torch.transpose(preds, 0, 1)
```suggestion
encoded_alternative_prompt = processor(images=[alternative_prompt], return_tensors="pt")
# predict
with torch.no_grad():
  outputs = model(**encoded_image, conditional_pixel_values=encoded_alternative_prompt.pixel_values)
preds = outputs.logits.unsqueeze(1)
preds = torch.transpose(preds, 0, 1)
```

2022-12-21 11:42 UTC, NielsRogge commented on clipseg-zero-shot.md
> +the best labeling platform for image segmentation.
:D

2022-12-21 11:46 UTC, NielsRogge commented on clipseg-zero-shot.md
> +CLIPSeg is a zero-shot segmentation model that works with both text and image prompts. The model adds a decoder to CLIP and can segment almost anything. However, the output segmentation masks are sti
```suggestion
CLIPSeg is a zero-shot segmentation model that works with both text and image prompts. The model adds a decoder to CLIP and can segment almost anything. However, the output segmentation masks are still very low-res for now, so you’ll probably still want to fine-tune a different segmentation model. Note that there's a lot of research going on to leverage CLIP for zero-shot segmentation, among which [GroupViT](https://huggingface.co/docs/transformers/model_doc/groupvit) which is also available in 🤗 Transformers. One can expect more models to be added in the near future.
```

2022-12-21 11:47 UTC, NielsRogge approved these changes
Awesome blog, thanks for all your work! 🙏

2022-12-21 11:50 UTC, sayakpaul commented on clipseg-zero-shot.md
> +the best labeling platform for image segmentation.
I forgot to come back to this one. 

@segments-tobias we usually try to avoid phrases like "best".

2022-12-21 11:51 UTC, sayakpaul commented
@osanseviero 

@NielsRogge and I have reviewed and approved the blog post. Once the suggestions from Niels are reflected, I think the post can be safely merged and shipped.

2022-12-21 11:54 UTC, NielsRogge commented on clipseg-zero-shot.md
> +the best labeling platform for image segmentation.
No it's totally fine for me!

2022-12-21 12:03 UTC, segments-tobias commented on clipseg-zero-shot.md
> +CLIPSeg is a zero-shot segmentation model that works with both text and image prompts. The model adds a decoder to CLIP and can segment almost anything. However, the output segmentation masks are sti
Rewrote this a little bit, can you check once more @NielsRogge ?

2022-12-21 12:11 UTC, segments-tobias commented
I added the post to `_blog.yaml` and updated the publish date to today, so it should be good to go.

2022-12-21 12:14 UTC, segments-tobias commented on clipseg-zero-shot.md
> +the best labeling platform for image segmentation.
Lmk if you still want me to change it @sayakpaul

2022-12-21 13:50 UTC, sayakpaul commented on clipseg-zero-shot.md
> +the best labeling platform for image segmentation.
Appreciate your understanding. Thank you!

2022-12-21 13:53 UTC, osanseviero approved these changes
I checked that the blog format and directories are alright. As Niels and Sayak already reviewed, I'm approving!

2022-12-21 13:53 UTC, NielsRogge commented on clipseg-zero-shot.md
> +CLIPSeg is a zero-shot segmentation model that works with both text and image prompts. The model adds a decoder to CLIP and can segment almost anything. However, the output segmentation masks are sti
LGTM 👍

2022-12-21 13:53 UTC, merged

2022-12-21 13:54 UTC, osanseviero commented
https://huggingface.co/blog/clipseg-zero-shot cool blog! Congrats :fire:

2022-12-21 14:41 UTC, NielsRogge commented
@segments-tobias could you open a PR to incorporate [this update](https://github.com/huggingface/transformers/pull/20816)?

2022-12-21 16:20 UTC, segments-tobias commented
Done, see [https://github.com/huggingface/blog/pull/748](https://github.com/huggingface/blog/pull/748)