Intro to graph ML blog post
huggingface/blog pull request #756
Opened 2022-12-23 11:47 UTC by clefourrier

Work in progress:

- [ ] needs a thumbnail > no idea what to put in it
- [ ] needs to make sure images are integrated properly > how can I check this?
- [ ] ideally needs some feedback on how understandable it is from someone who has not touched graph ML before > @omarespejel if you have the time?

2022-12-23 12:15 UTC, sayakpaul commented
Thank you for opening this PR, @clefourrier!

I don't know a thing about Graph ML. Can take a look during the weekend and share my comments. 

> needs to make sure images are integrated properly > how can I check this?

You can check [this section](https://github.com/huggingface/moon-landing#codespace) to get a preview of your blog post.

2022-12-23 15:58 UTC, clefourrier commented
That would be great, ty!

I'll look at the section you linked :)

On Fri, Dec 23, 2022 at 1:15 PM Sayak Paul ***@***.***> wrote:

> Thank you for opening this PR, @clefourrier
> <https://github.com/clefourrier>!
>
> I don't know a thing about Graph ML. Can take a look during the weekend
> and share my comments.
>
> needs to make sure images are integrated properly > how can I check this?
>
> You can check this section
> <https://github.com/huggingface/moon-landing#codespace> to get a preview
> of your blog post.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/huggingface/blog/pull/756#issuecomment-1363905880>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFNMROBVATBFWYEAMBUW2A3WOWJXLANCNFSM6AAAAAATHVBAL4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-26 04:05 UTC, sayakpaul requested changes
Excellent blog post! Really great content and dissemination of information. I learned tons. 

I mostly left styling nits and other minor suggestions.

2022-12-26 04:05 UTC, sayakpaul commented on intro-graphml.md
> +Here are some methods which seemed interesting to me, and which got SOTA or close on one of the hardest available benchmarks as of writing, Stanford's Open Graph Benchmark:
```suggestion
Here are some interesting methods which got state-of-the-art results or close on one of the hardest available benchmarks as of writing, [Stanford's Open Graph Benchmark](https://ogb.stanford.edu/):
```

2022-12-26 04:05 UTC, sayakpaul commented on intro-graphml.md
> +- *Global Self-Attention as a Replacement for Graph Convolution* (Hussain et al, 2021) introduced the Edge Augmented Transformer. This architecture embeds nodes and edges separately, and aggregates t
Hyperlink each of the papers?

2022-12-26 04:05 UTC, sayakpaul commented on intro-graphml.md
> +My favorites are:
Needs rewording. :D

2022-12-28 09:22 UTC, clefourrier commented on intro-graphml.md
> +A node through the first layer, is the aggregation of its direct neighbours. Through the second layer, it is still the aggregation of its direct neighbours, but this time, their representations now i
Because, after n layers, the representation of all nodes becomes an aggregation of all their neighbours at distance n, therefore, of the full graph, if its diameter is smaller than n - is this explanation better, or should i go step by step with examples?

2022-12-28 09:24 UTC, clefourrier commented on intro-graphml.md
> +A Transformer without its positional encoding layer is permutation invariant, and Transformers are known to scale well, so recently, people have started looking at adapting Transformers to graphs ([S
I think it's because no general architecture has been found at the moment for graphs, much like in NLP a decade ago, where neural methods were augmented with rule based/statistical features - do you think this should be mentioned?

2022-12-28 09:25 UTC, clefourrier commented on intro-graphml.md
> +My favorites are:
The last sentence? ^^

2022-12-28 09:27 UTC, clefourrier commented on intro-graphml.md
> +*On the right, the Hugging Face - on the left, a shuffled Hugging Face, which is quite a different new image.*
Is there a usual way to format captions in HFs blog posts? (it's supposed to be the caption of the above image)

2022-12-28 09:28 UTC, clefourrier commented on intro-graphml.md
> +Examples of graphs include social networks (Twitter, Mastodon, any citation networks linking papers and authors), molecules, knowledge graphs (such as UML diagrams, encyclopedias, any website with hy
Add an extra line between the "intro sentence" and the following paragraph?

2022-12-28 09:31 UTC, clefourrier commented on intro-graphml.md
> +Once you have node-level representations, it is possible to obtain edge or graph level information from it. For edge level information, you can simply concatenate node pair representations, or simply
Exactly! I will rephrase it.

2022-12-28 09:32 UTC, clefourrier commented on intro-graphml.md
> +Pre-neural networks, graphs and their items of interests could be represented as combination of features, in a task specific fashion. (Now, these features are used for data augmentation and semi-supe
To the general definitions in wikipedia, or to specific papers in graph ML?

2022-12-28 09:34 UTC, clefourrier commented on intro-graphml.md
> +Node-level features can give information about importance (how important is this node for the graph?) and/or structure based (what is the shape of the graph around the node?), and can be combined.
There are also edge and graph level features, I will add them back (I removed them to focus on node representation for clarity, but exhaustivity is possibly better)

2022-12-28 09:40 UTC, clefourrier commented on intro-graphml.md
> +    - Explanation: permuting the nodes before processing should be equivalent to permuting their representations
Would "permuting the nodes before passing them to the network should be equivalent to permuting their representations" be clearer?

2022-12-28 14:28 UTC, sayakpaul commented on intro-graphml.md
> +Examples of graphs include social networks (Twitter, Mastodon, any citation networks linking papers and authors), molecules, knowledge graphs (such as UML diagrams, encyclopedias, any website with hy
Yes, that's right.

2022-12-28 14:30 UTC, sayakpaul commented on intro-graphml.md
> +*On the right, the Hugging Face - on the left, a shuffled Hugging Face, which is quite a different new image.*
I don't believe so. You can follow an example markdown [here](https://raw.githubusercontent.com/huggingface/blog/main/clipseg-zero-shot.md) to see how the authors have used the `<figure>` tag to put in captions.

2022-12-28 14:31 UTC, sayakpaul commented on intro-graphml.md
> +Pre-neural networks, graphs and their items of interests could be represented as combination of features, in a task specific fashion. (Now, these features are used for data augmentation and semi-supe
Sorry for being unclear here and there. Deeply apologize. 

I meant hyperlinks specific to graph ML.

2022-12-28 14:31 UTC, sayakpaul commented on intro-graphml.md
> +    - Explanation: permuting the nodes before processing should be equivalent to permuting their representations
Yes. Much more explicit and clear.

2022-12-28 14:33 UTC, sayakpaul commented on intro-graphml.md
> +A node through the first layer, is the aggregation of its direct neighbours. Through the second layer, it is still the aggregation of its direct neighbours, but this time, their representations now i
I think this is better. If there's any visual depiction you can present via a figure, feel free to add it (not a must-have IMO).

2022-12-28 14:34 UTC, sayakpaul commented on intro-graphml.md
> +My favorites are:
Yeah. In the blog post, "My" and similar phrases could be avoided.

2023-01-02 07:59 UTC, clefourrier commented on intro-graphml.md
> +Pre-neural networks, graphs and their items of interests could be represented as combination of features, in a task specific fashion. (Now, these features are used for data augmentation and semi-supe
Absolutely not a problem, thank you so much for having taken the time to go through this!

2023-01-02 07:59 UTC, clefourrier commented on intro-graphml.md
> +Pre-neural networks, graphs and their items of interests could be represented as combination of features, in a task specific fashion. (Now, these features are used for data augmentation and semi-supe
I'll see if I have specific references that I have read on the topic.

2023-01-02 14:18 UTC, sayakpaul commented
@clefourrier the changes look good to me. Thanks so much!

2023-01-02 14:33 UTC, clefourrier commented
@sayakpaul Thank you so much for your reviews, it was great seeing what was clear and what was not! 

I'm a bit short on time atm but I'll add the images in the week and ping you again - do you have suggestions for the thumbnail?

2023-01-02 14:39 UTC, sayakpaul commented
> do you have suggestions for the thumbnail?

At this point, I don't but I will ping here if I have something. Also pinging @osanseviero if he has anything.

2023-01-02 16:48 UTC, osanseviero commented
@sayakpaul I re-requested review as you were in state "change requested" which would block merging. I'll be reviewing this now and once @clefourrier is happy with it, we can merge tomorrow or Wednesday :)

2023-01-02 17:13 UTC, sayakpaul approved these changes
LGTM (actually looks amazing) content-wise. 

Some small things that are pending: 

* We need the images to be in `documentation-images` repo which @clefourrier will work on. 
* Thumbnail (brainstorming this sub-consciously haha). 
* Resolution of the conflicts.

2023-01-02 19:19 UTC, osanseviero approved these changes
That is a very cool blog post!! :fire: I left lots of very minor suggestions, most of them are small changes to facilitate the reading. Great post! :rocket:

2023-01-02 19:19 UTC, osanseviero commented on intro-graphml.md
> +The usual process to work on graphs with machine learning is to, first, generate a meaningful representation for your items of interest (which can be nodes, edges, or full graphs depending on your ta
```suggestion
The usual process to work on graphs with machine learning is first to generate a meaningful representation for your items of interest (nodes, edges, or full graphs, depending on your task), then use these to train a predictor for your target task. We want (as in other modalities) to constrain the mathematical representations of your objects so that similar objects are mathematically close. However, the similarity is hard to define strictly in graph ML: for example, are two nodes more similar when they have the same labels or the same neighbors?
```

2023-01-02 19:19 UTC, osanseviero commented on intro-graphml.md
> +Once you have node-level representations, it is possible to obtain edge or graph-level information from it. For edge-level information, you can simply concatenate node pair representations or simply
```suggestion
Once you have node-level representations, it is possible to obtain edge or graph-level information. For edge-level information, you can concatenate node pair representations or do a dot product. For graph-level information, it is possible to do a global pooling (average, sum, etc.) on the concatenated tensor of all the node-level representations. Still, it will smooth and lose information over the graph -- a recursive hierarchical pooling can make more sense, or add a virtual node, connected to all other nodes in the graph, and use its representation as the overall graph representation.*
```

2023-01-02 19:19 UTC, osanseviero commented on intro-graphml.md
> +Pre-neural networks, graphs and their items of interests could be represented as combination of features, in a task specific fashion. Now, these features are still used for data augmentation and [sem
```suggestion
Pre-neural networks, graphs, and their items of interest could be represented as a combination of features in a task-specific fashion. Now, these features are still used for data augmentation and [semi-supervised learning](https://arxiv.org/abs/2202.08871), though [more complex feature generation methods](https://arxiv.org/abs/2208.11973) exist; they can be essential to find how best to provide them to your network depending on your task. 
```

2023-01-02 19:19 UTC, osanseviero commented on intro-graphml.md
> +The node **centrality** measures the node importance in the graph. It can be computed recursively by summing the centrality of each node’s neighbours until convergence, or through shortest distance m
```suggestion
The node **centrality** measures the node importance in the graph. It can be computed recursively by summing the centrality of each node’s neighbors until convergence, or through shortest distance measures between nodes, for example. The node **degree** is the number of direct neighbors it has. The **clustering coefficient** measures how connected the node neighbors are. **Graphlets degree vectors** count how many different graphlets are rooted at a given node, where graphlets are all the mini graphs you can create with a given number of connected nodes (with three connected nodes, you can have a line with two edges or a triangle with three edges).
```

2023-01-02 19:19 UTC, osanseviero commented on intro-graphml.md
> +**Graph level features** contain high-level information about graph similiarity and specificities. Total **graphlet counts**, though computationally expensive, provide information about the shape of
```suggestion
**Graph level features** contain high-level information about graph similarity and specificities. Total **graphlet counts**, though computationally expensive, provide information about the shape of sub-graphs. **Kernel methods** measure similarity between graphs through different "bag of nodes" methods (similar to bag of words).
```

2023-01-02 19:19 UTC, osanseviero commented on intro-graphml.md
> +[**Walk-based approaches**](https://en.wikipedia.org/wiki/Random_walk) use the probability of visiting a node j from a node i on a random walk to define similarity metrics; these approaches combine b
```suggestion
[**Walk-based approaches**](https://en.wikipedia.org/wiki/Random_walk) use the probability of visiting a node j from a node i on a random walk to define similarity metrics; these approaches combine both local and global information. [**Node2Vec**](https://snap.stanford.edu/node2vec/), for example, simulates random walks between nodes of a graph, then processes these walks with a skip-gram, [much like we would do with words in sentences](https://arxiv.org/abs/1301.3781), to compute embeddings. These approaches can also be used to [accelerate computations](https://arxiv.org/abs/1208.3071) of the [**Page Rank method**](http://infolab.stanford.edu/pub/papers/google.pdf), which assigns an importance score to each node (based on its connectivity to other nodes, evaluated as its frequency of visit by random walk, for example).
```

2023-01-02 19:19 UTC, osanseviero commented on intro-graphml.md
> +Neural networks can (hopefully) generalise to unseen data. What should a good neural network be, to work on graphs, given the representation constraints we evoked earlier?
```suggestion
Neural networks can generalize to unseen data. Given the representation constraints we evoked earlier, what should a good neural network be to work on graphs?
```

2023-01-02 19:19 UTC, osanseviero commented on intro-graphml.md
> +A GNN is made of successive layers. A GNN layer represents a node as the combination (**aggregation**) of the representations of its neighbours and itself from the previous layer (**message passing**
```suggestion
A GNN is made of successive layers. A GNN layer represents a node as the combination (**aggregation**) of the representations of its neighbors and itself from the previous layer (**message passing**), plus usually an activation to add some nonlinearity.
```

2023-01-02 19:19 UTC, osanseviero commented on intro-graphml.md
> +**Comparison to other models**: A CNN can be seen as a GNN with fixed neighbour sizes (through the sliding window) and ordering (it is not permutation equivariant). A [Transformer](https://arxiv.org/
```suggestion
**Comparison to other models**: A CNN can be seen as a GNN with fixed neighbor sizes (through the sliding window) and ordering (it is not permutation equivariant). A [Transformer](https://arxiv.org/abs/1706.03762v3) without positional embeddings can be seen as a GNN on a fully-connected input graph.
```

2023-01-02 19:19 UTC, osanseviero commented on intro-graphml.md
> +There are many ways to aggregate messages from neighbour nodes, summing, averaging, for example. Some notable works following this idea include:
```suggestion
There are many ways to aggregate messages from neighbor nodes, summing, averaging, for example. Some notable works following this idea include:
```

2023-01-02 19:19 UTC, osanseviero commented on intro-graphml.md
> +- [Graph Isomorphism Networks](https://arxiv.org/pdf/1810.00826v3.pdf) aggregates representation by applying an MLP to the sum of the neighbours node representations.
```suggestion
- [Graph Convolutional Networks](https://tkipf.github.io/graph-convolutional-networks/) averages the normalized representation of the neighbors for a node (most GNNs are actually GCNs);
- [Graph Attention Networks](https://petar-v.com/GAT/) learn to weigh the different neighbors based on their importance (like transformers);
- [GraphSAGE](https://snap.stanford.edu/graphsage/) samples neighbors at different hops before aggregating their information in several steps with max pooling.
- [Graph Isomorphism Networks](https://arxiv.org/pdf/1810.00826v3.pdf) aggregates representation by applying an MLP to the sum of the neighbors' node representations.
```

2023-01-02 19:19 UTC, osanseviero commented on intro-graphml.md
> +A node, through the first layer, is the aggregation of its direct neighbours. Through the second layer, it is still the aggregation of its direct neighbours, but this time, their representations now
```suggestion
A node, through the first layer, is the aggregation of its direct neighbors. Through the second layer, it is still the aggregation of its direct neighbors, but this time, their representations now include their neighbors (from the first layer). After n layers, the representation of all nodes becomes an aggregation of all their neighbors at distance n, therefore, of the full graph if its diameter is smaller than n! 
```

2023-01-02 19:19 UTC, osanseviero commented on intro-graphml.md
> +If your network had too many layers, there is therefore a risk that each node becomes an aggregation of the full graph (and that node representations converge to the same one for all nodes). This is
```suggestion
If your network has too many layers, there is a risk that each node becomes an aggregation of the full graph (and that node representations converge to the same one for all nodes). This is called **the oversmoothing problem**
```

2023-01-02 19:19 UTC, osanseviero commented on intro-graphml.md
> +A Transformer without its positional encoding layer is permutation invariant, and Transformers are known to scale well, so recently, people have started looking at adapting Transformers to graphs ([S
```suggestion
A Transformer without its positional encoding layer is permutation invariant, and Transformers are known to scale well, so recently, people have started looking at adapting Transformers to graphs ([Survey)](https://github.com/ChandlerBang/awesome-graph-transformer). Most methods focus on the best ways to represent graphs by looking for the best features and best ways to represent positional information and changing the attention to fit this new data.
```

2023-01-02 19:19 UTC, osanseviero commented on intro-graphml.md
> +Nice librairies to work on graphs are [PyGeometric](https://pytorch-geometric.readthedocs.io/en/latest/) (for graph ML) and [NetworkX](https://networkx.org/) (to manipulate graphs more generally).
```suggestion
Nice libraries to work on graphs are [PyGeometric](https://pytorch-geometric.readthedocs.io/en/latest/) (for graph ML) and [NetworkX](https://networkx.org/) (to manipulate graphs more generally).
```

2023-01-03 07:39 UTC, clefourrier commented on intro-graphml.md
> +- [Graph Isomorphism Networks](https://arxiv.org/pdf/1810.00826v3.pdf) aggregates representation by applying an MLP to the sum of the neighbours node representations.
Is there a preference for American English over British English?

2023-01-03 09:43 UTC, clefourrier commented
Took into account all of your comments, except that I chose to use GB English rather than US English.

All images were pushed to the correct repos (I hope :sweat_smile: ) and thumbnail was updated.

We should be good to go! :hugs:

2023-01-03 09:55 UTC, sayakpaul commented on _blog.yml
> +- local: intro-graphml
Since the images have been added [here](https://huggingface.co/datasets/huggingface/documentation-images/tree/main/blog/125_intro-to-graphml), resolving this comment :)

2023-01-03 10:04 UTC, merged