Graph classification tutorial post
huggingface/blog pull request #781
Opened 2023-01-16 12:50 UTC by clefourrier

Tutorial blog post for the graph classification task.

@sayakpaul I would love any feedback on how clear it is/if context is missing/... :hugs: 

Careful, this **must not** be merged before Transformers integrates Graphormer (= https://github.com/huggingface/transformers/pull/20968 gets closed) and the blog post gets updated if needed.

2023-01-16 13:34 UTC, sayakpaul commented
Thanks for working on this. Add this to my TODO.

2023-01-17 08:41 UTC, sayakpaul commented
Just a heads up that, I will get to the PR review by early next week.

2023-01-17 08:42 UTC, clefourrier commented
No hurry! :hugs:

2023-01-17 14:09 UTC, osanseviero reviewed
Nice!

2023-01-17 14:09 UTC, osanseviero commented on graphml-classification.md
> +Loading a graph dataset from the hub is very easy. Let's load the `ogbg-mohiv` dataset (a baseline from the Open Graph Benchmark by Stanford), stored in the `graphs-datasets` repository:
```suggestion
Loading a graph dataset from the Hub is very easy. Let's load the `ogbg-mohiv` dataset (a baseline from the Open Graph Benchmark by Stanford), stored in the `graphs-datasets` repository: 
```

2023-01-17 14:09 UTC, osanseviero commented on graphml-classification.md
> +Graph transformer frameworks usually apply specific preprocessing to their datasets, to generate added features and properties which help learning.
```suggestion
Graph transformer frameworks usually apply specific preprocessing to their datasets to generate added features and properties which help learning.
```

2023-01-17 14:09 UTC, osanseviero commented on graphml-classification.md
> +Here, we use the Graphormer's default preprocessing, which generates in/out degree information, shortest path between nodes matrices, and other properties of interest for the model.
```suggestion
Here, we use Graphormer's default preprocessing, which generates in/out degree information, the shortest path between node matrices, and other properties of interest for the model. 
```

2023-01-17 14:09 UTC, osanseviero commented on graphml-classification.md
> +It is also possible to apply this preprocessing on the fly, in the DataCollator's parameters (by setting `on_the_fly_processing` to True): not all datasets are as small as `ogbg-molhiv`, and for larg
```suggestion
It is also possible to create a new randomly initialized model to train from scratch, either following the known parameters of a given checkpoint or manually choosing them.
```

2023-01-17 14:09 UTC, osanseviero commented on graphml-classification.md
> +Here, we load an existing pretrained model/checkpoint and to fine-tune it on our downstream task, a binary classification task (hence `num_classes = 2`).
```suggestion
Here, we load an existing pretrained model/checkpoint that can be fine-tuned on our downstream task, such as binary classification task (hence `num_classes = 2`). 
```

2023-01-17 14:09 UTC, osanseviero commented on graphml-classification.md
> +It is also possible to create a new randomly initialized model to train from scratch, either following the known parameters of a given checkpoint, or by manually choosing them.
```suggestion
It is also possible to create a new randomly initialized model to train from scratch either following the known parameters of a given checkpoint or by manually choosing them.
```

2023-01-17 14:09 UTC, osanseviero commented on graphml-classification.md
> +For graph datasets, it is particularly important to play around with batch sizes and gradient accumulation steps, to train on enough samples, while avoiding out of memory errors.
```suggestion
For graph datasets, it is particularly important to play around with batch sizes and gradient accumulation steps to train on enough samples while avoiding out-of-memory errors.
```

2023-01-17 14:09 UTC, osanseviero commented on graphml-classification.md
> +Now that you know how to use `transformers` to train a graph classification model, we hope you will try to share your favorite graph transformer checkpoints, models and datasets on the hub for the re
```suggestion
Now that you know how to use `transformers` to train a graph classification model, we hope you will try to share your favorite graph transformer checkpoints, models, and datasets on the Hub for the rest of the community to use!
```

2023-01-17 14:23 UTC, clefourrier commented on graphml-classification.md
> +It is also possible to apply this preprocessing on the fly, in the DataCollator's parameters (by setting `on_the_fly_processing` to True): not all datasets are as small as `ogbg-molhiv`, and for larg
I think this was a comma correction for the previous end of section.

2023-01-20 07:33 UTC, clefourrier commented
@sayakpaul 
I'd like to publish the blog on Monday 30, as the Graphormer PR has been merged :sparkles: and the model will be integrated in the upcoming release of transformers next week - do you think you will have the time to look at it before?

(Btw I'm off from tomorrow for a week so I'll see possible new reviews on Monday 30 also.)

2023-01-20 07:36 UTC, sayakpaul commented
Yes, you will have my reviews before 30th :)

2023-01-20 09:43 UTC, clefourrier commented on graphml-classification.md
> +To follow this tutorial, you need to have installed `datasets` and `transformers` (version >= **TODO**).
Must not forget to update this!!

2023-01-24 02:20 UTC, sayakpaul commented on graphml-classification.md
> +At the moment, the only graph transformer model available in Transformers is Microsoft's Graphormer, so this is the one we will use here. We are looking forward to seeing what other models people wil
Very nice!

* Link the Graphormer paper? 
* Maybe also link the issue thread where you were gathering people's interest to contribute graph models to the library?

2023-01-24 02:22 UTC, sayakpaul commented on graphml-classification.md
> +To follow this tutorial, you need to have installed `datasets` and `transformers` (version >= **TODO**).
Maybe this?

```
pip install -q -U datasets git+https://github.com/huggingface/transformers
```

This way, the users will always have the latest stable release of `datasets` installed and the latest nightly build of `transformers` from the source.

2023-01-24 02:22 UTC, sayakpaul commented on graphml-classification.md
> +To use graph data, you can either start from your own datasets, or use [those available on the Hub][https://huggingface.co/graphs-datasets). We'll focus on using already available ones, but feel free
> https://huggingface.co/graphs-datasets

🤯

2023-01-24 02:23 UTC, sayakpaul commented on graphml-classification.md
> +To use graph data, you can either start from your own datasets, or use [those available on the Hub][https://huggingface.co/graphs-datasets). We'll focus on using already available ones, but feel free
> We'll focus on using already available ones, but feel free to add your datasets!

Maybe hyperlink the "add your datasets" phrase with documentation that a reader can refer to?

2023-01-24 02:24 UTC, sayakpaul commented on graphml-classification.md
> +A single graph is a dictionnary, and here is the expected format for our graph classification datasets:
```suggestion
A single graph is a dictionary, and here is the expected format for our graph classification datasets:
```

2023-01-24 02:25 UTC, sayakpaul commented on graphml-classification.md
> +	- This contains the available attributes (if present) for each edge of the graph, following the `edge_index` ordering.
Do we need to provide examples for these two like the above three ones?

2023-01-24 02:26 UTC, sayakpaul commented on graphml-classification.md
> +Loading a graph dataset from the Hub is very easy. Let's load the `ogbg-mohiv` dataset (a baseline from the Open Graph Benchmark by Stanford), stored in the `OGB` repository:
> a baseline from the Open Graph Benchmark by Stanford

Hyperlink?

2023-01-24 02:26 UTC, sayakpaul commented on graphml-classification.md
> +```
Amazing!

2023-01-24 02:39 UTC, sayakpaul requested changes
Very concise and to the point! Thanks a lot for working on it!

Apart from my comments, I'd suggest adding a notebook that the readers can run on Google Colab. Let me know if you need any guidance on that.

2023-01-24 02:39 UTC, sayakpaul commented on graphml-classification.md
> +Graph transformer frameworks usually apply specific preprocessing to their datasets to generate added features and properties which help learning.
```suggestion
Graph transformer frameworks usually apply specific preprocessing to their datasets to generate added features and properties which help the underlying learning task (classification in our case).
```

2023-01-24 02:39 UTC, sayakpaul commented on graphml-classification.md
> +### Training or fine-tuning
This heading seems to be redundant as we already have it above.

2023-01-24 02:39 UTC, sayakpaul commented on graphml-classification.md
> +# To train from scratch
Aren't we fine-tuning from the checkpoint? If so, this comment seems to be a bit misleading to me. 

I would remove this comment and add some explanatory text below to discuss what the code block is doing and how one can randomly initialize the model in this case. You can refer to [this notebook](https://github.com/huggingface/notebooks/blob/main/examples/image_classification.ipynb) to check how we usually discuss the former.  

Let me know if anything is unclear.

2023-01-24 02:39 UTC, sayakpaul commented on graphml-classification.md
> +from transformers import TrainingArguments, Trainer
Maybe spend a sentence or two to tell the users what Trainer is and provide hyperlinks? [This notebook](https://github.com/huggingface/notebooks/blob/main/examples/image_classification.ipynb) has a nice template of that description. But absolutely feel free to repurpose anything there.

2023-01-24 02:39 UTC, sayakpaul commented on graphml-classification.md
> +)
Can we also do `push_to_hub` to True? If so, I would show that and also at the end of training, call `trainer.push_to_hub()` so that all the fine-tuned artifacts (parameters, metadata, etc.) are pushed to a model repository on the Hub.

2023-01-24 02:39 UTC, sayakpaul commented on graphml-classification.md
> +As this model is quite big, it takes about a day to train/fine-tune for 20 epochs on CPU (IntelCore i7). It can be worth using powerful GPUs and parallelization instead, leveraging `accelerate`.
`Trainer` internally leverages `accelerate`, actually. Maybe you could try running it on Colab (with a GPU)?

Also, I would make the readers aware of the following: how `Trainer` is able to train the model with an objective. Specifically, how is it inferring that information in the first place. This is made possible because the underlying model implements the loss computation part and also returns an object that `Trainer` can use to know the loss quantity.

2023-01-24 02:39 UTC, sayakpaul commented on graphml-classification.md
> +Now that you know how to use `transformers` to train a graph classification model, we hope you will try to share your favorite graph transformer checkpoints, models, and datasets on the Hub for the r
Great conclusion and a passive call for action. Keeping this in mind, I think it would make even more sense to use `push_to_hub()`.

2023-01-24 02:39 UTC, sayakpaul commented on graphml-classification.md
> +Now that you know how to use `transformers` to train a graph classification model, we hope you will try to share your favorite graph transformer checkpoints, models, and datasets on the Hub for the r
Also, can we also show some inference on the samples from the test set and discuss about it?

2023-01-30 08:49 UTC, clefourrier commented on graphml-classification.md
> +To follow this tutorial, you need to have installed `datasets` and `transformers` (version >= **TODO**).
The PR has been merged in transformers 4.26, do you think we should still request people to pull the nightly?

2023-01-30 08:51 UTC, clefourrier commented on graphml-classification.md
> +	- This contains the available attributes (if present) for each edge of the graph, following the `edge_index` ordering.
It's very use case specific imo, people using/needing features will know what they have

2023-01-30 08:59 UTC, clefourrier commented on graphml-classification.md
> +# To train from scratch
We definitely are, it comes from a previous version of the code, well seen! :clap: :

2023-01-30 08:59 UTC, clefourrier commented on graphml-classification.md
> +)
Yes, we can, I'll add it!

2023-01-30 09:01 UTC, clefourrier commented on graphml-classification.md
> +As this model is quite big, it takes about a day to train/fine-tune for 20 epochs on CPU (IntelCore i7). It can be worth using powerful GPUs and parallelization instead, leveraging `accelerate`.
I used to run my code on GPUs on the cluster, but it needed me to explicitly invoke accelerate, using `accelerate launch my_scripts.py`, so I'm not sure I understand your comment there

2023-01-30 09:06 UTC, sayakpaul commented on graphml-classification.md
> +To follow this tutorial, you need to have installed `datasets` and `transformers` (version >= **TODO**).
No then no need. Just installing the latest Transformers version do it.

2023-01-30 09:08 UTC, sayakpaul commented on graphml-classification.md
> +As this model is quite big, it takes about a day to train/fine-tune for 20 epochs on CPU (IntelCore i7). It can be worth using powerful GPUs and parallelization instead, leveraging `accelerate`.
So, Trainer will automatically use accelerate. For launching a script, you might need to do `accelerate launch`. But for Colab, it won't be necessary.

2023-01-30 09:10 UTC, clefourrier commented on graphml-classification.md
> +At the moment, the only graph transformer model available in Transformers is Microsoft's Graphormer, so this is the one we will use here. We are looking forward to seeing what other models people wil
Linking the Graphormer paper, but people interest manifested in [several](https://github.com/huggingface/transformers/issues/20962) [issues](https://github.com/huggingface/blog/issues/767) and I feel it would be confusing to link them all

2023-01-30 09:28 UTC, clefourrier commented on graphml-classification.md
> +### Training or fine-tuning
restructured headings

2023-01-30 09:36 UTC, clefourrier commented on graphml-classification.md
> +from transformers import TrainingArguments, Trainer
Thank you for the reference!

2023-01-30 09:40 UTC, clefourrier commented on graphml-classification.md
> +Now that you know how to use `transformers` to train a graph classification model, we hope you will try to share your favorite graph transformer checkpoints, models, and datasets on the Hub for the r
Do you think it would be a big plus? 
I would need to retrain a model for this.

2023-01-30 09:48 UTC, clefourrier commented on graphml-classification.md
> +As this model is quite big, it takes about a day to train/fine-tune for 20 epochs on CPU (IntelCore i7). It can be worth using powerful GPUs and parallelization instead, leveraging `accelerate`.
Ok, I will edit the text

2023-01-30 10:08 UTC, sayakpaul commented on graphml-classification.md
> +Now that you know how to use `transformers` to train a graph classification model, we hope you will try to share your favorite graph transformer checkpoints, models, and datasets on the Hub for the r
Maybe in an accompanying Colab Notebook? I do think discussing the inference section in isolation makes it more complete.

2023-01-30 10:32 UTC, clefourrier commented on graphml-classification.md
> +Now that you know how to use `transformers` to train a graph classification model, we hope you will try to share your favorite graph transformer checkpoints, models, and datasets on the Hub for the r
Ok, that works for me! Do you have some pointers on how to do a Colab Notebook? :)

2023-01-30 10:49 UTC, clefourrier commented on graphml-classification.md
> +Now that you know how to use `transformers` to train a graph classification model, we hope you will try to share your favorite graph transformer checkpoints, models, and datasets on the Hub for the r
I'm also not clear on how much the contents of the notebook should intersect with the contents of the blog post

2023-01-30 11:21 UTC, sayakpaul commented on graphml-classification.md
> +Now that you know how to use `transformers` to train a graph classification model, we hope you will try to share your favorite graph transformer checkpoints, models, and datasets on the Hub for the r
Sure thing!

We can just add headers and copy-paste the code shown in the blog post. Let me know if anything's unclear.

2023-01-30 13:02 UTC, clefourrier commented on graphml-classification.md
> +    "clefourrier/pcqm4mv2_graphormer_base",
TODO: change path of graphormer checkpoint

2023-03-29 10:00 UTC, gitabtion commented on graphml-classification.md
> +It is also possible to apply this preprocessing on the fly, in the DataCollator's parameters (by setting `on_the_fly_processing` to True): not all datasets are as small as `ogbg-molhiv`, and for larg
I got the "ImportError: cannot import name 'algos_graphormer' from 'transformers.models.graphormer' " when run ''from transformers.models.graphormer.collating_graphormer import preprocess_item, GraphormerDataCollator'', should I build from resource code rather than use pip install transformers?

2023-03-29 10:21 UTC, clefourrier commented on graphml-classification.md
> +It is also possible to apply this preprocessing on the fly, in the DataCollator's parameters (by setting `on_the_fly_processing` to True): not all datasets are as small as `ogbg-molhiv`, and for larg
Hi @gitabtion ! This blog post has not been published yet because I need to update it to follow the last version of the code - I'll come back to it soon and ping you when it's up to date :hugs:

2023-04-11 14:01 UTC, sayakpaul commented
Superb!

I think this should be it:
https://github.com/huggingface/notebooks

@osanseviero WDYT?

2023-04-11 14:02 UTC, clefourrier commented
Amazing! Just going to update the blog so it follows the collab, then we'll be good!

2023-04-11 15:14 UTC, clefourrier commented
Should be good!

2023-04-11 15:19 UTC, osanseviero commented
The blog notebooks can also go in https://github.com/huggingface/blog/tree/main/notebooks

2023-04-12 11:18 UTC, clefourrier commented
@osanseviero added the notebook here then!
Tell me if you think it's good to merge :hugs:

2023-04-14 07:05 UTC, sayakpaul commented
Hi @clefourrier!

I am a bit swamped with a few other things. I will have to pass it sadly.

2023-04-14 07:09 UTC, clefourrier commented
Ok, no problem! Fyi, I don't think it needs another in depth review as you already did one and I integrated your comments - _only thing I did not add was the inference part, because it's hard to render and visualize since graph-datasets are very specialized (for ex, here we classify HIV-inhibiting molecules, would be hard to generalize to any other kind of molecule)_. 

Could you ping someone else who you think would be relevant so we can merge it?

2023-04-14 07:53 UTC, osanseviero approved these changes
Thanks a lot! Please update the date and we can merge :)

2023-04-14 07:53 UTC, osanseviero commented on graphml-classification.md
> +    <small>Published January 30, 2023.</small>
Please update :)

2023-04-14 08:12 UTC, merged