Republish @VictorSanh's blogpost
huggingface/blog pull request #81
Opened 2021-02-02 13:43 UTC by julien-c

2021-02-03 15:01 UTC, VictorSanh requested changes
👍 great thanks
expect the format nit, lgtm!

2021-02-03 15:01 UTC, VictorSanh commented on simple-considerations.md
> +4\. 👀 Tune but don’t tune blindly
nitpicking: Sections 1,2,3, and 4 don't have the same format

2021-02-03 21:34 UTC, stefan-it commented on simple-considerations.md
> +        <img class="avatar avatar-user" src="https://aeiljuispo.cloudimg.io/v7/https://s3.amazonaws.com/moonup/production/uploads/1590600248871-noauth.jpeg?w=200&h=200&f=face" title="Gravatar">
Oh, Victor has a new haircut 🤔

2021-02-04 12:17 UTC, julien-c commented on simple-considerations.md
> +        <img class="avatar avatar-user" src="https://aeiljuispo.cloudimg.io/v7/https://s3.amazonaws.com/moonup/production/uploads/1590600248871-noauth.jpeg?w=200&h=200&f=face" title="Gravatar">
i'm hardcoding his avatar from huggingface.co/victorsanh, @VictorSanh lmk if you want me to change it

2021-02-08 19:39 UTC, VictorSanh approved these changes

2021-02-25 20:31 UTC, merged