add `peft` release blog
huggingface/blog pull request #828
Opened 2023-02-09 11:31 UTC by pacman100

### What does this PR do?
1. PEFT release blog

2023-02-09 12:01 UTC, sayakpaul requested changes
Thanks a lot for this one!

Could you also increase the font size in the thumbnail?

2023-02-09 12:01 UTC, sayakpaul commented on peft.md
> +We've released PEFT as an efficient way of tuning large LLMs on downstream tasks and domains saving a lot of compute and storage while achieving comparable performance to full finetuning. In the comi
```suggestion
We've released PEFT as an efficient way of tuning large LLMs on downstream tasks and domains, saving a lot of compute and storage while achieving comparable performance to full finetuning. In the coming months, we'll be exploring more PEFT methods, such as (IA)3 and bottleneck adapters. Also, focus on new use cases such as INT8 training of [`wishper-large`](https://huggingface.co/openai/whisper-large) model in Colab and tuning of RLHF components such as policy and ranker using PEFT approaches.
```

Possible to also comment on the computer vision use cases so that the readers don't think that PEFT is only limited to LLMs and other large models like Stable Diffusion.

2023-02-09 12:17 UTC, pcuenca reviewed
Great work, I just did a first pass through it and left some comments.

2023-02-09 12:17 UTC, pcuenca commented on peft.md
> +PEFT approaches only fine-tune a small number of (extra) model parameters while freezing most parameters of the pretrained LLMs, thereby greatly decreasing the computational and storage costs. This a
The suggestion block doesn't work for some reason, I suggested a few small fixes:

> PEFT approaches only fine-tune a small number of (extra) model parameters while freezing most parameters of the pretrained LLMs, thereby greatly decreasing the computational and storage costs. This also overcomes the issues of catastrophic forgetting benaviour observed in full finetuning of LLMs. PEFT approaches have also shown to be better than fine-tuning in low-data regimes and generalize better to out-of-domain scenarios. They also help in portability wherein users can tune models using PEFT methods to get tiny checkpoints of just a few MBs, compared to the large checkpoints of full fine-tuning. For example, [`bigscience/mt0-xxl`](https://huggingface.co/bigscience/mt0-xxl) takes up 40GB of storage, so full fine-tuning will lead to 40GB checkpoints for each downstream dataset or task. Using PEFT methods, the trained weights would just be a few MBs for each downstream dataset, all the while achieving comparable performance to full fine-tuning. In short, PEFT approaches enable you to get performance comparable to full fine-tuning while only having a small number of trainable parameters.


Maybe adding a link relative to catastrophic forgetting would be nice.

I think it would also be worth clarifying that the small trained weights are added on top of the pretrained LLM. So the same LLM can be used for multiple tasks by adding small weights; it's not that we can replace the LLM with the small weights.

2023-02-09 12:17 UTC, pcuenca commented on peft.md
> +We focus on the plethora of interesting use-cases in the [README](https://github.com/huggingface/peft#use-cases) of the library. Highlighting below few of the more interesting ones:
```suggestion
We focus on the plethora of interesting use-cases in the [README](https://github.com/huggingface/peft#use-cases) of the library. These are a few of the more interesting ones:
```

2023-02-09 12:17 UTC, pcuenca commented on peft.md
> +🤗 Accelerate's DepSpeed integration: [peft_lora_seq2seq_accelerate_ds_zero3_offload.py](https://github.com/huggingface/peft/blob/main/examples/conditional_generation/peft_lora_seq2seq_accelerate_ds_z
```suggestion
🤗 Accelerate's DeepSpeed integration: [peft_lora_seq2seq_accelerate_ds_zero3_offload.py](https://github.com/huggingface/peft/blob/main/examples/conditional_generation/peft_lora_seq2seq_accelerate_ds_zero3_offload.py). This means you can tune such large LLMs in Google Colab.
```

2023-02-09 12:17 UTC, pcuenca commented on peft.md
> +2. Taking previous example a notch up by enabling INT8 tuning of `OPT-6.7b` model (6.7 Billion parameters) in Google Colab
```suggestion
2. Taking the previous example a notch up by enabling INT8 tuning of `OPT-6.7b` model (6.7 Billion parameters) in Google Colab
```

2023-02-09 12:17 UTC, pcuenca commented on peft.md
> +3. Stable Diffusion Dreambooth tuning using 🤗 PEFT on consumer hardware. Try out the 🤗 Gradio Space which should run seamlessly on a T4 instance (16GB GPU): [smangrul/peft-lora-sd-dreambooth](https:/
Maybe also worth mentioning other consumer hardware with 11 GB of RAM, such as 2080 Ti, 3080, etc. So it works in personal computers, not just colab or cloud services.

Maybe also link to bitsandbytes, and/or to our blog post on 8-bit computing: https://huggingface.co/blog/hf-bitsandbytes-integration

2023-02-09 12:17 UTC, pcuenca commented on peft.md
> +```
If we are not going to explain what the configuration parameters mean, maybe link to the project readme and tell readers to go there for details :)

2023-02-09 12:17 UTC, pcuenca commented on peft.md
> +That's it! Rest of the training loop remains same.
```suggestion
That's it! The rest of the training loop remains same. 
```

2023-02-09 12:17 UTC, pcuenca commented on peft.md
> +```
Maybe put the code first and then the example?

> 4. When you are ready to save or upload the model for inference, just do the following. 
> ```
> model.save_pretrained("output_dir") # model.push_to_hub("my_awesome_peft_model")
> ```
> 
> This will only save the incremental PEFT weights that were trained. For example, you can find the `bigscience/T0_3B` tuned using LoRA on the `twitter_complaints` raft dataset here: [smangrul/twitter_complaints_bigscience_T0_3B_LORA_SEQ_2_SEQ_LM](https://huggingface.co/smangrul/twitter_complaints_bigscience_T0_3B_LORA_SEQ_2_SEQ_LM). Notice that it only contains 2 files: `adapter_config.json` and `adapter_model.bin` with the latter being just `19MB`.

2023-02-09 12:17 UTC, pcuenca commented on peft.md
> +5. To load it for inference, follow the below snippet:
```suggestion
5. To load it for inference, follow the snippet below:
```

2023-02-09 12:17 UTC, pcuenca commented on peft.md
> ++ model = PeftModel.from_pretrained(model, peft_model_id)
Awesome!

2023-02-09 12:17 UTC, pcuenca commented on peft.md
> +Large Language Models (LLMs) based on Transformers architectures like GPT, T5 and BERT have achieved state-of-the-art results in various Natural Language Processing (NLP) tasks and have also started
Maybe also briefly other domains in the intro (such as Stable Diffusion), not just LLMs.

2023-02-09 20:11 UTC, sgugger approved these changes
Great, thanks a lot for writing this!

2023-02-09 20:11 UTC, sgugger commented on peft.md
> +1. Using 🤗 PEFT LoRA for tuning `bigscience/T0_3B` model (3 Billion parameters) on consumer hardware with 16GB GPU using
Maybe precise which hardware here.

2023-02-09 20:11 UTC, sgugger commented on peft.md
> +tokenizer_name_or_path = "bigscience/mt0-large"
```suggestion
  from transformers import AutoModelForSeq2SeqLM
+ from peft import get_peft_model, LoraConfig, TaskType

  model_name_or_path = "bigscience/mt0-large"
  tokenizer_name_or_path = "bigscience/mt0-large"
```

2023-02-09 20:11 UTC, sgugger commented on peft.md
> +```
```suggestion
```py
```

2023-02-09 20:11 UTC, sgugger commented on peft.md
> +```diff
Same for this sample.

2023-02-09 20:11 UTC, sgugger commented on peft.md
> +We've released PEFT as an efficient way of tuning large LLMs on downstream tasks and domains, saving a lot of compute and storage while achieving comparable performance to full finetuning. In the com
```suggestion
We've released PEFT as an efficient way of tuning large LLMs on downstream tasks and domains, saving a lot of compute and storage while achieving comparable performance to full finetuning. In the coming months, we'll be exploring more PEFT methods, such as (IA)3 and bottleneck adapters. Also, focus on new use cases such as INT8 training of [`whisper-large`](https://huggingface.co/openai/whisper-large) model in Colab and tuning of RLHF components such as policy and ranker using PEFT approaches.
```

2023-02-09 20:48 UTC, LysandreJik reviewed
Cool blogpost!!

2023-02-09 20:48 UTC, LysandreJik commented on peft.md
> +<h1>Parameter-Efficient Fine-Tuning using 🤗 PEFT</h1>
I wonder if we don't want a bit more of a flashy title?

Something like (just examples):
- PEFT: fine-tune billion-scale models on consumer hardware
- Fine-tuning very large transformer models in a matter of minutes using PEFT
- ...

2023-02-09 20:55 UTC, osanseviero approved these changes
Very cool blog post! :fire:

2023-02-09 20:55 UTC, osanseviero commented on peft.md
> +---
You'll also need to change https://github.com/huggingface/blog/blob/main/_blog.yml so the blog is included

2023-02-09 20:55 UTC, osanseviero commented on peft.md
> +Large Language Models (LLMs) based on Transformers architectures like GPT, T5, and BERT have achieved state-of-the-art results in various Natural Language Processing (NLP) tasks. They have also start
```suggestion
Large Language Models (LLMs) based on Transformers architectures like GPT, T5, and BERT have achieved state-of-the-art results in various Natural Language Processing (NLP) tasks. They have also started foraying into other domains, such as Computer Vision (CV) and Audio. The conventional paradigm is large-scale pretraining on generic web-scale data followed by fine-tuning to downstream tasks. Fine-tuning these pretrained LLMs on downstream datasets results in huge performance gains compared to using the pretrained LLMs out-of-the-box (zero-shot inference, for example).
```

2023-02-09 20:55 UTC, osanseviero commented on peft.md
> +However, as models get larger and larger, full finetuning becomes infeasible to train on consumer hardware, and storing and deploying fine-tuned models independently for each downstream task becomes
```suggestion
However, as models get larger and larger, full fine-tuning becomes infeasible to train on consumer hardware, and storing and deploying fine-tuned models independently for each downstream task becomes very expensive. Parameter-Efficient Fine-tuning (PEFT) approaches are meant to address this problem!
```

2023-02-09 20:55 UTC, osanseviero commented on peft.md
> +Today, we are excited is excited to introduce 🤗 PEFT library which provides the latest Parameter-Efficient Fine-tuning techniques seamlessly integrated with 🤗 Transformers and 🤗 Accelerate. This enab
```suggestion
Today, we are excited to introduce the 🤗 PEFT library, which provides the latest Parameter-Efficient Fine-tuning techniques seamlessly integrated with 🤗 Transformers and 🤗 Accelerate. This enables using the most popular and performant models from 🤗 Transformers coupled with the simplicity and scalability of 🤗 Accelerate. Below are the currently supported PEFT methods, with more coming soon:
```

2023-02-09 20:55 UTC, osanseviero commented on peft.md
> +3. Stable Diffusion Dreambooth training using 🤗 PEFT on consumer hardware. Try out the 🤗 Gradio Space, which should run seamlessly on a T4 instance (16GB GPU): [smangrul/peft-lora-sd-dreambooth](http
```suggestion
3. Stable Diffusion Dreambooth training using 🤗 PEFT on consumer hardware. Try out the Space demo, which should run seamlessly on a T4 instance (16GB GPU): [smangrul/peft-lora-sd-dreambooth](https://huggingface.co/spaces/smangrul/peft-lora-sd-dreambooth).
```

2023-02-09 20:55 UTC, osanseviero commented on peft.md
> +```
```suggestion
```py
```

2023-02-10 08:10 UTC, pacman100 commented on peft.md
> +<h1>Parameter-Efficient Fine-Tuning using 🤗 PEFT</h1>
Done. Updated it to `🤗 PEFT: Parameter-Efficient Fine-Tuning of Billion-Scale Models on Low-Resource Hardware`

2023-02-10 08:11 UTC, pacman100 commented on peft.md
> +---
Done, Thank you!

2023-02-10 10:09 UTC, merged